// genres/modern/professions.js
// Each profession carries: title, industry, economicTier (1-5),
// statAffinity (the stats that make this profession more likely),
// sentiments (pool to draw from randomly)
//
// Economic tiers:
//   1 = poverty / survival
//   2 = working poor
//   3 = working / lower-middle class
//   4 = middle / upper-middle class
//   5 = wealthy / elite

export const SENTIMENTS = ['proud', 'resentful', 'indifferent', 'passionate', 'burned out', 'desperate', 'quietly satisfied', 'ashamed'];

export const PROFESSIONS = [

  // ── BLUE COLLAR / TRADES ──────────────────────────────────────────────────
  {
    title: 'Dock worker',
    industry: 'Shipping & logistics',
    economicTier: 2,
    statAffinity: { strength: 1.4, constitution: 1.2 },
    sentiments: ['resentful', 'burned out', 'quietly satisfied', 'proud'],
  },
  {
    title: 'Electrician',
    industry: 'Trades',
    economicTier: 3,
    statAffinity: { dexterity: 1.3, intelligence: 1.1 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent'],
  },
  {
    title: 'Plumber',
    industry: 'Trades',
    economicTier: 3,
    statAffinity: { strength: 1.2, dexterity: 1.2 },
    sentiments: ['proud', 'indifferent', 'quietly satisfied'],
  },
  {
    title: 'Auto mechanic',
    industry: 'Automotive',
    economicTier: 3,
    statAffinity: { dexterity: 1.3, intelligence: 1.1, strength: 1.1 },
    sentiments: ['passionate', 'proud', 'quietly satisfied', 'burned out'],
  },
  {
    title: 'Long-haul truck driver',
    industry: 'Transportation',
    economicTier: 3,
    statAffinity: { constitution: 1.3, wisdom: 1.1 },
    sentiments: ['indifferent', 'quietly satisfied', 'lonely', 'burned out'],
  },
  {
    title: 'Construction worker',
    industry: 'Construction',
    economicTier: 2,
    statAffinity: { strength: 1.5, constitution: 1.3 },
    sentiments: ['resentful', 'proud', 'burned out', 'indifferent'],
  },
  {
    title: 'Welder',
    industry: 'Manufacturing',
    economicTier: 3,
    statAffinity: { strength: 1.3, dexterity: 1.3 },
    sentiments: ['proud', 'indifferent', 'quietly satisfied'],
  },
  {
    title: 'Garbage collector',
    industry: 'Municipal services',
    economicTier: 2,
    statAffinity: { constitution: 1.4, strength: 1.2 },
    sentiments: ['resentful', 'indifferent', 'quietly satisfied', 'ashamed'],
  },
  {
    title: 'Factory line worker',
    industry: 'Manufacturing',
    economicTier: 2,
    statAffinity: { constitution: 1.3, dexterity: 1.1 },
    sentiments: ['resentful', 'burned out', 'indifferent'],
  },
  {
    title: 'Warehouse worker',
    industry: 'Logistics',
    economicTier: 2,
    statAffinity: { strength: 1.3, constitution: 1.2 },
    sentiments: ['resentful', 'burned out', 'indifferent', 'desperate'],
  },

  // ── SERVICE INDUSTRY ──────────────────────────────────────────────────────
  {
    title: 'Barista',
    industry: 'Food & beverage',
    economicTier: 2,
    statAffinity: { charisma: 1.2, dexterity: 1.1 },
    sentiments: ['indifferent', 'quietly satisfied', 'passionate', 'burned out'],
  },
  {
    title: 'Line cook',
    industry: 'Food & beverage',
    economicTier: 2,
    statAffinity: { dexterity: 1.3, constitution: 1.2 },
    sentiments: ['passionate', 'burned out', 'resentful', 'proud'],
  },
  {
    title: 'Restaurant manager',
    industry: 'Food & beverage',
    economicTier: 3,
    statAffinity: { charisma: 1.3, wisdom: 1.2 },
    sentiments: ['burned out', 'proud', 'resentful', 'quietly satisfied'],
  },
  {
    title: 'Hotel front desk clerk',
    industry: 'Hospitality',
    economicTier: 2,
    statAffinity: { charisma: 1.3, wisdom: 1.1 },
    sentiments: ['indifferent', 'burned out', 'quietly satisfied'],
  },
  {
    title: 'Rideshare driver',
    industry: 'Gig economy',
    economicTier: 2,
    statAffinity: { charisma: 1.2, wisdom: 1.1 },
    sentiments: ['resentful', 'indifferent', 'desperate', 'quietly satisfied'],
  },
  {
    title: 'Tattoo artist',
    industry: 'Personal services',
    economicTier: 3,
    statAffinity: { dexterity: 1.5, charisma: 1.2 },
    sentiments: ['passionate', 'proud', 'quietly satisfied'],
  },
  {
    title: 'Hairdresser',
    industry: 'Personal services',
    economicTier: 3,
    statAffinity: { charisma: 1.4, dexterity: 1.2 },
    sentiments: ['passionate', 'quietly satisfied', 'burned out', 'proud'],
  },
  {
    title: 'Personal trainer',
    industry: 'Fitness',
    economicTier: 3,
    statAffinity: { strength: 1.4, charisma: 1.3, constitution: 1.2 },
    sentiments: ['passionate', 'proud', 'indifferent', 'burned out'],
  },
  {
    title: 'Security guard',
    industry: 'Private security',
    economicTier: 2,
    statAffinity: { strength: 1.3, constitution: 1.2 },
    sentiments: ['indifferent', 'resentful', 'quietly satisfied', 'burned out'],
  },
  {
    title: 'Delivery driver',
    industry: 'Gig economy',
    economicTier: 2,
    statAffinity: { constitution: 1.2, dexterity: 1.1 },
    sentiments: ['indifferent', 'resentful', 'desperate'],
  },

  // ── CREATIVE / ARTS ───────────────────────────────────────────────────────
  {
    title: 'Freelance graphic designer',
    industry: 'Creative services',
    economicTier: 3,
    statAffinity: { intelligence: 1.3, dexterity: 1.2, charisma: 1.1 },
    sentiments: ['passionate', 'burned out', 'quietly satisfied', 'desperate'],
  },
  {
    title: 'Struggling musician',
    industry: 'Entertainment',
    economicTier: 1,
    statAffinity: { charisma: 1.4, wisdom: 1.2 },
    sentiments: ['passionate', 'desperate', 'resentful', 'burned out'],
  },
  {
    title: 'Working actor',
    industry: 'Entertainment',
    economicTier: 2,
    statAffinity: { charisma: 1.5, intelligence: 1.2 },
    sentiments: ['passionate', 'desperate', 'burned out', 'quietly satisfied'],
  },
  {
    title: 'Photographer',
    industry: 'Creative services',
    economicTier: 3,
    statAffinity: { dexterity: 1.2, intelligence: 1.2, charisma: 1.1 },
    sentiments: ['passionate', 'indifferent', 'quietly satisfied'],
  },
  {
    title: 'Tattoo artist',
    industry: 'Art & personal services',
    economicTier: 3,
    statAffinity: { dexterity: 1.5, charisma: 1.2 },
    sentiments: ['passionate', 'proud', 'quietly satisfied'],
  },
  {
    title: 'Freelance writer',
    industry: 'Media',
    economicTier: 2,
    statAffinity: { intelligence: 1.4, wisdom: 1.2 },
    sentiments: ['passionate', 'desperate', 'burned out', 'quietly satisfied'],
  },
  {
    title: 'Graffiti artist',
    industry: 'Street art',
    economicTier: 1,
    statAffinity: { dexterity: 1.4, charisma: 1.2 },
    sentiments: ['passionate', 'resentful', 'proud'],
  },

  // ── WHITE COLLAR / PROFESSIONAL ───────────────────────────────────────────
  {
    title: 'Accountant',
    industry: 'Finance',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, wisdom: 1.2 },
    sentiments: ['indifferent', 'quietly satisfied', 'burned out', 'resentful'],
  },
  {
    title: 'Software developer',
    industry: 'Technology',
    economicTier: 4,
    statAffinity: { intelligence: 1.5, dexterity: 1.1 },
    sentiments: ['passionate', 'burned out', 'indifferent', 'quietly satisfied'],
  },
  {
    title: 'Nurse',
    industry: 'Healthcare',
    economicTier: 3,
    statAffinity: { wisdom: 1.3, constitution: 1.2, charisma: 1.1 },
    sentiments: ['passionate', 'burned out', 'proud', 'resentful'],
  },
  {
    title: 'Paramedic',
    industry: 'Emergency services',
    economicTier: 3,
    statAffinity: { constitution: 1.3, wisdom: 1.3, dexterity: 1.2 },
    sentiments: ['passionate', 'burned out', 'proud'],
  },
  {
    title: 'High school teacher',
    industry: 'Education',
    economicTier: 3,
    statAffinity: { wisdom: 1.4, charisma: 1.2, intelligence: 1.1 },
    sentiments: ['passionate', 'burned out', 'resentful', 'quietly satisfied'],
  },
  {
    title: 'Social worker',
    industry: 'Public services',
    economicTier: 3,
    statAffinity: { wisdom: 1.4, charisma: 1.2 },
    sentiments: ['passionate', 'burned out', 'resentful', 'quietly satisfied'],
  },
  {
    title: 'Lawyer',
    industry: 'Legal',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, charisma: 1.3, wisdom: 1.1 },
    sentiments: ['proud', 'burned out', 'indifferent', 'quietly satisfied'],
  },
  {
    title: 'Corporate HR manager',
    industry: 'Corporate',
    economicTier: 4,
    statAffinity: { charisma: 1.3, wisdom: 1.2 },
    sentiments: ['indifferent', 'burned out', 'quietly satisfied', 'resentful'],
  },
  {
    title: 'Financial analyst',
    industry: 'Finance',
    economicTier: 4,
    statAffinity: { intelligence: 1.5, wisdom: 1.1 },
    sentiments: ['indifferent', 'proud', 'burned out', 'quietly satisfied'],
  },
  {
    title: 'Journalist',
    industry: 'Media',
    economicTier: 3,
    statAffinity: { intelligence: 1.3, charisma: 1.3, wisdom: 1.1 },
    sentiments: ['passionate', 'burned out', 'resentful', 'quietly satisfied'],
  },
  {
    title: 'Therapist',
    industry: 'Mental health',
    economicTier: 4,
    statAffinity: { wisdom: 1.5, charisma: 1.2, intelligence: 1.1 },
    sentiments: ['passionate', 'quietly satisfied', 'burned out'],
  },
  {
    title: 'Pharmacist',
    industry: 'Healthcare',
    economicTier: 4,
    statAffinity: { intelligence: 1.3, wisdom: 1.2 },
    sentiments: ['indifferent', 'quietly satisfied', 'burned out'],
  },

  // ── SALES / HUSTLE ────────────────────────────────────────────────────────
  {
    title: 'Car salesperson',
    industry: 'Automotive',
    economicTier: 3,
    statAffinity: { charisma: 1.5, intelligence: 1.1 },
    sentiments: ['proud', 'indifferent', 'resentful', 'burned out'],
  },
  {
    title: 'Real estate agent',
    industry: 'Real estate',
    economicTier: 4,
    statAffinity: { charisma: 1.5, wisdom: 1.2 },
    sentiments: ['proud', 'passionate', 'burned out', 'quietly satisfied'],
  },
  {
    title: 'Insurance salesperson',
    industry: 'Finance',
    economicTier: 3,
    statAffinity: { charisma: 1.4, intelligence: 1.1 },
    sentiments: ['indifferent', 'resentful', 'burned out', 'ashamed'],
  },
  {
    title: 'Pawn shop owner',
    industry: 'Retail',
    economicTier: 3,
    statAffinity: { charisma: 1.3, intelligence: 1.2, wisdom: 1.1 },
    sentiments: ['quietly satisfied', 'indifferent', 'proud'],
  },

  // ── LAW ENFORCEMENT / MILITARY ────────────────────────────────────────────
  {
    title: 'Police officer',
    industry: 'Law enforcement',
    economicTier: 3,
    statAffinity: { strength: 1.3, constitution: 1.2, charisma: 1.1 },
    sentiments: ['proud', 'burned out', 'resentful', 'quietly satisfied'],
  },
  {
    title: 'Private investigator',
    industry: 'Security',
    economicTier: 3,
    statAffinity: { intelligence: 1.3, wisdom: 1.3, dexterity: 1.1 },
    sentiments: ['passionate', 'quietly satisfied', 'burned out', 'indifferent'],
  },
  {
    title: 'Bounty hunter',
    industry: 'Security',
    economicTier: 3,
    statAffinity: { strength: 1.4, dexterity: 1.2, wisdom: 1.1 },
    sentiments: ['passionate', 'proud', 'indifferent'],
  },
  {
    title: 'Military veteran (recently discharged)',
    industry: 'Military',
    economicTier: 2,
    statAffinity: { strength: 1.4, constitution: 1.3, wisdom: 1.1 },
    sentiments: ['lost', 'proud', 'resentful', 'burned out'],
  },
  {
    title: 'Firefighter',
    industry: 'Emergency services',
    economicTier: 3,
    statAffinity: { strength: 1.4, constitution: 1.3, charisma: 1.1 },
    sentiments: ['proud', 'passionate', 'burned out'],
  },

  // ── CRIMINAL / UNDERGROUND ────────────────────────────────────────────────
  {
    title: 'Street-level drug dealer',
    industry: 'Criminal',
    economicTier: 2,
    statAffinity: { charisma: 1.3, strength: 1.2, wisdom: 0.8 },
    sentiments: ['desperate', 'resentful', 'proud', 'ashamed'],
  },
  {
    title: 'Mid-level drug distributor',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { charisma: 1.3, intelligence: 1.2, strength: 1.1 },
    sentiments: ['proud', 'quietly satisfied', 'desperate', 'resentful'],
  },
  {
    title: 'Fixer',
    industry: 'Criminal',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, charisma: 1.3, wisdom: 1.2 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent'],
  },
  {
    title: 'Con artist',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { charisma: 1.6, intelligence: 1.3, wisdom: 0.9 },
    sentiments: ['proud', 'passionate', 'indifferent', 'quietly satisfied'],
  },
  {
    title: 'Pickpocket / petty thief',
    industry: 'Criminal',
    economicTier: 1,
    statAffinity: { dexterity: 1.5, charisma: 1.2 },
    sentiments: ['desperate', 'resentful', 'indifferent', 'ashamed'],
  },
  {
    title: 'Burglar',
    industry: 'Criminal',
    economicTier: 2,
    statAffinity: { dexterity: 1.5, intelligence: 1.2 },
    sentiments: ['proud', 'desperate', 'indifferent', 'resentful'],
  },
  {
    title: 'Enforcer / muscle',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { strength: 1.6, constitution: 1.3 },
    sentiments: ['proud', 'indifferent', 'resentful', 'ashamed'],
  },
  {
    title: 'Getaway driver',
    industry: 'Criminal',
    economicTier: 2,
    statAffinity: { dexterity: 1.4, constitution: 1.2 },
    sentiments: ['indifferent', 'desperate', 'quietly satisfied', 'resentful'],
  },
  {
    title: 'Hacker / cybercriminal',
    industry: 'Criminal',
    economicTier: 4,
    statAffinity: { intelligence: 1.6, dexterity: 1.2 },
    sentiments: ['passionate', 'proud', 'indifferent', 'quietly satisfied'],
  },
  {
    title: 'Money launderer',
    industry: 'Criminal',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, charisma: 1.2, wisdom: 1.1 },
    sentiments: ['indifferent', 'quietly satisfied', 'ashamed', 'proud'],
  },
  {
    title: 'Forger',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { intelligence: 1.3, dexterity: 1.4 },
    sentiments: ['passionate', 'proud', 'quietly satisfied'],
  },
  {
    title: 'Underground fight promoter',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { charisma: 1.4, strength: 1.2, intelligence: 1.1 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent'],
  },

  // ── ELITE / WEALTHY ───────────────────────────────────────────────────────
  {
    title: 'Investment banker',
    industry: 'Finance',
    economicTier: 5,
    statAffinity: { intelligence: 1.5, charisma: 1.3 },
    sentiments: ['proud', 'burned out', 'indifferent', 'quietly satisfied'],
  },
  {
    title: 'Surgeon',
    industry: 'Healthcare',
    economicTier: 5,
    statAffinity: { intelligence: 1.5, dexterity: 1.4, wisdom: 1.2 },
    sentiments: ['proud', 'burned out', 'passionate', 'quietly satisfied'],
  },
  {
    title: 'Corporate executive',
    industry: 'Corporate',
    economicTier: 5,
    statAffinity: { charisma: 1.4, intelligence: 1.3, wisdom: 1.2 },
    sentiments: ['proud', 'indifferent', 'burned out', 'quietly satisfied'],
  },
  {
    title: 'Corrupt politician',
    industry: 'Government',
    economicTier: 5,
    statAffinity: { charisma: 1.5, intelligence: 1.3, wisdom: 0.9 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent'],
  },
  {
    title: 'Crime boss',
    industry: 'Criminal',
    economicTier: 5,
    statAffinity: { charisma: 1.5, intelligence: 1.4, strength: 1.1 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent'],
  },
];
