// genres/sci-fi/professions.js
// Each profession carries: title, industry, economicTier (1-5),
// statAffinity (stats that make this profession more likely),
// sentiments (pool to draw from randomly)
//
// Economic tiers:
//   1 = below the line / grey-market survival
//   2 = wage-serf / corp labour
//   3 = independent contractor / working class
//   4 = corporate citizen / professional class
//   5 = elite / executive

import { SENTIMENTS } from '../../common/sentiments.js';

export const PROFESSIONS = [

  // ── CREW & HAULERS ────────────────────────────────────────────────────────
  {
    title: 'Freighter Pilot',
    industry: 'Shipping & transit',
    economicTier: 3,
    statAffinity: { dexterity: 1.4, wisdom: 1.2 },
    sentiments: ['proud', 'quietly satisfied', 'burned out', 'indifferent'],
    iconPrompt: 'A seasoned freighter pilot navigating through asteroid fields, wearing a weathered flight suit and goggles.',
    iconPath: 'icons/PROFESSIONS#1#freighter_pilot.png',
  },
  {
    title: 'Ship Engineer',
    industry: 'Shipping & transit',
    economicTier: 3,
    statAffinity: { intelligence: 1.3, dexterity: 1.3 },
    sentiments: ['proud', 'passionate', 'quietly satisfied', 'burned out'],
    iconPrompt: 'A ship engineer working on a spaceship engine, wearing a mechanic suit with tools.',
    iconPath: 'icons/PROFESSIONS#2#ship_engineer.png',
  },
  {
    title: 'Cargo Hauler',
    industry: 'Logistics',
    economicTier: 2,
    statAffinity: { constitution: 1.3, strength: 1.2 },
    sentiments: ['resentful', 'indifferent', 'burned out', 'desperate'],
    iconPrompt: 'A cargo hauler loading goods onto a freighter, wearing a utilitarian work suit.',
    iconPath: 'icons/PROFESSIONS#3#cargo_hauler.png',
  },
  {
    title: 'Navigation Specialist',
    industry: 'Shipping & transit',
    economicTier: 3,
    statAffinity: { intelligence: 1.4, wisdom: 1.2 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent', 'passionate'],
    iconPrompt: 'A navigation specialist plotting a course through a star map, wearing a command uniform with a headset.',
    iconPath: 'icons/PROFESSIONS#4#navigation_specialist.png',
  },
  {
    title: 'Shuttle Operator',
    industry: 'Transit',
    economicTier: 2,
    statAffinity: { dexterity: 1.2 },
    sentiments: ['indifferent', 'burned out', 'quietly satisfied', 'resentful'],
    iconPrompt: 'A shuttle operator guiding a small spacecraft through docking ports, wearing a transit uniform.',
    iconPath: 'icons/PROFESSIONS#5#shuttle_operator.png',
  },

  // ── SECURITY & COMBAT ─────────────────────────────────────────────────────
  {
    title: 'Corporate Mercenary',
    industry: 'Security',
    economicTier: 3,
    statAffinity: { strength: 1.5, constitution: 1.3 },
    sentiments: ['proud', 'indifferent', 'resentful', 'burned out'],
    iconPrompt: 'A corporate mercenary in a tactical uniform, carrying a high-tech weapon.',
    iconPath: 'icons/PROFESSIONS#6#corporate_mercenary.png',
  },
  {
    title: 'Bounty Hunter',
    industry: 'Security',
    economicTier: 3,
    statAffinity: { strength: 1.3, dexterity: 1.2, wisdom: 1.2 },
    sentiments: ['proud', 'indifferent', 'passionate', 'quietly satisfied'],
    iconPrompt: 'A bounty hunter in a rugged suit, holding a tracking device.',
    iconPath: 'icons/PROFESSIONS#7#bounty_hunter.png',
  },
  {
    title: 'Station Security',
    industry: 'Security',
    economicTier: 2,
    statAffinity: { strength: 1.2, constitution: 1.2 },
    sentiments: ['indifferent', 'burned out', 'resentful', 'quietly satisfied'],
    iconPrompt: 'A station security officer on patrol, wearing a standard security uniform with a radio.',
    iconPath: 'icons/PROFESSIONS#8#station_security.png',
  },
  {
    title: 'Military Veteran',
    industry: 'Military',
    economicTier: 2,
    statAffinity: { strength: 1.4, constitution: 1.3, wisdom: 1.1 },
    sentiments: ['lost', 'proud', 'resentful', 'burned out'],
    iconPrompt: 'A military veteran in a worn uniform, carrying a service medal.',
    iconPath: 'icons/PROFESSIONS#9#military_veteran.png',
  },
  {
    title: 'Combat Medic',
    industry: 'Medical',
    economicTier: 3,
    statAffinity: { wisdom: 1.3, dexterity: 1.3, constitution: 1.2 },
    sentiments: ['proud', 'burned out', 'passionate', 'quietly satisfied'],
    iconPrompt: 'A combat medic in a medical uniform, tending to a wounded soldier.',
    iconPath: 'icons/PROFESSIONS#10#combat_medic.png',
  },

  // ── TECH & DATA ───────────────────────────────────────────────────────────
  {
    title: 'Hacker / Netrunner',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { intelligence: 1.6, dexterity: 1.2 },
    sentiments: ['passionate', 'proud', 'indifferent', 'quietly satisfied'],
    iconPrompt: 'A hacker in a dark room, surrounded by screens and cables.',
    iconPath: 'icons/PROFESSIONS#11#hacker_netrunner.png',
  },
  {
    title: 'AI Technician',
    industry: 'Technology',
    economicTier: 4,
    statAffinity: { intelligence: 1.5, wisdom: 1.2 },
    sentiments: ['passionate', 'proud', 'indifferent', 'burned out'],
    iconPrompt: 'An AI technician working on a holographic interface, wearing a tech uniform.',
    iconPath: 'icons/PROFESSIONS#12#ai_technician.png',
  },
  {
    title: 'Data Broker',
    industry: 'Information',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, charisma: 1.3, wisdom: 1.1 },
    sentiments: ['quietly satisfied', 'indifferent', 'proud', 'burned out'],
    iconPrompt: 'A data broker in a sleek office, surrounded by data streams.',
    iconPath: 'icons/PROFESSIONS#13#data_broker.png',
  },
  {
    title: 'Systems Analyst',
    industry: 'Technology',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, dexterity: 1.1 },
    sentiments: ['indifferent', 'quietly satisfied', 'burned out', 'passionate'],
    iconPrompt: 'A systems analyst working at a console, reviewing data streams.',
    iconPath: 'icons/PROFESSIONS#14#systems_analyst.png',
  },
  {
    title: 'Comm Tech',
    industry: 'Communications',
    economicTier: 3,
    statAffinity: { intelligence: 1.2, dexterity: 1.2 },
    sentiments: ['indifferent', 'burned out', 'quietly satisfied', 'resentful'],
    iconPrompt: 'A comm tech working on communication equipment, wearing a tech uniform.',
    iconPath: 'icons/PROFESSIONS#15#comm_tech.png',
  },
  {
    title: 'Pleasure Droid Maintenance Tech',
    industry: 'Entertainment',
    economicTier: 3,
    statAffinity: { intelligence: 1.1, dexterity: 1.2 },
    sentiments: ['indifferent', 'burned out', 'resentful', 'ashamed', 'desperate'],
    iconPrompt: 'A pleasure droid maintenance tech working on a droid, wearing a tech uniform.',
    iconPath: 'icons/PROFESSIONS#16#pleasure_droid_maintenance_tech.png',
  },

  // ── MEDICAL ───────────────────────────────────────────────────────────────
  {
    title: 'Street Doc',
    industry: 'Medical',
    economicTier: 3,
    statAffinity: { intelligence: 1.4, dexterity: 1.3, wisdom: 1.2 },
    sentiments: ['passionate', 'burned out', 'proud', 'resentful'],
    iconPrompt: 'A street doc working in a makeshift clinic, wearing a medical uniform.',
    iconPath: 'icons/PROFESSIONS#17#street_doc.png',
  },
  {
    title: 'Corporate Physician',
    industry: 'Medical',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, wisdom: 1.3 },
    sentiments: ['indifferent', 'quietly satisfied', 'burned out', 'proud'],
    iconPrompt: 'A corporate physician in a sleek office, wearing a medical uniform.',
    iconPath: 'icons/PROFESSIONS#18#corporate_physician.png',
  },
  {
    title: 'Gene-Tech',
    industry: 'Biotech',
    economicTier: 4,
    statAffinity: { intelligence: 1.5, dexterity: 1.2 },
    sentiments: ['passionate', 'proud', 'indifferent', 'quietly satisfied'],
    iconPrompt: 'A gene-tech working on genetic material, wearing a lab coat.',
    iconPath: 'icons/PROFESSIONS#19#gene_tech.png',
  },
  {
    title: 'Psych-Tech',
    industry: 'Medical',
    economicTier: 4,
    statAffinity: { wisdom: 1.5, intelligence: 1.3 },
    sentiments: ['passionate', 'burned out', 'quietly satisfied', 'indifferent'],
    iconPrompt: 'A psych-tech working on a patient, wearing a medical uniform.',
    iconPath: 'icons/PROFESSIONS#20#psych_tech.png',
  },

  // ── CRIMINAL ──────────────────────────────────────────────────────────────
  {
    title: 'Smuggler',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { dexterity: 1.3, charisma: 1.2, wisdom: 1.1 },
    sentiments: ['proud', 'indifferent', 'quietly satisfied', 'desperate'],
    iconPrompt: 'A smuggler in a dark room, surrounded by cargo.',
    iconPath: 'icons/PROFESSIONS#21#smuggler.png',
  },
  {
    title: 'Black-Market Dealer',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { charisma: 1.4, intelligence: 1.2 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent', 'desperate'],
    iconPrompt: 'A black-market dealer in a dark room, surrounded by goods.',
    iconPath: 'icons/PROFESSIONS#22#black_market_dealer.png',
  },
  {
    title: 'Corporate Spy',
    industry: 'Criminal',
    economicTier: 4,
    statAffinity: { charisma: 1.4, intelligence: 1.3, wisdom: 1.2 },
    sentiments: ['indifferent', 'quietly satisfied', 'burned out', 'proud'],
    iconPrompt: 'A corporate spy in a dark room, surrounded by documents.',
    iconPath: 'icons/PROFESSIONS#23#corporate_spy.png',
  },
  {
    title: 'Fixer',
    industry: 'Criminal',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, charisma: 1.4, wisdom: 1.2 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent'],
    iconPrompt: 'A fixer in a dark room, surrounded by documents.',
    iconPath: 'icons/PROFESSIONS#24#fixer.png',
  },
  {
    title: 'Augmentation Bootlegger',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { intelligence: 1.3, dexterity: 1.2 },
    sentiments: ['proud', 'passionate', 'indifferent', 'desperate'],
    iconPrompt: 'An augmentation bootlegger in a dark room, surrounded by augmented parts.',
    iconPath: 'icons/PROFESSIONS#25#augmentation_bootlegger.png',
  },
  {
    title: 'Memory Thief',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { dexterity: 1.4, intelligence: 1.3 },
    sentiments: ['indifferent', 'quietly satisfied', 'ashamed', 'proud'],
    iconPrompt: 'A memory thief in a dark room, surrounded by memory chips.',
    iconPath: 'icons/PROFESSIONS#26#memory_thief.png',
  },
  {
    title: 'Undercity Enforcer',
    industry: 'Criminal',
    economicTier: 2,
    statAffinity: { strength: 1.5, constitution: 1.3 },
    sentiments: ['proud', 'indifferent', 'resentful', 'ashamed'],
    iconPrompt: 'An undercity enforcer in a dark room, surrounded by criminals.',
    iconPath: 'icons/PROFESSIONS#27#undercity_enforcer.png',
  },

  // ── CORPORATE ─────────────────────────────────────────────────────────────
  {
    title: 'Mid-Level Corporate Suit',
    industry: 'Corporate',
    economicTier: 4,
    statAffinity: { charisma: 1.3, intelligence: 1.2 },
    sentiments: ['indifferent', 'burned out', 'quietly satisfied', 'resentful'],
    iconPrompt: 'A mid-level corporate suit in a dark room, surrounded by documents.',
    iconPath: 'icons/PROFESSIONS#28#mid_level_corporate_suit.png',
  },
  {
    title: 'Compliance Officer',
    industry: 'Corporate',
    economicTier: 4,
    statAffinity: { wisdom: 1.3, intelligence: 1.2 },
    sentiments: ['indifferent', 'burned out', 'quietly satisfied', 'ashamed'],
    iconPrompt: 'A compliance officer in a dark room, surrounded by documents.',
    iconPath: 'icons/PROFESSIONS#29#compliance_officer.png',
  },
  {
    title: 'Propaganda Specialist',
    industry: 'Corporate',
    economicTier: 4,
    statAffinity: { charisma: 1.5, intelligence: 1.2 },
    sentiments: ['indifferent', 'ashamed', 'quietly satisfied', 'burned out'],
    iconPrompt: 'A propaganda specialist in a dark room, surrounded by propaganda materials.',
    iconPath: 'icons/PROFESSIONS#30#propaganda_specialist.png',
  },

  // ── SCIENCE ───────────────────────────────────────────────────────────────
  {
    title: 'Terraforming Engineer',
    industry: 'Science',
    economicTier: 3,
    statAffinity: { intelligence: 1.4, wisdom: 1.2, constitution: 1.1 },
    sentiments: ['passionate', 'proud', 'burned out', 'quietly satisfied'],
    iconPrompt: 'A terraforming engineer in a dark room, surrounded by engineering tools.',
    iconPath: 'icons/PROFESSIONS#31#terraforming_engineer.png',
  },
  {
    title: 'Xenobiologist',
    industry: 'Science',
    economicTier: 3,
    statAffinity: { intelligence: 1.5, wisdom: 1.3 },
    sentiments: ['passionate', 'proud', 'indifferent', 'quietly satisfied'],
    iconPrompt: 'A xenobiologist in a dark room, surrounded by biological samples.',
    iconPath: 'icons/PROFESSIONS#32#xenobiologist.png',
  },
  {
    title: 'Deep-Space Scout',
    industry: 'Exploration',
    economicTier: 3,
    statAffinity: { constitution: 1.3, wisdom: 1.2, dexterity: 1.1 },
    sentiments: ['passionate', 'proud', 'indifferent', 'burned out'],
    iconPrompt: 'A deep-space scout in a dark room, surrounded by exploration tools.',
    iconPath: 'icons/PROFESSIONS#33#deep_space_scout.png',
  },
  {
    title: 'Colonist',
    industry: 'Settlement',
    economicTier: 2,
    statAffinity: { constitution: 1.3, strength: 1.2, wisdom: 1.1 },
    sentiments: ['proud', 'desperate', 'quietly satisfied', 'resentful'],
    iconPrompt: 'A colonist in a dark room, surrounded by settlement tools.',
    iconPath: 'icons/PROFESSIONS#34#colonist.png',
  },
  {
    title: 'Salvager',
    industry: 'Salvage',
    economicTier: 2,
    statAffinity: { dexterity: 1.3, wisdom: 1.2, constitution: 1.1 },
    sentiments: ['indifferent', 'quietly satisfied', 'desperate', 'proud'],
    iconPrompt: 'A salvager in a dark room, surrounded by salvaged items.',
    iconPath: 'icons/PROFESSIONS#35#salvager.png',
  },

  // ── ARTS ──────────────────────────────────────────────────────────────────
  {
    title: 'Netspace Artist',
    industry: 'Creative',
    economicTier: 2,
    statAffinity: { intelligence: 1.3, charisma: 1.3 },
    sentiments: ['passionate', 'desperate', 'burned out', 'quietly satisfied'],
    iconPrompt: 'A netspace artist in a dark room, surrounded by digital art.',
    iconPath: 'icons/PROFESSIONS#36#netspace_artist.png',
  },
  {
    title: 'Underground Journalist',
    industry: 'Media',
    economicTier: 2,
    statAffinity: { intelligence: 1.3, charisma: 1.2, wisdom: 1.2 },
    sentiments: ['passionate', 'resentful', 'burned out', 'proud'],
    iconPrompt: 'An underground journalist in a dark room, surrounded by documents.',
    iconPath: 'icons/PROFESSIONS#37#underground_journalist.png',
  },

  // ── ELITE ─────────────────────────────────────────────────────────────────
  {
    title: 'Megacorp Executive',
    industry: 'Corporate',
    economicTier: 5,
    statAffinity: { charisma: 1.4, intelligence: 1.3, wisdom: 1.2 },
    sentiments: ['proud', 'indifferent', 'quietly satisfied', 'burned out'],
    iconPrompt: 'A megacorp executive in a dark room, surrounded by corporate documents.',
    iconPath: 'icons/PROFESSIONS#38#megacorp_executive.png',
  },
  {
    title: 'AI Architect',
    industry: 'Technology',
    economicTier: 5,
    statAffinity: { intelligence: 1.6, wisdom: 1.2 },
    sentiments: ['passionate', 'proud', 'indifferent', 'quietly satisfied'],
    iconPrompt: 'An AI architect in a dark room, surrounded by AI components.',
    iconPath: 'icons/PROFESSIONS#39#ai_architect.png',
  },
  {
    title: 'Orbital Mogul',
    industry: 'Corporate',
    economicTier: 5,
    statAffinity: { charisma: 1.5, intelligence: 1.3 },
    sentiments: ['proud', 'indifferent', 'quietly satisfied'],
    iconPrompt: 'An orbital mogul in a dark room, surrounded by orbital structures.',
    iconPath: 'icons/PROFESSIONS#40#orbital_mogul.png',
  },
];
