// genres/nihongi/life-events.js
// Formative events in the Nihon Shoki world.

export const LIFE_EVENTS = [
  {
    id: 'compound_fire',
    label: 'Survived a great fire that took the family compound',
    toneTag: 'trauma',
    statAffinity: { constitution: 1.2, wisdom: 1.1 },
    iconPrompt: 'ancient japanese compound fire thatched roof burning night family fleeing loss rebuild nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#compound_fire.png',
  },
  {
    id: 'witnessed_lord_death',
    label: 'Was present at the death of a great clan lord',
    toneTag: 'formative',
    statAffinity: { wisdom: 1.3, charisma: 1.1 },
    iconPrompt: 'ancient japanese great clan lord death bedside retainer mourning compound nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#witnessed_lord_death.png',
  },
  {
    id: 'diplomatic_mission',
    label: 'Traveled to Baekje, Silla, or Tang China as part of a diplomatic mission',
    toneTag: 'transformative',
    statAffinity: { intelligence: 1.3, charisma: 1.2 },
    iconPrompt: 'ancient japanese diplomatic mission ship sea voyage baekje continental journey cultural exchange nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#diplomatic_mission.png',
  },
  {
    id: 'survived_purge',
    label: 'Their clan\'s faction lost a court power struggle — survived the purge',
    toneTag: 'survival',
    statAffinity: { wisdom: 1.3, dexterity: 1.2 },
    iconPrompt: 'ancient japanese survived clan purge political loss hiding escape court fall from grace nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#survived_purge.png',
  },
  {
    id: 'imperial_audience',
    label: 'Received a direct personal audience with the emperor',
    toneTag: 'prestigious',
    statAffinity: { charisma: 1.3, wisdom: 1.2 },
    iconPrompt: 'ancient japanese imperial audience throne room prostrating reverence asuka court emperor divine nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#imperial_audience.png',
  },
  {
    id: 'buddhist_arrival',
    label: 'Was present when Buddhist scriptures and images first arrived in their region',
    toneTag: 'transformative',
    statAffinity: { wisdom: 1.3, intelligence: 1.2 },
    iconPrompt: 'ancient japanese buddhist scriptures arriving monks baekje temple founding asuka period new faith nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#buddhist_arrival.png',
  },
  {
    id: 'great_shrine_built',
    label: 'Participated in the building of a great shrine or the first temple in a province',
    toneTag: 'communal',
    statAffinity: { constitution: 1.2, wisdom: 1.2 },
    iconPrompt: 'ancient japanese shrine temple construction communal ritual sacred building hinoki cypress forest nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#great_shrine_built.png',
  },
  {
    id: 'survived_flood',
    label: 'Survived a major flood or typhoon that reshaped their region',
    toneTag: 'trauma',
    statAffinity: { constitution: 1.3, wisdom: 1.1 },
    iconPrompt: 'ancient japanese flood typhoon disaster village survival rebuilding after catastrophe nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#survived_flood.png',
  },
  {
    id: 'taken_as_hostage',
    label: 'Was held at the imperial court or a great clan compound as a peace hostage',
    toneTag: 'formative',
    statAffinity: { wisdom: 1.2, charisma: 1.2 },
    iconPrompt: 'ancient japanese clan hostage held imperial court child alone far from home political guarantee asuka period nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#taken_as_hostage.png',
  },
  {
    id: 'continental_training',
    label: 'Trained under a continental scholar or Buddhist monk for several years',
    toneTag: 'transformative',
    statAffinity: { intelligence: 1.4, wisdom: 1.2 },
    iconPrompt: 'ancient japanese student continental scholar monk teaching chinese characters medicine astronomy asuka period nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#continental_training.png',
  },
  {
    id: 'survived_clan_war',
    label: 'Fought in an inter-clan military conflict and survived',
    toneTag: 'trauma',
    statAffinity: { strength: 1.2, constitution: 1.3 },
    iconPrompt: 'ancient japanese inter-clan war battle survivors aftermath provincial nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#survived_clan_war.png',
  },
  {
    id: 'great_ritual',
    label: 'Participated in a grand national Shinto ceremony at the imperial court',
    toneTag: 'prestigious',
    statAffinity: { wisdom: 1.3, charisma: 1.2 },
    iconPrompt: 'ancient japanese grand national shinto ceremony court ritual imperial participation sacred offering nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#great_ritual.png',
  },
  {
    id: 'kami_oracle',
    label: 'Received a direct oracle from a kami through a spirit medium — and the message was unambiguous',
    toneTag: 'transformative',
    statAffinity: { wisdom: 1.4, charisma: 1.1 },
    iconPrompt: 'ancient japanese kami oracle spirit medium miko possessed divine message sacred terrifying nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/LIFE_EVENTS#kami_oracle.png',
  },
];
