// genres/nihongi/professions.js
// Professions in ancient Yamato Japan (Nihon Shoki era).
// industry values must match TAG_POOLS.professionTags keys in settings.js.

export const PROFESSIONS = [
  // ── COURT SERVICE ──────────────────────────────────────────────────────────
  {
    id: 'court_scribe',
    title: 'Court Scribe',
    industry: 'Court Service',
    economicTier: 4,
    nsfw: false,
    statAffinity: { intelligence: 1.4, wisdom: 1.2 },
    sentiments: ['methodical', 'careful', 'status-conscious'],
    iconPrompt: 'ancient japanese court scribe writing brush ink silk robes asuka palace imperial decree careful literate nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#court_scribe.png',
  },
  {
    id: 'palace_steward',
    title: 'Palace Steward',
    industry: 'Court Service',
    economicTier: 4,
    nsfw: false,
    statAffinity: { charisma: 1.3, wisdom: 1.3 },
    sentiments: ['pragmatic', 'observant', 'discreet'],
    iconPrompt: 'ancient japanese palace steward managing household imperial compound directing servants logistics silk robes asuka period nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#palace_steward.png',
  },
  {
    id: 'court_diviner',
    title: 'Court Diviner',
    industry: 'Court Service',
    economicTier: 4,
    nsfw: false,
    statAffinity: { wisdom: 1.5, intelligence: 1.2 },
    sentiments: ['cryptic', 'observant', 'ritually precise'],
    iconPrompt: 'ancient japanese court diviner tortoiseshell reading omen ritual ceremonial robes asuka court prediction nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#court_diviner.png',
  },
  {
    id: 'provincial_aide',
    title: 'Provincial Governor\'s Aide',
    industry: 'Court Service',
    economicTier: 3,
    nsfw: false,
    statAffinity: { charisma: 1.2, intelligence: 1.2 },
    sentiments: ['dutiful', 'politically aware', 'quietly ambitious'],
    iconPrompt: 'ancient japanese provincial aide official implementing edicts provincial compound away from capital practical nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#provincial_aide.png',
  },

  // ── MILITARY ───────────────────────────────────────────────────────────────
  {
    id: 'imperial_guard',
    title: 'Imperial Guard',
    industry: 'Military',
    economicTier: 4,
    nsfw: false,
    statAffinity: { strength: 1.4, constitution: 1.3 },
    sentiments: ['loyal', 'alert', 'clan-proud'],
    iconPrompt: 'ancient japanese imperial guard asuka palace protective armor weapon ceremonial formal loyal nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#imperial_guard.png',
  },
  {
    id: 'clan_warrior',
    title: 'Clan Warrior',
    industry: 'Military',
    economicTier: 3,
    nsfw: false,
    statAffinity: { strength: 1.4, dexterity: 1.2 },
    sentiments: ['loyal', 'direct', 'proud of lineage'],
    iconPrompt: 'ancient japanese clan warrior hereditary military retainer armor sword bow provincial nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#clan_warrior.png',
  },
  {
    id: 'fortress_soldier',
    title: 'Fortress Soldier',
    industry: 'Military',
    economicTier: 2,
    nsfw: false,
    statAffinity: { constitution: 1.3, strength: 1.3 },
    sentiments: ['stoic', 'bored', 'homesick'],
    iconPrompt: 'ancient japanese fortress garrison soldier watchpost provincial border duty spear rough gear nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#fortress_soldier.png',
  },

  // ── RELIGION ───────────────────────────────────────────────────────────────
  {
    id: 'buddhist_monk',
    title: 'Buddhist Monk',
    industry: 'Religion',
    economicTier: 3,
    nsfw: false,
    statAffinity: { wisdom: 1.5, intelligence: 1.3 },
    sentiments: ['contemplative', 'learned', 'diplomatically positioned'],
    iconPrompt: 'ancient japanese buddhist monk newly arrived continental faith robes scriptures asuka period temple incense nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#buddhist_monk.png',
  },
  {
    id: 'kami_priest',
    title: 'Kami Priest',
    industry: 'Religion',
    economicTier: 3,
    nsfw: false,
    statAffinity: { wisdom: 1.4, charisma: 1.2 },
    sentiments: ['traditional', 'proud', 'wary of the continental newcomers'],
    iconPrompt: 'ancient japanese kami shrine priest hereditary custodian ritual ceremony white robes sacred forest nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#kami_priest.png',
  },
  {
    id: 'miko',
    title: 'Miko (Shrine Maiden / Spirit Medium)',
    industry: 'Religion',
    allowedGenders: ['woman', 'trans_woman'],
    economicTier: 3,
    nsfw: false,
    statAffinity: { charisma: 1.3, wisdom: 1.4 },
    sentiments: ['receptive', 'otherworldly', 'practically capable'],
    iconPrompt: 'ancient japanese miko shrine maiden spirit medium ritual dance white red robes sacred forest oracle nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#miko.png',
  },
  {
    id: 'onmyoji',
    title: 'Onmyōji (Yin-Yang Diviner)',
    industry: 'Religion',
    economicTier: 4,
    nsfw: false,
    statAffinity: { intelligence: 1.5, wisdom: 1.3 },
    sentiments: ['precise', 'continental-trained', 'politically useful to whoever needs an omen explained'],
    iconPrompt: 'ancient japanese onmyoji yin yang diviner continental cosmology calendar astronomical calculation court asuka period nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#onmyoji.png',
  },

  // ── SCHOLARSHIP ────────────────────────────────────────────────────────────
  {
    id: 'court_physician',
    title: 'Court Physician (from Baekje)',
    industry: 'Scholarship',
    economicTier: 3,
    nsfw: false,
    statAffinity: { intelligence: 1.5, wisdom: 1.2 },
    sentiments: ['analytical', 'foreign-trained', 'navigating cultural difference daily'],
    iconPrompt: 'ancient japanese court physician baekje continental medicine herbs diagnosis asuka court newcomer learning nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#court_physician.png',
  },
  {
    id: 'astronomer_scribe',
    title: 'Astronomer-Scribe',
    industry: 'Scholarship',
    economicTier: 4,
    nsfw: false,
    statAffinity: { intelligence: 1.5, wisdom: 1.3 },
    sentiments: ['methodical', 'celestially minded', 'keeper of the official calendar'],
    iconPrompt: 'ancient japanese astronomer scribe celestial observation records calendar omen stars court asuka period nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#astronomer_scribe.png',
  },

  // ── CRAFT ──────────────────────────────────────────────────────────────────
  {
    id: 'master_potter',
    title: 'Master Potter',
    industry: 'Craft',
    economicTier: 3,
    nsfw: false,
    statAffinity: { dexterity: 1.4, intelligence: 1.2 },
    sentiments: ['patient', 'proud of lineage skill', 'reads social weather through their clients'],
    iconPrompt: 'ancient japanese master potter fine ceramics court ritual vessel continental technique craft guild nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#master_potter.png',
  },
  {
    id: 'silk_weaver',
    title: 'Silk Weaver',
    industry: 'Craft',
    economicTier: 3,
    nsfw: false,
    statAffinity: { dexterity: 1.4, wisdom: 1.2 },
    sentiments: ['methodical', 'understated', 'the fabric they make is more valued than they are'],
    iconPrompt: 'ancient japanese silk weaver loom continental technique craft guild prestige cloth production nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#silk_weaver.png',
  },
  {
    id: 'forge_master',
    title: 'Forge Master',
    industry: 'Craft',
    economicTier: 3,
    nsfw: false,
    statAffinity: { strength: 1.3, dexterity: 1.3 },
    sentiments: ['direct', 'self-sufficient', 'valued by both court and warrior clan'],
    iconPrompt: 'ancient japanese forge master smithing iron weapons mirrors agricultural tools fire anvil craft guild nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#forge_master.png',
  },

  // ── AGRICULTURE ────────────────────────────────────────────────────────────
  {
    id: 'village_chief',
    title: 'Village Chief',
    industry: 'Agriculture',
    economicTier: 3,
    nsfw: false,
    statAffinity: { wisdom: 1.3, charisma: 1.2 },
    sentiments: ['pragmatic', 'protective of community', 'perpetually mediating'],
    iconPrompt: 'ancient japanese village chief mediating rice paddy community provincial administration mediator respected elder nihon shoki folk painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#village_chief.png',
  },
  {
    id: 'rice_farmer',
    title: 'Rice Farmer',
    industry: 'Agriculture',
    economicTier: 2,
    nsfw: false,
    statAffinity: { constitution: 1.3, strength: 1.2 },
    sentiments: ['seasonal', 'community-bound', 'pragmatic about hardship'],
    iconPrompt: 'ancient japanese rice farmer paddy field planting harvest seasonal rural tami commoner plain clothing nihon shoki folk painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#rice_farmer.png',
  },

  // ── TRADE ──────────────────────────────────────────────────────────────────
  {
    id: 'harbor_official',
    title: 'Harbor Official',
    industry: 'Trade',
    economicTier: 3,
    nsfw: false,
    statAffinity: { charisma: 1.3, intelligence: 1.2 },
    sentiments: ['alert', 'politically sensitive', 'first to know everything that arrives'],
    iconPrompt: 'ancient japanese harbor official continental ship receiving tribute diplomatic goods naniwa port asuka period nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#harbor_official.png',
  },
  {
    id: 'traveling_merchant',
    title: 'Traveling Merchant',
    industry: 'Trade',
    economicTier: 2,
    nsfw: false,
    statAffinity: { charisma: 1.3, dexterity: 1.2 },
    sentiments: ['adaptable', 'observant', 'the most current intelligence in any room'],
    iconPrompt: 'ancient japanese traveling merchant goods pack provincial roads moving between markets ancient japan nihon shoki folk painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#traveling_merchant.png',
  },

  // ── PERFORMANCE ────────────────────────────────────────────────────────────
  {
    id: 'court_entertainer',
    title: 'Court Entertainer (Unebi)',
    industry: 'Performance',
    economicTier: 3,
    nsfw: true,
    statAffinity: { charisma: 1.5, dexterity: 1.3 },
    sentiments: ['graceful', 'perceptive', 'navigates power through aesthetics'],
    iconPrompt: 'ancient japanese court entertainer unebi music dance elegant silk robes banquet clan lord patron intimate performance nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/PROFESSIONS#court_entertainer.png',
  },
];
