// genres/nihongi/tensions.js
// Active pressures on a Nihon Shoki character.

export const TENSIONS = [
  {
    id: 'ritual_pollution',
    description: 'A powerful official has declared them ritually impure (kegare) — they must undergo public cleansing or lose their position',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'ancient japanese ritual pollution kegare accusation court shame cleansing ceremony public crisis nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#ritual_pollution.png',
  },
  {
    id: 'impossible_mission',
    description: 'Their clan lord has assigned them a mission that is either impossible or certain to create powerful enemies',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'ancient japanese clan lord command difficult mission impossible retainer bound by duty no good option nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#impossible_mission.png',
  },
  {
    id: 'clan_absorption',
    description: 'A great clan has begun the process of absorbing their family\'s lands and loyalties into their own structure',
    toneTag: 'gritty',
    criminalFlag: false,
    iconPrompt: 'ancient japanese powerful clan absorbing smaller family pressure obligation resistance surrender provincial nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#clan_absorption.png',
  },
  {
    id: 'forbidden_text',
    description: 'They carry continental documents — a letter, a copied sutra, a medical text — that the old kami-priest faction wants destroyed',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'ancient japanese forbidden continental text scroll hidden danger kami priest faction threat literacy nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#forbidden_text.png',
  },
  {
    id: 'false_genealogy_planted',
    description: 'Someone has doctored the official clan records to undercut their lineage claim — and the forgery is convincing',
    toneTag: 'gritty',
    criminalFlag: false,
    iconPrompt: 'ancient japanese clan record falsified genealogy document forgery identity undermined accusation nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#false_genealogy_planted.png',
  },
  {
    id: 'kami_wrath',
    description: 'Omens are accumulating — floods, sick livestock, a shrine oracle — that suggest a kami is specifically displeased with something they have done',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'ancient japanese kami divine wrath omens flood sick livestock shrine warning ritual appeasement nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#kami_wrath.png',
  },
  {
    id: 'purge_knowledge',
    description: 'They know the timing and targets of an upcoming political purge — and must choose between warning, silence, and using the knowledge',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'ancient japanese court purge knowledge danger choosing sides silence warning political survival nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#purge_knowledge.png',
  },
  {
    id: 'buddhist_secrecy',
    description: 'They practise Buddhism privately while officially serving a kami shrine — the two factions are moving toward open conflict',
    toneTag: 'gritty',
    criminalFlag: false,
    iconPrompt: 'ancient japanese secret buddhist practice hidden sutra shrine duty dual faith kami buddhist conflict nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#buddhist_secrecy.png',
  },
  {
    id: 'foreign_arrival',
    description: 'A continental ship has arrived carrying something — a person, a document, a relic — that multiple powerful factions want controlled',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'ancient japanese foreign ship continental arrival competing factions dangerous cargo monk relic document nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#foreign_arrival.png',
  },
  {
    id: 'succession_crisis',
    description: 'The clan lord is dying and two potential successors have already begun positioning — the character\'s position forces them to choose',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'ancient japanese clan succession dying lord rival heirs pressure choose sides court politics nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#succession_crisis.png',
  },
  {
    id: 'imperial_spy',
    description: 'A court official has asked them to report on a clan they owe personal loyalty — and has made clear this is not optional',
    toneTag: 'criminal',
    criminalFlag: true,
    iconPrompt: 'ancient japanese court spy coerced informant reporting clan lord loyalty conflict imperial pressure nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#imperial_spy.png',
  },
  {
    id: 'dire_prophecy',
    description: 'A shrine medium has named something terrible involving someone close to them — and the oracle has not been wrong in living memory',
    toneTag: 'gritty',
    criminalFlag: false,
    iconPrompt: 'ancient japanese shrine oracle prophecy dire miko spirit medium foretelling someone close dread nihon shoki yamato-e painting',
    iconPath: 'generator/genres/nihongi/icons/TENSIONS#dire_prophecy.png',
  },
];
