// ── HAIR ─────────────────────────────────────────────────────────────────
export const HAIR = [
  { id: 'auburn_braided', label: 'auburn, braided' },
  { id: 'bald', label: 'bald' },
  { id: 'black_close_cropped', label: 'black, close-cropped' },
  { id: 'black_long_straight', label: 'black, long and straight' },
  { id: 'black_medusa', label: 'black, Medusa hair that moves on its own, almost alive' },
  { id: 'black_medium_greased', label: 'black, medium-length, greased and slicked back' },
  { id: 'black_swept_one_side', label: 'black, swept to one side' },
  { id: 'black_braided', label: 'black, braided' },
  { id: 'black_voluminous', label: 'black, voluminous' },
  { id: 'black_shaved_undercut', label: 'black, with a shaved undercut' },
  { id: 'black_streaks_neon_blue', label: 'black, with streaks of neon blue' },
  { id: 'black_bobcut', label: 'black, bobcut' },
  { id: 'black_short_spiky', label: 'black, short and spiky' },
  { id: 'blonde_long_loose', label: 'blonde, long and loose' },
  { id: 'blonde_shoulder_length', label: 'blonde, shoulder-length' },
  { id: 'blonde_short_spiky', label: 'blonde, short and spiky' },
  { id: 'blonde_pixie_cut', label: 'blonde, pixie cut' },
  { id: 'blue_neon_dyed', label: 'blue, short, neon-dyed' },
  { id: 'brown_dreadlocks', label: 'brown, dreadlocks' },
  { id: 'brown_pulled_back', label: 'brown, pulled back' },
  { id: 'brown_shoulder_length', label: 'brown, shoulder-length' },
  { id: 'brown_short_spiky', label: 'brown, short and spiky' },
  { id: 'brown_wild_unkempt', label: 'brown, wild and unkempt' },
  { id: 'chestnut_gorgeous_flowing_locks', label: 'chestnut, gorgeous flowing locks' },
  { id: 'gray_ponytail', label: 'gray ponytail' },
  { id: 'gray_buzzed_short', label: 'gray, buzzed short' },
  { id: 'green_mohawk', label: 'green, mohawk' },
  { id: 'multicolored_neon_colors', label: 'multicolored, dyed in neon colors' },
  { id: 'platinum_impeccably_styled', label: 'platinum, impeccably styled' },
  { id: 'purple_bobcut', label: 'purple, bobcut' },
  { id: 'red_barely_maintained', label: 'red, barely maintained' },
  { id: 'shaved_stubble', label: 'shaved stubble' },
  { id: 'silver_shaved_one_side', label: 'silver, shaved on one side' },
  { id: 'short_dark', label: 'short dark hair' },
  { id: 'short_light', label: 'short light hair' },
  { id: 'close_cropped', label: 'close-cropped or shaved' },
  { id: 'medium_wavy', label: 'medium-length, wavy' },
  { id: 'long_straight', label: 'long, straight' },
  { id: 'long_curly', label: 'long, curly or coily' },
  { id: 'natural_coily', label: 'natural coils or locs' },
  { id: 'gray_streaked', label: 'going gray, not hiding it' },
  { id: 'dyed', label: 'dyed an unnatural color' },
  { id: 'messy', label: 'perpetually messy' },
  { id: 'pulled_back', label: 'always pulled back' },
  { id: 'thinning', label: 'thinning or receding' },
];
