// genres/fantasy/tensions.js

export const TENSIONS = [
  // ── DEBTS & OBLIGATIONS ───────────────────────────────────────────────────
  {
    id: 'debt_to_guild',
    description: 'Owes a significant debt to a guild or criminal organization — the clock is ticking',
    toneTag: 'dramatic',
    criminalFlag: true,
    iconPrompt: 'Fantasy RPG icon. A cloaked figure signing a contract by candlelight, a guild seal stamped in wax on the parchment, armed silhouettes looming in the shadows behind them.',
    iconPath: 'fantasy/icons/TENSION#debt_to_guild.png',
  },
  {
    id: 'owed_service',
    description: 'Is bound by oath or contract to perform a service they\'ve been avoiding',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A warrior standing before a glowing magical scroll bound with chains of light, an hourglass casting a long shadow across the stone floor.',
    iconPath: 'fantasy/icons/TENSION#owed_service.png',
  },
  {
    id: 'price_on_head',
    description: 'Has a bounty on their head in at least one territory — for reasons that are complicated',
    toneTag: 'gritty',
    criminalFlag: true,
    iconPrompt: 'Fantasy RPG icon. A wanted poster nailed to a tavern wall, a hooded figure\'s face sketched on it, torchlight flickering, armored bounty hunters reading it in the background.',
    iconPath: 'fantasy/icons/TENSION#price_on_head.png',
  },
  {
    id: 'magic_debt',
    description: 'Owes a debt to something supernatural — a spirit, a deity, or something harder to name',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A lone figure kneeling before a vast spectral entity of light and shadow, magical binding runes etched in a circle on the ground between them, otherworldly glow.',
    iconPath: 'fantasy/icons/TENSION#magic_debt.png',
  },

  // ── PURSUIT & DANGER ──────────────────────────────────────────────────────
  {
    id: 'being_hunted',
    description: 'Is being hunted by someone with the resources to actually find them',
    toneTag: 'gritty',
    criminalFlag: true,
    iconPrompt: 'Fantasy RPG icon. A cloaked figure sprinting through a dark forest, armored hunters with torches and hounds visible through the trees behind them, closing the gap.',
    iconPath: 'fantasy/icons/TENSION#being_hunted.png',
  },
  {
    id: 'prophecy_attached',
    description: 'Has had a prophecy attached to their name — and is not sure if they believe it, but others do',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A glowing crystal orb showing a vision of a distant figure, an ancient parchment unfurled beside it, a robed seer pointing at a lone traveler with reverence and fear.',
    iconPath: 'fantasy/icons/TENSION#prophecy_attached.png',
  },
  {
    id: 'cursed_item',
    description: 'Is in possession of something powerful and cursed that they cannot simply put down',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A gauntleted hand clutching a pulsing dark artifact, tendrils of black shadow curling up the arm, an ominous purple glow, the figure unable to release their grip.',
    iconPath: 'fantasy/icons/TENSION#cursed_item.png',
  },
  {
    id: 'old_enemy_resurfaces',
    description: 'An enemy from their past has resurfaced — better resourced and angrier than before',
    toneTag: 'gritty',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. Two armored figures facing each other across a ruined battlefield, recognition and cold fury in their stances, swords drawn, a history of violence between them implied.',
    iconPath: 'fantasy/icons/TENSION#old_enemy_resurfaces.png',
  },
  {
    id: 'witness_to_conspiracy',
    description: 'Witnessed something they weren\'t supposed to see — the people involved have noticed',
    toneTag: 'gritty',
    criminalFlag: true,
    iconPrompt: 'Fantasy RPG icon. A figure pressing against a stone wall, peering through a cracked doorway at robed conspirators gathered around a glowing map, one conspirator looking back with suspicion.',
    iconPath: 'fantasy/icons/TENSION#witness_to_conspiracy.png',
  },

  // ── DUTY & LOYALTY ────────────────────────────────────────────────────────
  {
    id: 'lord_demands_it',
    description: 'Their lord, patron, or employer has issued a command they are not comfortable carrying out',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A noble lord on a high throne extending a sealed decree toward a kneeling knight, the knight\'s expression conflicted and reluctant, a grand castle hall behind them.',
    iconPath: 'fantasy/icons/TENSION#lord_demands_it.png',
  },
  {
    id: 'protect_someone',
    description: 'Responsible for protecting someone who makes that job as difficult as possible',
    toneTag: 'neutral',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A weary guardian with sword drawn standing protectively in front of a reckless charge who is leaning eagerly toward danger, exasperation evident on the guardian\'s face.',
    iconPath: 'fantasy/icons/TENSION#protect_someone.png',
  },
  {
    id: 'conflicting_oaths',
    description: 'Has made oaths to two parties whose interests are now directly in conflict',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A figure standing between two opposing faction banners, arms outstretched toward each, a glowing oath-mark on each palm, torn expression on their face.',
    iconPath: 'fantasy/icons/TENSION#conflicting_oaths.png',  
  },
  {
    id: 'last_of_something',
    description: 'Is the last known member of an order, bloodline, or tradition — and that means something dangerous',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A lone figure standing in a crumbling hall bearing an ancient crest, dozens of extinguished candles surrounding a single flame still burning, the weight of extinction on their shoulders.',
    iconPath: 'fantasy/icons/TENSION#last_of_something.png',
  },

  // ── POWER & AMBITION ──────────────────────────────────────────────────────
  {
    id: 'power_growing',
    description: 'Their power is growing faster than their control — and they haven\'t told anyone',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A mage\'s hands crackling with wild uncontrolled energy, arcs of arcane lightning radiating outward, fear on their face as the power exceeds their will, companions nearby unaware.',
    iconPath: 'fantasy/icons/TENSION#power_growing.png',
  },
  {
    id: 'something_wants_them',
    description: 'Something magical or divine is taking an interest in them — the attention is not comfortable',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A vast divine eye of burning light descending from stormclouds, its gaze fixed on a single small figure below who looks up with unease, all other figures oblivious.',
    iconPath: 'fantasy/icons/TENSION#something_wants_them.png',
  },
  {
    id: 'rival_ahead',
    description: 'A rival is close to achieving something that would be very bad for everyone — including them',
    toneTag: 'neutral',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. Two figures racing down a dungeon corridor toward a glowing artifact at the far end, the rival nearly there, the hero behind and losing ground.',
    iconPath: 'fantasy/icons/TENSION#rival_ahead.png',
  },
  {
    id: 'political_pawn',
    description: 'Has been caught between two powerful factions who both want to use them',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A figure standing on a giant chessboard between two rival rulers extending their hands, the figure a pawn between two kings, unable to choose a side.',
    iconPath: 'fantasy/icons/TENSION#political_pawn.png',
  },

  // ── PERSONAL ─────────────────────────────────────────────────────────────
  {
    id: 'searching_for_someone',
    description: 'Is searching for someone who disappeared — or was taken — and the trail is finally warm',
    toneTag: 'neutral',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A traveler crouching over a trail of faint glowing footprints on a misty forest path, clutching a worn locket with a portrait inside, urgency in their posture.',
    iconPath: 'fantasy/icons/TENSION#searching_for_someone.png',
  },
  {
    id: 'past_catches_up',
    description: 'Something from their past is catching up — a choice, a crime, a person, a promise',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A figure walking forward as ghostly hands and shadowy memories reach out from behind them, nearly grasping their cloak, a road they thought they had left far behind.',
    iconPath: 'fantasy/icons/TENSION#past_catches_up.png',
  },
  {
    id: 'health_or_curse',
    description: 'Something is wrong with them — a wound, a curse, a corruption — and they haven\'t told their companions',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A warrior pressing a hand over a wound that pulses with dark corruption, quickly pulling their cloak shut as companions approach, concealing the spreading mark.',
    iconPath: 'fantasy/icons/TENSION#health_or_curse.png',
  },
  {
    id: 'running_out_of_time',
    description: 'Is working against a deadline they haven\'t told anyone about — something will happen if they don\'t act',
    toneTag: 'dramatic',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. An enormous cracked hourglass with the last grains of sand falling, a lone figure sprinting desperately across a fantasy landscape beneath it, no one else aware.',
    iconPath: 'fantasy/icons/TENSION#running_out_of_time.png',
  },

  // ── GRITTY ────────────────────────────────────────────────────────────────
  {
    id: 'job_gone_wrong',
    description: 'A job went sideways — someone died who wasn\'t supposed to, and the fallout is still arriving',
    toneTag: 'gritty',
    criminalFlag: true,
    iconPrompt: 'Fantasy RPG icon. A rogue standing in a ruined room amid overturned furniture and a body covered by cloth, one bloodied hand at their side, the weight of an unintended outcome on their face.',
    iconPath: 'fantasy/icons/TENSION#job_gone_wrong.png',
  },
  {
    id: 'forced_to_work_with_enemy',
    description: 'Has been forced to work alongside someone they deeply distrust — or outright hate',
    toneTag: 'gritty',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. Two armed figures standing back to back in a dark dungeon corridor, visibly tense and bristling, forced into cooperation by the danger surrounding them on all sides.',
    iconPath: 'fantasy/icons/TENSION#forced_to_work_with_enemy.png',
  },
  {
    id: 'broke_and_desperate',
    description: 'Flat broke in a city that rewards wealth and punishes poverty, with skills and no coin',
    toneTag: 'gritty',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A down-on-their-luck adventurer counting the last few copper coins in their palm, a wealthy merchant city glittering behind them, eyes scanning for an opportunity.',
    iconPath: 'fantasy/icons/TENSION#broke_and_desperate.png',
  },

  // ── COZY / LIGHT ─────────────────────────────────────────────────────────
  {
    id: 'reluctant_hero',
    description: 'Keeps being asked to solve problems they didn\'t cause and didn\'t volunteer for',
    toneTag: 'cozy',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. An ordinary villager being tugged by the sleeves toward a distant problem by a hopeful crowd, arms crossed and resistant, clearly not having volunteered for any of this.',
    iconPath: 'fantasy/icons/TENSION#reluctant_hero.png',
  },
  {
    id: 'first_adventure',
    description: 'Has landed in their first real adventure — considerably more dangerous than anticipated',
    toneTag: 'cozy',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A wide-eyed young adventurer holding a torch at the mouth of a dark dungeon, pack still neat and clean, looking into the unknown with excitement tipping toward dread.',
    iconPath: 'fantasy/icons/TENSION#first_adventure.png',
  },
  {
    id: 'unlikely_alliance',
    description: 'Has formed an unlikely alliance that makes both parties uncomfortable — but it\'s working',
    toneTag: 'cozy',
    criminalFlag: false,
    iconPrompt: 'Fantasy RPG icon. A prim knight and a scruffy rogue walking side by side through a forest, both visibly uncomfortable with each other, yet moving in the same direction with undeniable effectiveness.',
    iconPath: 'fantasy/icons/TENSION#unlikely_alliance.png',
  },
];
