// genres/fantasy/professions.js
// Fantasy professions — grouped by archetype.
// Economic tiers map to fantasy wealth:
//   1 = destitute / thrall / beggar
//   2 = peasant / laborer / hedge worker
//   3 = craftsperson / soldier / journeyman
//   4 = merchant / knight / skilled mage
//   5 = noble / archmage / guild master

import { SENTIMENTS } from '../../common/sentiments.js';

export const PROFESSIONS = [

  // ── MARTIAL ───────────────────────────────────────────────────────────────
  {
    title: 'City guard',
    industry: 'Martial',
    economicTier: 3,
    statAffinity: { strength: 1.3, constitution: 1.2 },
    sentiments: ['proud', 'burned out', 'resentful', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. An armored city guard standing at a gatehouse archway, spear in hand, surveying the street below with a tired but watchful eye, the city walls looming behind them.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#city_guard.webp',
  },
  {
    title: 'Mercenary soldier',
    industry: 'Martial',
    economicTier: 3,
    statAffinity: { strength: 1.4, constitution: 1.3, dexterity: 1.1 },
    sentiments: ['indifferent', 'proud', 'burned out', 'desperate'],
    iconPrompt: 'Fantasy RPG icon. A battle-scarred mercenary in mismatched armor, a fraying company banner behind them, coin purse at their belt, appraising the next contract with professional indifference.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#mercenary_soldier.webp',
  },
  {
    title: 'Knight in service to a lord',
    industry: 'Martial',
    economicTier: 4,
    statAffinity: { strength: 1.4, charisma: 1.2, wisdom: 1.1 },
    sentiments: ['proud', 'quietly satisfied', 'burned out', 'resentful'],
    iconPrompt: 'Fantasy RPG icon. A fully armored knight kneeling before a noble lord on a dais, receiving a blessed sword, heraldic banners hanging from stone pillars in a great hall.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#knight_in_service_to_a_lord.webp',
  },
  {
    title: 'Disgraced knight',
    industry: 'Martial',
    economicTier: 2,
    statAffinity: { strength: 1.3, wisdom: 1.1 },
    sentiments: ['ashamed', 'resentful', 'desperate', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. A knight in dented, unpolished armor sitting alone at a tavern table, a tarnished heraldic emblem visible on their chest, staring into an untouched cup.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#disgraced_knight.webp',
  },
  {
    title: 'Sellsword',
    industry: 'Martial',
    economicTier: 2,
    statAffinity: { strength: 1.5, dexterity: 1.2 },
    sentiments: ['indifferent', 'proud', 'burned out'],
    iconPrompt: 'Fantasy RPG icon. A lean fighter for hire leaning against a market square wall, sword casually visible at their hip, watching passersby with calculating eyes, no allegiance to anyone.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#sellsword.webp',
  },
  {
    title: 'Bounty hunter',
    industry: 'Martial',
    economicTier: 3,
    statAffinity: { strength: 1.3, dexterity: 1.3, wisdom: 1.1 },
    sentiments: ['indifferent', 'passionate', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. A cloaked bounty hunter studying a wanted poster on a tavern wall, manacles and a chain visible at their belt, patient and methodical, already planning the route.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#bounty_hunter.webp',
  },
  {
    title: 'Arena fighter',
    industry: 'Martial',
    economicTier: 2,
    statAffinity: { strength: 1.5, constitution: 1.4 },
    sentiments: ['proud', 'desperate', 'burned out', 'resentful'],
    iconPrompt: 'Fantasy RPG icon. A gladiator standing on blood-stained sand, weapons raised, the roaring crowd of a stone colosseum surrounding them, sweat and grit on their face, surviving on skill alone.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#arena_fighter.webp',
  },
  {
    title: 'Bodyguard',
    industry: 'Martial',
    economicTier: 3,
    statAffinity: { strength: 1.3, constitution: 1.2, wisdom: 1.1 },
    sentiments: ['indifferent', 'quietly satisfied', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A broad-shouldered bodyguard standing half a step behind a wealthy patron in a crowded market, hand resting on their weapon\'s pommel, eyes scanning the crowd for threats.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#bodyguard.webp',
  },

  // ── ROGUISH ───────────────────────────────────────────────────────────────
  {
    title: 'Thief',
    industry: 'Criminal',
    economicTier: 2,
    statAffinity: { dexterity: 1.5, intelligence: 1.2 },
    sentiments: ['proud', 'desperate', 'indifferent', 'passionate'],
    iconPrompt: 'Fantasy RPG icon. A nimble thief perched on a rooftop at night, reaching through a shuttered window toward a glinting jewel inside, the moonlit city spread out below them.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#thief.webp',
  },
  {
    title: 'Fence',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { charisma: 1.3, intelligence: 1.2 },
    sentiments: ['quietly satisfied', 'indifferent', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A fence examining a stolen artifact under candlelight in a cluttered back-room shop, shelves of dubious goods on every wall, appraising the piece with a practiced and unimpressed eye.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#fence.webp',
  },
  {
    title: 'Assassin',
    industry: 'Criminal',
    economicTier: 4,
    statAffinity: { dexterity: 1.5, intelligence: 1.3, wisdom: 1.1 },
    sentiments: ['indifferent', 'quietly satisfied', 'ashamed', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A black-clad assassin poised in the shadows of a moonlit corridor, twin daggers drawn, a target visible through a doorway ahead, absolutely still and utterly lethal.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#assassin.webp',
  },
  {
    title: 'Guild thief',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { dexterity: 1.4, charisma: 1.1, intelligence: 1.2 },
    sentiments: ['proud', 'indifferent', 'passionate'],
    iconPrompt: 'Fantasy RPG icon. A guild thief in the middle of a precision vault job, lockpicks spread on the floor, a guild mark visible on their wrist, working with the calm of someone who has done this many times.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#guild_thief.webp',
  },
  {
    title: 'Con artist / grifter',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { charisma: 1.6, intelligence: 1.3 },
    sentiments: ['passionate', 'proud', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A charming grifter mid-performance at a tavern table, a crowd of marks leaning in, cards and coin spread between them, a warm smile that never quite reaches their eyes.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#con_artist_grifter.webp',
  },
  {
    title: 'Smuggler',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { dexterity: 1.3, charisma: 1.2, wisdom: 1.1 },
    sentiments: ['indifferent', 'proud', 'desperate', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. A smuggler guiding a loaded cart down a hidden forest path at night, lantern shuttered, one hand raised to halt the group while listening for patrol sounds.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#smuggler.webp',
  },
  {
    title: 'Spy / informant',
    industry: 'Criminal',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, charisma: 1.3, dexterity: 1.2 },
    sentiments: ['indifferent', 'quietly satisfied', 'ashamed'],
    iconPrompt: 'Fantasy RPG icon. A spy in aristocratic dress at a candlelit court gathering, appearing to sip wine while listening intently, a folded cipher note half-concealed in their sleeve.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#spy_informant.webp',
  },

  // ── ARCANE ────────────────────────────────────────────────────────────────
  {
    title: 'Hedge witch',
    industry: 'Arcane',
    economicTier: 2,
    statAffinity: { intelligence: 1.3, wisdom: 1.2 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent', 'resentful'],
    iconPrompt: 'Fantasy RPG icon. A weathered hedge witch in a cluttered woodland cottage, drying herbs hanging from the rafters, a worn spellbook open on the table, knowledge earned through practice not privilege.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#hedge_witch.webp',
  },
  {
    title: 'Apprentice mage',
    industry: 'Arcane',
    economicTier: 2,
    statAffinity: { intelligence: 1.5, wisdom: 1.1 },
    sentiments: ['passionate', 'desperate', 'burned out', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A young apprentice mage hunched over a towering stack of spellbooks by candlelight, a failed spell sending sparks across the study, determination refusing to become defeat.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#apprentice_mage.webp',
  },
  {
    title: 'Court wizard',
    industry: 'Arcane',
    economicTier: 4,
    statAffinity: { intelligence: 1.5, charisma: 1.2, wisdom: 1.2 },
    sentiments: ['quietly satisfied', 'burned out', 'resentful', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A court wizard in fine robes standing at the king\'s shoulder in the throne room, advising quietly, arcane instruments on a nearby table, power wielded through knowledge rather than force.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#court_wizard.webp',
  },
  {
    title: 'Battle mage',
    industry: 'Arcane',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, strength: 1.2, constitution: 1.1 },
    sentiments: ['proud', 'burned out', 'passionate'],
    iconPrompt: 'Fantasy RPG icon. A battle mage in armored robes channeling destructive energy between gauntleted hands, soldiers falling back around them on a smoky battlefield, power and discipline held in equal measure.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#battle_mage.webp',
  },
  {
    title: 'Warlock',
    industry: 'Arcane',
    economicTier: 3,
    statAffinity: { intelligence: 1.3, charisma: 1.3, wisdom: 0.9 },
    sentiments: ['proud', 'quietly satisfied', 'desperate', 'ashamed'],
    iconPrompt: 'Fantasy RPG icon. A warlock standing in a summoning circle, dark energy coiling around their outstretched hand, the faint and massive suggestion of an otherworldly patron looming in the shadows behind them.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#warlock.webp',
  },
  {
    title: 'Necromancer',
    industry: 'Arcane',
    economicTier: 3,
    statAffinity: { intelligence: 1.5, wisdom: 0.9 },
    sentiments: ['passionate', 'indifferent', 'quietly satisfied', 'ashamed'],
    iconPrompt: 'Fantasy RPG icon. A necromancer in dark robes raising skeletal forms from cracked earth, cold blue light emanating from their staff, clinical curiosity rather than malice on their face.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#necromancer.webp',
  },
  {
    title: 'Runesmith',
    industry: 'Arcane',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, dexterity: 1.3 },
    sentiments: ['passionate', 'proud', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. A runesmith etching glowing sigils into a sword blade with a fine chisel, the metal coming alive with arcane light, rune diagrams and reference scrolls spread across the workbench.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#runesmith.webp',
  },
  {
    title: 'Alchemist',
    industry: 'Arcane',
    economicTier: 3,
    statAffinity: { intelligence: 1.5, dexterity: 1.2 },
    sentiments: ['passionate', 'burned out', 'quietly satisfied', 'proud'],
    iconPrompt: 'Fantasy RPG icon. An alchemist surrounded by bubbling flasks and labeled vials in a cluttered laboratory, carefully measuring a luminous substance over a flame, the air around them faintly smoking.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#alchemist.webp',
  },
  {
    title: 'Witch hunter',
    industry: 'Arcane',
    economicTier: 3,
    statAffinity: { wisdom: 1.3, strength: 1.2, constitution: 1.1 },
    sentiments: ['proud', 'burned out', 'resentful'],
    iconPrompt: 'Fantasy RPG icon. A grim witch hunter in heavy leather armor moving through a misty village at night, silver-tipped crossbow raised, a ward-medallion around their neck, absolutely certain of their purpose.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#witch_hunter.webp',
  },

  // ── DIVINE ────────────────────────────────────────────────────────────────
  {
    title: 'Temple priest',
    industry: 'Divine',
    economicTier: 3,
    statAffinity: { wisdom: 1.4, charisma: 1.2 },
    sentiments: ['passionate', 'quietly satisfied', 'burned out', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A robed priest conducting a candlelit ritual at a stone altar, divine symbols carved into the walls behind them, the faithful gathered in the shadows, devotion in every gesture.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#temple_priest.webp',
  },
  {
    title: 'Wandering cleric',
    industry: 'Divine',
    economicTier: 2,
    statAffinity: { wisdom: 1.4, constitution: 1.2 },
    sentiments: ['passionate', 'quietly satisfied', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A cleric in travel-worn robes kneeling to tend an injured stranger at a roadside, holy symbol glowing softly at their chest, a walking staff leaning against a tree nearby.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#wandering_cleric.webp',
  },
  {
    title: 'Inquisitor',
    industry: 'Divine',
    economicTier: 4,
    statAffinity: { wisdom: 1.3, strength: 1.2, intelligence: 1.1 },
    sentiments: ['proud', 'passionate', 'quietly satisfied', 'burned out'],
    iconPrompt: 'Fantasy RPG icon. A steel-eyed inquisitor in ceremonial armor standing over a bound suspect in a stone chamber, a holy seal carved into the wall behind them, righteous and utterly certain.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#inquisitor.webp',
  },
  {
    title: 'Fallen paladin',
    industry: 'Divine',
    economicTier: 2,
    statAffinity: { strength: 1.3, wisdom: 1.2, constitution: 1.1 },
    sentiments: ['ashamed', 'resentful', 'desperate', 'quietly satisfied'],
  },
  {
    title: 'Oracle / seer',
    industry: 'Divine',
    economicTier: 3,
    statAffinity: { wisdom: 1.5, intelligence: 1.2 },
    sentiments: ['quietly satisfied', 'burned out', 'indifferent', 'passionate'],
    iconPrompt: 'Fantasy RPG icon. A veiled oracle seated before a glowing scrying pool, hands hovering over the water\'s surface, visions of distant events reflected in their clouded eyes, voice hollow and precise.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#oracle_seer.webp',
  },
  {
    title: 'Druid',
    industry: 'Divine',
    economicTier: 2,
    statAffinity: { wisdom: 1.4, constitution: 1.3 },
    sentiments: ['quietly satisfied', 'passionate', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A druid standing in an ancient stone circle at dawn, arms raised, roots and vines stirring in response, one hand resting on the bark of a vast and gnarled oak tree.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#druid.webp',
  },

  // ── SKILLED TRADES / CRAFT ────────────────────────────────────────────────
  {
    title: 'Blacksmith',
    industry: 'Craft',
    economicTier: 3,
    statAffinity: { strength: 1.4, dexterity: 1.2, constitution: 1.1 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A blacksmith at a roaring forge, hammer raised over a glowing blade on the anvil, sparks flying, strong arms and a lifetime of practiced precision in every strike.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#blacksmith.webp',
  },
  {
    title: 'Weaponsmith',
    industry: 'Craft',
    economicTier: 4,
    statAffinity: { strength: 1.3, dexterity: 1.4, intelligence: 1.1 },
    sentiments: ['passionate', 'proud', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. A weaponsmith holding a freshly finished sword up to the light, inspecting every edge with exacting care, a wall of completed blades and armaments displayed behind them.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#weaponsmith.webp',
  },
  {
    title: 'Shipwright',
    industry: 'Craft',
    economicTier: 3,
    statAffinity: { intelligence: 1.2, strength: 1.2, dexterity: 1.2 },
    sentiments: ['proud', 'quietly satisfied', 'burned out'],
    iconPrompt: 'Fantasy RPG icon. A shipwright standing atop a half-built hull in a harbor yard, blueprints in hand, directing workers below, a finished tall-masted ship waiting in the water behind them.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#shipwright.webp',
  },
  {
    title: 'Herbalist',
    industry: 'Craft',
    economicTier: 2,
    statAffinity: { wisdom: 1.3, intelligence: 1.2, dexterity: 1.1 },
    sentiments: ['quietly satisfied', 'passionate', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. An herbalist at a garden table carefully sorting and bundling dried plants, shelves of labeled tinctures and poultices behind them, healing knowledge rooted in the natural world.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#herbalist.webp',
  },
  {
    title: 'Cartographer',
    industry: 'Craft',
    economicTier: 3,
    statAffinity: { intelligence: 1.4, dexterity: 1.2, wisdom: 1.1 },
    sentiments: ['passionate', 'quietly satisfied', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A cartographer bent over a large map on a cluttered desk, quill tracing a newly discovered coastline, explorer\'s notes and specimen jars scattered across the surface, the world growing under their hand.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#cartographer.webp',
  },
  {
    title: 'Tattooist / scarifier',
    industry: 'Craft',
    economicTier: 3,
    statAffinity: { dexterity: 1.5, charisma: 1.1 },
    sentiments: ['passionate', 'quietly satisfied', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A tattooist with ink-stained fingers working an intricate pattern onto a client\'s arm, the design glowing faintly with magical resonance in the dim light of a parlor filled with art.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#tattooist_scarifier.webp',
  },

  // ── SOCIAL / SERVICE ──────────────────────────────────────────────────────
  {
    title: 'Bard',
    industry: 'Performance',
    economicTier: 2,
    statAffinity: { charisma: 1.5, dexterity: 1.2 },
    sentiments: ['passionate', 'indifferent', 'quietly satisfied', 'burned out'],
    iconPrompt: 'Fantasy RPG icon. A bard mid-performance on a tavern stage, lute in hand, a crowded room hanging on every note, mischief in their smile, a story unfolding in every pause between chords.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#bard.webp',
  },
  {
    title: 'Innkeeper',
    industry: 'Service',
    economicTier: 3,
    statAffinity: { charisma: 1.3, wisdom: 1.2, constitution: 1.1 },
    sentiments: ['quietly satisfied', 'burned out', 'proud', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A stout innkeeper behind a well-worn bar, polishing a tankard with calm authority, overseeing a full and rowdy common room with the ease of someone who has seen everything.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#innkeeper.webp',
  },
  {
    title: 'Merchant',
    industry: 'Trade',
    economicTier: 4,
    statAffinity: { charisma: 1.4, intelligence: 1.3 },
    sentiments: ['proud', 'quietly satisfied', 'passionate', 'burned out'],
    iconPrompt: 'Fantasy RPG icon. A prosperous merchant at a market stall reviewing trade documents with a partner, scales and coin on the table between them, a loaded caravan waiting in the street behind.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#merchant.webp',
  },
  {
    title: 'Ship captain',
    industry: 'Trade',
    economicTier: 4,
    statAffinity: { charisma: 1.3, wisdom: 1.2, strength: 1.1 },
    sentiments: ['proud', 'passionate', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. A ship captain at the helm in heavy weather, coat whipping in the wind, commanding the crew with calm certainty, the sea crashing over the bow below.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#ship_captain.webp',
  },
  {
    title: 'Sailor / deckhand',
    industry: 'Trade',
    economicTier: 2,
    statAffinity: { constitution: 1.3, strength: 1.2 },
    sentiments: ['indifferent', 'proud', 'burned out', 'desperate'],
    iconPrompt: 'Fantasy RPG icon. A weathered sailor hauling rope on the deck of a tall-masted ship at sea, the deck pitching beneath their feet, wind-burned and capable, the open horizon ahead.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#sailor_deckhand.webp',
  },
  {
    title: 'Tavern keeper',
    industry: 'Service',
    economicTier: 3,
    statAffinity: { charisma: 1.2, constitution: 1.2, wisdom: 1.1 },
    sentiments: ['quietly satisfied', 'burned out', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A tavern keeper managing a rowdy night crowd with practiced efficiency, breaking up a minor argument at one table while refilling cups at another, master of their domain.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#tavern_keeper.webp',
  },
  {
    title: 'Scribe',
    industry: 'Service',
    economicTier: 3,
    statAffinity: { intelligence: 1.4, dexterity: 1.2 },
    sentiments: ['indifferent', 'quietly satisfied', 'burned out', 'passionate'],
    iconPrompt: 'Fantasy RPG icon. A scribe hunched over parchment by candlelight in a scriptorium, quill moving in careful strokes, stacks of finished documents and wax seals beside them, copying without sentiment.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#scribe.webp',
  },
  {
    title: 'Courier / messenger',
    industry: 'Service',
    economicTier: 2,
    statAffinity: { dexterity: 1.3, constitution: 1.2 },
    sentiments: ['indifferent', 'quietly satisfied', 'desperate'],
    iconPrompt: 'Fantasy RPG icon. A courier on horseback galloping hard down a road at dusk, sealed message satchel over their shoulder, urgency in every line of their posture, distance still to cover.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#courier_messenger.webp',
  },
  {
    title: 'Gravedigger',
    industry: 'Service',
    economicTier: 2,
    statAffinity: { constitution: 1.3, strength: 1.2 },
    sentiments: ['indifferent', 'quietly satisfied', 'resentful', 'ashamed'],
    iconPrompt: 'Fantasy RPG icon. A gravedigger at work in a torch-lit cemetery at night, shovel over their shoulder, an open grave behind them, matter-of-fact about the work that no one else will do.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#gravedigger.webp',
  },

  // ── NOBILITY / POWER ──────────────────────────────────────────────────────
  {
    title: 'Minor noble',
    industry: 'Nobility',
    economicTier: 4,
    statAffinity: { charisma: 1.3, intelligence: 1.2 },
    sentiments: ['proud', 'quietly satisfied', 'resentful', 'burned out'],
    iconPrompt: 'Fantasy RPG icon. A minor noble in fine but not extravagant dress standing in a modest manor hall, aware of their station but equally aware of the greater names above them in the hierarchy.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#minor_noble.webp',
  },
  {
    title: 'Disinherited noble',
    industry: 'Nobility',
    economicTier: 2,
    statAffinity: { charisma: 1.3, intelligence: 1.2 },
    sentiments: ['resentful', 'ashamed', 'desperate', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A well-dressed figure in clothes that were once finer standing outside the closed gates of an estate that is no longer theirs, pride and bitterness struggling on their face.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#disinherited_noble.webp',
  },
  {
    title: 'Royal advisor',
    industry: 'Nobility',
    economicTier: 5,
    statAffinity: { intelligence: 1.5, charisma: 1.3, wisdom: 1.2 },
    sentiments: ['quietly satisfied', 'burned out', 'proud', 'resentful'],
    iconPrompt: 'Fantasy RPG icon. A lean advisor standing at the shoulder of a throne, leaning close to whisper counsel, a scroll of intelligence in one hand, every word to the king chosen with precise intent.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#royal_advisor.webp',
  },
  {
    title: 'Spymaster',
    industry: 'Nobility',
    economicTier: 5,
    statAffinity: { intelligence: 1.5, charisma: 1.3, wisdom: 1.2 },
    sentiments: ['quietly satisfied', 'indifferent', 'proud'],
    iconPrompt: 'Fantasy RPG icon. A figure in unremarkable dress seated in a candlelit room full of maps and correspondence, a network of strings connecting locations on the wall behind them, knowing everything.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#spymaster.webp',
  },
  {
    title: 'Crime lord',
    industry: 'Criminal',
    economicTier: 5,
    statAffinity: { charisma: 1.5, intelligence: 1.4, strength: 1.1 },
    sentiments: ['proud', 'quietly satisfied', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A crime lord seated in a shadowed throne of their own making, lieutenants at each side, the city visible through the window below, owning it all without ever being seen to.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#crime_lord.webp',
  },

  // ── OUTCAST / WILDERNESS ──────────────────────────────────────────────────
  {
    title: 'Hunter / trapper',
    industry: 'Wilderness',
    economicTier: 2,
    statAffinity: { dexterity: 1.4, wisdom: 1.2, constitution: 1.1 },
    sentiments: ['quietly satisfied', 'proud', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A hunter moving silently through a dense forest, bow in hand, reading the signs in the underbrush with practiced ease, utterly at home in the wilderness.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#hunter_trapper.webp',
  },
  {
    title: 'Ranger',
    industry: 'Wilderness',
    economicTier: 3,
    statAffinity: { dexterity: 1.4, wisdom: 1.3, constitution: 1.2 },
    sentiments: ['quietly satisfied', 'indifferent', 'passionate', 'burned out'],
    iconPrompt: 'Fantasy RPG icon. A ranger crouched at a treeline, studying the landscape ahead, longbow across their back, reading the land like a map, guardian of the boundary between civilization and wild.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#ranger.webp',
  },
  {
    title: 'Monster hunter',
    industry: 'Wilderness',
    economicTier: 3,
    statAffinity: { strength: 1.3, dexterity: 1.3, wisdom: 1.2 },
    sentiments: ['passionate', 'burned out', 'proud', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A monster hunter checking silver-tipped bolts before entering a dark cave, specialized hunting kit spread on a flat rock, a monster trophy visible on their worn gear.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#monster_hunter.webp',
  },
  {
    title: 'Outlaw / bandit',
    industry: 'Criminal',
    economicTier: 2,
    statAffinity: { strength: 1.3, dexterity: 1.2, wisdom: 0.9 },
    sentiments: ['proud', 'desperate', 'resentful', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. An outlaw resting at a roadside camp in the trees, a stolen saddlebag nearby, cloth mask pulled down, watching the road below with wary and calculating eyes.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#outlaw_bandit.webp',
  },
  {
    title: 'Pirate',
    industry: 'Criminal',
    economicTier: 3,
    statAffinity: { strength: 1.3, charisma: 1.2, dexterity: 1.2 },
    sentiments: ['proud', 'passionate', 'indifferent', 'desperate'],
    iconPrompt: 'Fantasy RPG icon. A pirate at the prow of a ship, a merchant vessel closing in the distance, crew armed and ready at their back, a flag of no allegiance cracking in the wind above.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#pirate.webp',
  },
  {
    title: 'Exiled mage',
    industry: 'Arcane',
    economicTier: 1,
    statAffinity: { intelligence: 1.4, wisdom: 1.1 },
    sentiments: ['resentful', 'ashamed', 'desperate', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. A mage walking a lonely road alone, staff in hand, the city that cast them out fading on the horizon behind them, their robes stripped of every guild mark and insignia.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#exiled_mage.webp',
  },
  {
    title: 'Escaped slave',
    industry: 'Outcast',
    economicTier: 1,
    statAffinity: { constitution: 1.3, strength: 1.2 },
    sentiments: ['desperate', 'resentful', 'proud', 'quietly satisfied'],
    iconPrompt: 'Fantasy RPG icon. A figure moving fast through a dark forest at night, the broken remnant of a shackle still on one wrist, determined expression, putting as much distance as possible between themselves and what they left.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#escaped_slave.webp',
  },
  {
    title: 'Wandering monk',
    industry: 'Divine',
    economicTier: 1,
    statAffinity: { wisdom: 1.4, constitution: 1.2 },
    sentiments: ['quietly satisfied', 'passionate', 'indifferent'],
    iconPrompt: 'Fantasy RPG icon. A wandering monk on a dusty road with a simple staff, a single small pack on their back, pausing to help a stranger at the roadside, carrying nothing that cannot be carried alone.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#wandering_monk.webp',
  },
  // ── NSFW ─────────────────────────────────────────────────────────────────
  {
    title: 'Sex Worker',
    industry: 'Entertainment',
    economicTier: 2,
    nsfw: true,
    statAffinity: { charisma: 1.4, intelligence: 0.9, wisdom: 0.8 },
    sentiments: ['proud', 'indifferent', 'quietly satisfied', 'burned out'],
    iconPrompt: 'Fantasy RPG icon. A woman wearing a corset showing cleavage with a sultry smile standing outside a dimly lit tavern.',
    iconPath: 'generator/genres/fantasy/icons/PROFESSION#sex_worker.webp',
  },
];
