// genres/manga-osaka-highschool1987/names.js
// Japanese name pools keyed by school archetype (identity.broad).
// Surnames are common Japanese family names from the era.
// Given names reflect the archetype's flavor while staying period-authentic.

export const NAME_POOLS = {

  // ── YANKII ────────────────────────────────────────────────────────────────
  'Yankii': {
    masc:    ['Ryuji', 'Takeshi', 'Kunio', 'Makoto', 'Tetsuya', 'Hiroyuki', 'Masaaki', 'Noboru',
              'Kenji', 'Toshio', 'Akira', 'Junnosuke', 'Kyosuke', 'Daichi', 'Ryu',
              'Susumu', 'Katsuo', 'Gorota', 'Isamu', 'Shigeo', 'Bunta', 'Eiji', 'Fumio', 'Genzo', 'Hideki',
              'Ippei', 'Jotaro', 'Kanta', 'Manabu', 'Norio', 'Osamu', 'Ryota', 'Seiji', 'Takumi', 'Ushio',
              'Yasuo', 'Zenji', 'Atsushi', 'Botan', 'Choji', 'Denta', 'Eizo', 'Fuma', 'Genta', 'Hyoma', 'Ittetsu', 'Jinbei', 'Korin', 'Ranmaru', 'Shoji'],
    fem:     ['Junko', 'Yuki', 'Tomoe', 'Akemi', 'Kazue', 'Sachiko', 'Miyuki', 'Fumie',
              'Noriko', 'Reiko', 'Yoshiko', 'Haruko', 'Sumiko', 'Teruko', 'Kimiko',
              'Ayako', 'Chieko', 'Emiko', 'Fusae', 'Gin', 'Hisako', 'Ikuko', 'Kiyoko', 'Kikue', 'Machiko',
              'Nobuko', 'Rumiko', 'Setsuko', 'Toyoko', 'Umeko', 'Wakana', 'Yasuko', 'Chiyo', 'Etsuko', 'Fujie',
              'Harue', 'Ikue', 'Kanako', 'Masako', 'Ranko', 'Ritsuko', 'Sayuri', 'Tamae', 'Wakako', 'Yuriko', 'Airiko', 'Botan', 'Chikayo', 'Dainaka', 'Ebisu'],
    neutral: ['Kaoru', 'Nao', 'Sora', 'Tomo', 'Akira', 'Rei', 'Hikaru', 'Yuu'],
    last:    ['Tanaka', 'Yamamoto', 'Nakamura', 'Watanabe', 'Kobayashi', 'Ito', 'Kato',
              'Shimizu', 'Hayashi', 'Inoue', 'Ogawa', 'Mori', 'Maeda', 'Fujita', 'Nishida',
              'Goto', 'Okamoto', 'Kimura', 'Ueda', 'Naito',
              'Sugiyama', 'Kaneko', 'Endo', 'Aoki', 'Fukuda', 'Sakamoto', 'Yokoyama', 'Miura', 'Ando', 'Ishii',
              'Taniguchi', 'Uchida', 'Takagi', 'Nakagawa', 'Kubo', 'Matsuda', 'Harada', 'Nomura', 'Sakai', 'Kikuchi',
              'Sugawara', 'Doi', 'Onishi', 'Tsuchiya', 'Kudo', 'Yano', 'Sekine', 'Wada', 'Iwata', 'Hori'],
  },

  // ── HONOR STUDENT ─────────────────────────────────────────────────────────
  'Honor Student': {
    masc:    ['Hiroshi', 'Kenji', 'Shinichi', 'Toshiro', 'Kazuhiro', 'Masato', 'Nobuhiro',
              'Satoshi', 'Yoshiro', 'Takahiro', 'Shunsuke', 'Naoki', 'Tomohiro', 'Fumihiro', 'Koji',
              'Akihiko', 'Bunji', 'Chikara', 'Daigo', 'Etsuo', 'Gakuto', 'Hideo', 'Ikuo', 'Junpei', 'Katsura',
              'Masayuki', 'Norihiko', 'Osamu', 'Reiji', 'Susumu', 'Takanori', 'Umeo', 'Wataru', 'Yasuhiko', 'Zenta',
              'Akinori', 'Chikashi', 'Fumiya', 'Gento', 'Hidenori', 'Isao', 'Kunihiko', 'Michio', 'Nobuo', 'Tetsuo', 'Yoshinori', 'Zenichi', 'Akitake', 'Bunroku', 'Choshiro'],
    fem:     ['Yukiko', 'Michiko', 'Keiko', 'Akiko', 'Tomoko', 'Noriko', 'Yoshiko', 'Kyoko',
              'Hiroko', 'Fumiko', 'Kazuko', 'Mariko', 'Sachiko', 'Reiko', 'Naoko',
              'Chikako', 'Emiko', 'Harumi', 'Ikuko', 'Junko', 'Kaori', 'Machiko', 'Nobuko', 'Ritsuko', 'Sumiko',
              'Takako', 'Umeko', 'Wakako', 'Yasuko', 'Chieko', 'Etsuko', 'Fusako', 'Gyoko', 'Hisako', 'Kikuko',
              'Masayo', 'Norie', 'Ranko', 'Sayoko', 'Toyoko', 'Umeyo', 'Wakana', 'Yukie', 'Chizuko', 'Emiyo', 'Fujiyo', 'Gyokue', 'Hanae', 'Ikuyo', 'Junye'],
    neutral: ['Hikaru', 'Kaoru', 'Rei', 'Nao', 'Akira', 'Saki', 'Natsuki', 'Tomo'],
    last:    ['Suzuki', 'Yamada', 'Sasaki', 'Yamazaki', 'Matsumoto', 'Ikeda', 'Hashimoto',
              'Fujiwara', 'Nishimura', 'Ishikawa', 'Abe', 'Miyamoto', 'Honda', 'Hasegawa',
              'Tamura', 'Saito', 'Kawamoto', 'Nakajima', 'Yamamoto', 'Kondo',
              'Nakano', 'Fukushima', 'Ono', 'Kaneda', 'Shibata', 'Yasuda', 'Terada', 'Kojima', 'Anzai', 'Uehara',
              'Morita', 'Matsuura', 'Segawa', 'Takeda', 'Ishida', 'Kurihara', 'Sano', 'Nagata', 'Sekiguchi', 'Baba',
              'Nakayama', 'Morimoto', 'Ozawa', 'Igarashi', 'Kaji', 'Umeda', 'Wakabayashi', 'Yagi', 'Otsuka', 'Kikuchi'],
  },

  // ── SPORTS ACE ────────────────────────────────────────────────────────────
  'Sports Ace': {
    masc:    ['Ichiro', 'Kenta', 'Daisuke', 'Yusuke', 'Tatsuya', 'Kosuke', 'Ryota',
              'Shohei', 'Daiki', 'Takuya', 'Koichi', 'Masahiro', 'Tsubasa', 'Kotaro', 'Goro',
              'Akito', 'Bunta', 'Choei', 'Daigoro', 'Eisuke', 'Fumiya', 'Gaku', 'Hayato', 'Isao', 'Joji',
              'Kazuki', 'Masaru', 'Norio', 'Osamu', 'Ryuki', 'Shingo', 'Taiga', 'Uta', 'Wataru', 'Yuudai',
              'Akitoshi', 'Bunji', 'Chikatoshi', 'Daigo', 'Genki', 'Haruto', 'Ikki', 'Junya', 'Kaito', 'Manato', 'Ranmaru', 'Shungo', 'Taketo', 'Uichi', 'Yorito'],
    fem:     ['Ayumi', 'Haruka', 'Miho', 'Rie', 'Kaori', 'Yumiko', 'Madoka', 'Yoko',
              'Satsuki', 'Tomoe', 'Mika', 'Asuka', 'Natsuko', 'Chiharu', 'Kana',
              'Airi', 'Chika', 'Emika', 'Fuyumi', 'Hitomi', 'Izumi', 'Junna', 'Kotone', 'Manaka', 'Nozomi',
              'Rika', 'Sayaka', 'Tamaki', 'Ume', 'Wakaba', 'Yui', 'Chinatsu', 'Erika', 'Fuka', 'Harumi',
              'Ikumi', 'Kaede', 'Mizuki', 'Natsumi', 'Ririka', 'Sakiko', 'Tomomi', 'Wakana', 'Yumeka', 'Chihiro', 'Airika', 'Botan', 'Chisa', 'Detoko', 'Ebina'],
    neutral: ['Sora', 'Natsuki', 'Akira', 'Tomo', 'Hikaru', 'Kiri', 'Nao', 'Haruki'],
    last:    ['Tanaka', 'Yamamoto', 'Ito', 'Nakamura', 'Watanabe', 'Kato', 'Yoshida',
              'Shimizu', 'Mori', 'Hayashi', 'Okamoto', 'Maeda', 'Kimura', 'Fujita',
              'Ueda', 'Inoue', 'Tamura', 'Honda', 'Goto', 'Takahashi',
              'Yokota', 'Kaneko', 'Endo', 'Aoki', 'Fukuda', 'Sakamoto', 'Yokoyama', 'Miura', 'Ando', 'Ishii',
              'Taniguchi', 'Uchida', 'Takagi', 'Nakagawa', 'Kubo', 'Matsuda', 'Harada', 'Nomura', 'Sakai', 'Doi',
              'Sugawara', 'Onishi', 'Tsuchiya', 'Kudo', 'Yano', 'Sekine', 'Wada', 'Iwata', 'Hori', 'Sugiyama'],
  },

  // ── DRAMA KID ─────────────────────────────────────────────────────────────
  'Drama Kid': {
    masc:    ['Hikaru', 'Ryosuke', 'Shuichi', 'Taichi', 'Makoto', 'Kazuya', 'Shinya',
              'Yoji', 'Haruki', 'Seiichi', 'Ryo', 'Masaki', 'Takeshi', 'Koji', 'Isamu',
              'Akihito', 'Bunta', 'Chikara', 'Daigo', 'Eisaku', 'Fuyuki', 'Gaishi', 'Hayao', 'Ikuya', 'Junichi',
              'Kaname', 'Manabu', 'Norihito', 'Osamu', 'Reo', 'Shusaku', 'Tatsuo', 'Ushio', 'Wataru', 'Yasunari',
              'Akitsugu', 'Chiaki', 'Fumito', 'Gento', 'Haruo', 'Ichiya', 'Junro', 'Kunio', 'Michiya', 'Nozomu', 'Ranmaru', 'Shungo', 'Taketo', 'Umanosuke', 'Yoritomo'],
    fem:     ['Ayaka', 'Emi', 'Saki', 'Yuri', 'Kanako', 'Madoka', 'Nana', 'Shiori',
              'Yumiko', 'Fumiko', 'Akane', 'Chiharu', 'Ritsuko', 'Yoshimi', 'Hanako',
              'Airi', 'Chiaki', 'Emika', 'Fuyuko', 'Harune', 'Ikuyo', 'Junna', 'Kokoro', 'Manami', 'Nozomi',
              'Rina', 'Sayuri', 'Tamami', 'Umeka', 'Wakaba', 'Yuina', 'Chika', 'Erina', 'Fumika', 'Haruna',
              'Ikuko', 'Kaede', 'Mizue', 'Natsume', 'Ririko', 'Sakura', 'Tomoyo', 'Wakami', 'Yumeko', 'Chisato', 'Airina', 'Botanko', 'Chiyu', 'Dechiko', 'Emine'],
    neutral: ['Rei', 'Kaoru', 'Akira', 'Hikaru', 'Sora', 'Nao', 'Tomo', 'Yuu'],
    last:    ['Kawamoto', 'Fujiwara', 'Hashimoto', 'Nishimura', 'Sasaki', 'Yamazaki',
              'Ikeda', 'Matsumoto', 'Abe', 'Hasegawa', 'Ishikawa', 'Miyamoto', 'Kondo',
              'Nakajima', 'Saito', 'Ogawa', 'Honda', 'Tamura', 'Ueda', 'Takahashi',
              'Nakano', 'Fukushima', 'Ono', 'Kaneda', 'Shibata', 'Yasuda', 'Terada', 'Kojima', 'Anzai', 'Uehara',
              'Morita', 'Matsuura', 'Segawa', 'Takeda', 'Ishida', 'Kurihara', 'Sano', 'Nagata', 'Sekiguchi', 'Baba',
              'Nakayama', 'Morimoto', 'Ozawa', 'Igarashi', 'Kaji', 'Umeda', 'Wakabayashi', 'Yagi', 'Otsuka', 'Ando'],
  },

  // ── TRANSFER STUDENT ──────────────────────────────────────────────────────
  'Transfer Student': {
    masc:    ['Shin', 'Ryu', 'Ken', 'Hiro', 'Jun', 'Sho', 'Taro', 'Jiro', 'Saburo',
              'Kazuya', 'Naoki', 'Shota', 'Yuto', 'Kei', 'Sosuke',
              'Akito', 'Ban', 'Choru', 'Dai', 'Emu', 'Fuu', 'Gan', 'Hayo', 'Ippo', 'Joh',
              'Kyo', 'Len', 'Michi', 'Nen', 'Oto', 'Pon', 'Ren', 'Sui', 'Toma', 'Uta',
              'Wataru', 'Yamato', 'Zen', 'Airu', 'Boku', 'Chise', 'Deko', 'Etsu', 'Fumi', 'Getsu', 'Hyoichi', 'Ittoku', 'Jinta', 'Korio', 'Mareo'],
    fem:     ['Mio', 'Rin', 'Yui', 'Ai', 'Hana', 'Nao', 'Riko', 'Sae',
              'Nana', 'Yuna', 'Minami', 'Haruna', 'Koharu', 'Aoi', 'Misaki',
              'Chie', 'Emi', 'Fuu', 'Hina', 'Ito', 'Jun', 'Kokoa', 'Lira', 'Mei', 'Nozomi',
              'Ren', 'Saya', 'Toa', 'Umi', 'Waka', 'Yoru', 'Chihaya', 'Erika', 'Fumi', 'Haru',
              'Ichika', 'Kaho', 'Momoka', 'Natsu', 'Ran', 'Sora', 'Tsumugi', 'Wakaba', 'Yura', 'Chiya', 'Airahi', 'Botanka', 'Chisae', 'Detona', 'Emiru'],
    neutral: ['Sora', 'Nao', 'Kiri', 'Rei', 'Hikaru', 'Tomo', 'Natsuki', 'Akira'],
    last:    ['Yamamoto', 'Tanaka', 'Suzuki', 'Ito', 'Watanabe', 'Kato', 'Nakamura',
              'Kobayashi', 'Yoshida', 'Yamada', 'Mori', 'Hayashi', 'Inoue', 'Shimizu',
              'Kimura', 'Yamaguchi', 'Ogawa', 'Matsumoto', 'Saito', 'Goto',
              'Kaneko', 'Endo', 'Aoki', 'Fukuda', 'Sakamoto', 'Yokoyama', 'Miura', 'Ando', 'Ishii', 'Taniguchi',
              'Uchida', 'Takagi', 'Nakagawa', 'Kubo', 'Matsuda', 'Harada', 'Nomura', 'Sakai', 'Sugawara', 'Doi',
              'Onishi', 'Tsuchiya', 'Kudo', 'Yano', 'Sekine', 'Wada', 'Iwata', 'Hori', 'Sugiyama', 'Kikuchi'],
  },

  // ── OTAKU ─────────────────────────────────────────────────────────────────
  'Otaku': {
    masc:    ['Satoshi', 'Tomohiro', 'Noboru', 'Kazuaki', 'Shigeru', 'Hiroshi', 'Makoto',
              'Tetsuya', 'Kenji', 'Toshihiko', 'Masao', 'Yasuhiro', 'Fumihiko', 'Shuji', 'Koji',
              'Akinobu', 'Bunshiro', 'Choichi', 'Daizo', 'Etsuji', 'Fuyuhiko', 'Gishi', 'Hironobu', 'Ikuo', 'Junzo',
              'Kanji', 'Masahiko', 'Norihiro', 'Osamu', 'Ryuzo', 'Shinnosuke', 'Takanori', 'Umeji', 'Wataru', 'Yoshinobu',
              'Akitomo', 'Chikahiro', 'Fumitake', 'Gishin', 'Hidetomo', 'Isao', 'Junnosuke', 'Kunitomo', 'Michinori', 'Nobutaka', 'Ranei', 'Shunzo', 'Takeharu', 'Umezo', 'Yoritsugu'],
    fem:     ['Tomoko', 'Yumiko', 'Fumiko', 'Noriko', 'Sachiko', 'Akiko', 'Yukiko',
              'Yoshiko', 'Keiko', 'Hiroko', 'Michiko', 'Mariko', 'Kyoko', 'Kazuko', 'Naoko',
              'Ayano', 'Chikako', 'Emiko', 'Fusako', 'Harumi', 'Ikuyo', 'Junko', 'Kanae', 'Machiyo', 'Nobue',
              'Ritsuko', 'Sumie', 'Takako', 'Umeyo', 'Wakae', 'Yasuyo', 'Chieko', 'Etsuyo', 'Fumiyo', 'Gyokuko',
              'Hisayo', 'Kikuyo', 'Masayo', 'Norie', 'Ranko', 'Sayoko', 'Toyoe', 'Umeko', 'Wakaba', 'Yukie', 'Airieko', 'Botanne', 'Chisayo', 'Detomo', 'Emisayo'],
    neutral: ['Tomo', 'Hikaru', 'Rei', 'Nao', 'Kaoru', 'Akira', 'Saki', 'Yuu'],
    last:    ['Sasaki', 'Yamazaki', 'Matsumoto', 'Ikeda', 'Hashimoto', 'Fujiwara',
              'Nishimura', 'Ishikawa', 'Abe', 'Miyamoto', 'Hasegawa', 'Kondo', 'Honda',
              'Tamura', 'Nakajima', 'Ueda', 'Saito', 'Kawamoto', 'Ogawa', 'Goto',
              'Nakano', 'Fukushima', 'Ono', 'Kaneda', 'Shibata', 'Yasuda', 'Terada', 'Kojima', 'Anzai', 'Uehara',
              'Morita', 'Matsuura', 'Segawa', 'Takeda', 'Ishida', 'Kurihara', 'Sano', 'Nagata', 'Sekiguchi', 'Baba',
              'Nakayama', 'Morimoto', 'Ozawa', 'Igarashi', 'Kaji', 'Umeda', 'Wakabayashi', 'Yagi', 'Otsuka', 'Endo'],
  },

  // ── POPULAR CROWD ─────────────────────────────────────────────────────────
  'Popular Crowd': {
    masc:    ['Yusuke', 'Daisuke', 'Takuya', 'Ryosuke', 'Kei', 'Shota', 'Kosuke',
              'Naoki', 'Daiki', 'Sho', 'Taisei', 'Ryo', 'Kotaro', 'Masaki', 'Jun',
              'Akiyoshi', 'Bunya', 'Choki', 'Daichi', 'Eisuke', 'Fumiaki', 'Gaku', 'Haruto', 'Issei', 'Joji',
              'Kaito', 'Masaru', 'Norito', 'Ouki', 'Ryuga', 'Shingo', 'Taiyo', 'Uta', 'Wataru', 'Yuudai',
              'Akihito', 'Bunta', 'Chikai', 'Daigo', 'Genki', 'Haruki', 'Ikki', 'Junya', 'Kanata', 'Manato', 'Ranjiro', 'Shunta', 'Taketora', 'Umito', 'Yoshimasa'],
    fem:     ['Ayumi', 'Emi', 'Mika', 'Rie', 'Kaori', 'Asuka', 'Nana', 'Yuri',
              'Miho', 'Saki', 'Riko', 'Haruka', 'Yui', 'Minami', 'Mio',
              'Airi', 'Chika', 'Emika', 'Fuyumi', 'Hitomi', 'Izumi', 'Junna', 'Kotone', 'Manaka', 'Nozomi',
              'Rika', 'Sayaka', 'Tamaki', 'Umeka', 'Wakaba', 'Yuina', 'Chinatsu', 'Erika', 'Fuka', 'Harumi',
              'Ikumi', 'Kaede', 'Mizuki', 'Natsumi', 'Ririka', 'Sakiko', 'Tomomi', 'Wakana', 'Yumeka', 'Chihiro', 'Airiho', 'Botanmi', 'Chisana', 'Detoka', 'Ebisu'],
    neutral: ['Sora', 'Nao', 'Hikaru', 'Rei', 'Tomo', 'Akira', 'Natsuki', 'Kiri'],
    last:    ['Tanaka', 'Yamamoto', 'Suzuki', 'Nakamura', 'Ito', 'Watanabe', 'Kato',
              'Yoshida', 'Mori', 'Kimura', 'Shimizu', 'Hayashi', 'Inoue', 'Maeda',
              'Fujita', 'Okamoto', 'Ueda', 'Honda', 'Goto', 'Takahashi',
              'Yokota', 'Kaneko', 'Endo', 'Aoki', 'Fukuda', 'Sakamoto', 'Yokoyama', 'Miura', 'Ando', 'Ishii',
              'Taniguchi', 'Uchida', 'Takagi', 'Nakagawa', 'Kubo', 'Matsuda', 'Harada', 'Nomura', 'Sakai', 'Doi',
              'Sugawara', 'Onishi', 'Tsuchiya', 'Kudo', 'Yano', 'Sekine', 'Wada', 'Iwata', 'Hori', 'Sugiyama'],
  },

  // ── ORDINARY KID ──────────────────────────────────────────────────────────
  'Ordinary Kid': {
    masc:    ['Taro', 'Ichiro', 'Hiroshi', 'Kenji', 'Masato', 'Kazuya', 'Satoshi', 'Koichi',
              'Noboru', 'Tsutomu', 'Jun', 'Kenta', 'Naoki', 'Shota', 'Yusuke',
              'Akio', 'Bunji', 'Choji', 'Daisuke', 'Eitaro', 'Fumio', 'Gonta', 'Hideo', 'Isamu', 'Jiro',
              'Kanichi', 'Masaru', 'Norio', 'Osamu', 'Ryuta', 'Shigeo', 'Takeo', 'Ushio', 'Wataru', 'Yoshio',
              'Akira', 'Bunta', 'Chuji', 'Daigo', 'Genzo', 'Hachiro', 'Ippei', 'Junji', 'Kotaro', 'Manzo', 'Ranji', 'Shunkichi', 'Taketsugu', 'Umenosuke', 'Yorimasa'],
    fem:     ['Hanako', 'Yuki', 'Akemi', 'Keiko', 'Michiko', 'Noriko', 'Tomoko', 'Sachiko',
              'Haruko', 'Fumiko', 'Yoshiko', 'Kyoko', 'Akiko', 'Naoko', 'Reiko',
              'Ayako', 'Chiyoko', 'Emiko', 'Fusako', 'Hisako', 'Ikuko', 'Junko', 'Kimie', 'Machiko', 'Nobuko',
              'Ritsuko', 'Setsuko', 'Takako', 'Umeko', 'Wakako', 'Yasuko', 'Chieko', 'Etsuko', 'Fujiko', 'Gyoko',
              'Harue', 'Kikue', 'Masae', 'Norie', 'Ranko', 'Sayoko', 'Toyoko', 'Umeyo', 'Wakae', 'Yukie', 'Airine', 'Botanyo', 'Chisayo', 'Detomi', 'Emisae'],
    neutral: ['Nao', 'Tomo', 'Akira', 'Sora', 'Rei', 'Hikaru', 'Kaoru', 'Yuu'],
    last:    ['Tanaka', 'Yamamoto', 'Suzuki', 'Watanabe', 'Ito', 'Nakamura', 'Kobayashi',
              'Kato', 'Yoshida', 'Yamada', 'Sasaki', 'Yamazaki', 'Matsumoto', 'Inoue',
              'Kimura', 'Hayashi', 'Shimizu', 'Yamaguchi', 'Mori', 'Abe',
              'Kaneko', 'Endo', 'Aoki', 'Fukuda', 'Sakamoto', 'Yokoyama', 'Miura', 'Ando', 'Ishii', 'Taniguchi',
              'Uchida', 'Takagi', 'Nakagawa', 'Kubo', 'Matsuda', 'Harada', 'Nomura', 'Sakai', 'Sugawara', 'Doi',
              'Onishi', 'Tsuchiya', 'Kudo', 'Yano', 'Sekine', 'Wada', 'Iwata', 'Hori', 'Sugiyama', 'Kikuchi'],
  },
};
