// genres/paleolithic/names.js
// Name pools keyed by tribal broad label.
// Proto-human sounding names — short, consonant-strong, evocative.
// Surnames are totem/clan markers: natural elements and creatures.

export const NAME_POOLS = {

  // ── MAMMOTH HUNTERS ────────────────────────────────────────────────────────
  'Mammoth Hunters': {
    masc:    ['Gor', 'Krak', 'Dun', 'Bron', 'Harg', 'Tal', 'Ruk', 'Vor', 'Grel', 'Skam',
              'Ulf', 'Brak', 'Drav', 'Ekk', 'Fend', 'Gron', 'Holt', 'Irk', 'Jorn', 'Keld',
              'Lorg', 'Mund', 'Norv', 'Ost', 'Prag', 'Quon', 'Rask', 'Sturn', 'Torv', 'Ulg',
              'Vask', 'Wren', 'Yorn', 'Zurk', 'Bak', 'Chor', 'Delk', 'Erm', 'Fost', 'Gulk',
              'Hask', 'Ist', 'Jek', 'Kolg', 'Lask', 'Morn', 'Nurk', 'Olv', 'Pest', 'Rulk'],
    fem:     ['Huna', 'Ava', 'Kela', 'Nara', 'Bora', 'Tura', 'Yeva', 'Grela', 'Drava', 'Mira',
              'Sera', 'Tala', 'Vela', 'Wyna', 'Xara', 'Zela', 'Alna', 'Breva', 'Cana', 'Dela',
              'Elva', 'Fenna', 'Gora', 'Hilda', 'Isla', 'Jora', 'Kelva', 'Luna', 'Morra', 'Nira',
              'Olva', 'Pera', 'Runa', 'Sula', 'Tova', 'Ulva', 'Vira', 'Wenna', 'Yola', 'Zora',
              'Asta', 'Berna', 'Corra', 'Dana', 'Erla', 'Fira', 'Gunna', 'Hela', 'Irsa', 'Jenna'],
    neutral: ['Ash', 'Tusk', 'Flint', 'Stone', 'Ice', 'Bone', 'Snow', 'Gale', 'Shard', 'Peak',
              'Sleet', 'Frost', 'Bluff', 'Crag', 'Drift'],
    last:    ['Ashbone', 'Coldstone', 'Darkflint', 'Earthback', 'Firebone', 'Greatherd',
              'Hardrock', 'Iceborn', 'Jawbone', 'Killstone', 'Longspear', 'Mammotheye',
              'Northwind', 'Oldblood', 'Plainmark', 'Rockfall', 'Strongback', 'Tundraborn',
              'Whitepelt', 'Wolfchest', 'Antlerhand', 'Bloodtusk', 'Cravenbone', 'Direherd',
              'Elktrack', 'Frostmane', 'Greatfang', 'Hidebound', 'Icewalker', 'Javelinarm',
              'Killfrost', 'Longtusk', 'Mammothborn', 'Nighthide', 'Oxfooted', 'Packleader',
              'Quarrymark', 'Ridgebone', 'Snowtrack', 'Thickhide', 'Underfrost', 'Vastherd',
              'Warmblood', 'Wintermark', 'Ashenherd', 'Boarhide', 'Coldtusk', 'Direfrost', 'Emberherd', 'Frostjaw'],
  },

  // ── RIVER PEOPLE ──────────────────────────────────────────────────────────
  'River People': {
    masc:    ['Edo', 'Kan', 'Lom', 'Pari', 'Rel', 'Sev', 'Tiru', 'Venu', 'Wasi', 'Yaru',
              'Anu', 'Benu', 'Duru', 'Filu', 'Genu', 'Haku', 'Ibu', 'Jiru', 'Koru', 'Lenu',
              'Mesu', 'Niru', 'Oju', 'Pesu', 'Qadu', 'Reku', 'Sotu', 'Teku', 'Ulu', 'Vetu',
              'Wiru', 'Xolu', 'Yeku', 'Zatu', 'Abu', 'Boru', 'Ceku', 'Detu', 'Elu', 'Foku',
              'Garu', 'Hetu', 'Ilu', 'Joku', 'Katu', 'Lelu', 'Motu', 'Netu', 'Oru', 'Petu'],
    fem:     ['Ela', 'Faru', 'Hiru', 'Lara', 'Nuri', 'Olu', 'Pala', 'Rusa', 'Sira', 'Tula',
              'Ama', 'Bira', 'Cela', 'Diru', 'Emu', 'Fela', 'Gura', 'Hara', 'Iru', 'Jala',
              'Kesu', 'Lira', 'Mora', 'Netu', 'Osa', 'Peru', 'Rila', 'Situ', 'Tara', 'Umu',
              'Vela', 'Wesu', 'Xira', 'Yola', 'Zetu', 'Anila', 'Belu', 'Coru', 'Dela', 'Eku',
              'Fira', 'Golu', 'Hesu', 'Isha', 'Jelu', 'Kora', 'Lesu', 'Mila', 'Notu', 'Opa'],
    neutral: ['Reed', 'River', 'Drift', 'Wade', 'Flow', 'Mist', 'Tide', 'Brook', 'Foam', 'Weir',
              'Silt', 'Eddy', 'Pool', 'Rush', 'Current'],
    last:    ['Riverbed', 'Mudstone', 'Wetstone', 'Longcurrent', 'Deepwade', 'Fishbone',
              'Gentleflow', 'Heron-Eye', 'Ironreed', 'Pondmark', 'Quietwater', 'Rushbed',
              'Sandbar', 'Spawning-Run', 'Trout-Blood', 'Underpool', 'Valleyborn',
              'Watermark', 'Eel-Catch', 'Frogstone', 'Basketweave', 'Carp-Runner', 'Driftwood',
              'Estuary-Born', 'Fishtrap', 'Gravelbed', 'Highwater', 'Islandborn', 'Junction-Flow',
              'Kingfisher-Eye', 'Lily-Root', 'Millstone', 'Netcaster', 'Oxbow-Turn', 'Pebbleshore',
              'Quickcurrent', 'Reedcutter', 'Streambed', 'Troutfollower', 'Upstream-Walk',
              'Wading-Deep', 'Ashenmarsh', 'Backwater', 'Channelborn', 'Delta-Kin', 'Eddy-Born', 'Fen-Walker', 'Gravelrun', 'Headwater-Kin', 'Islet-Born'],
  },

  // ── CAVE DWELLERS ─────────────────────────────────────────────────────────
  'Cave Dwellers': {
    masc:    ['Dar', 'Kem', 'Lok', 'Mor', 'Nar', 'Pek', 'Rok', 'Sol', 'Tor', 'Vok',
              'Ack', 'Bor', 'Dek', 'Fok', 'Gak', 'Hek', 'Ick', 'Jok', 'Kak', 'Lek',
              'Mok', 'Nek', 'Ork', 'Pak', 'Quk', 'Rek', 'Sok', 'Tek', 'Uk', 'Vek',
              'Wok', 'Xek', 'Yak', 'Zok', 'Ban', 'Chok', 'Duk', 'Ek', 'Fak', 'Gek',
              'Hok', 'Ik', 'Juk', 'Kok', 'Lak', 'Mek', 'Nok', 'Oak', 'Pok', 'Ruk'],
    fem:     ['Ara', 'Bela', 'Dava', 'Ela', 'Fara', 'Huna', 'Isa', 'Kava', 'Lava', 'Mara',
              'Nava', 'Ola', 'Para', 'Rava', 'Sela', 'Tava', 'Ula', 'Vara', 'Wala', 'Xela',
              'Yara', 'Zava', 'Anka', 'Bexa', 'Cora', 'Doka', 'Enka', 'Foka', 'Goka', 'Hoka',
              'Ika', 'Joka', 'Koka', 'Loka', 'Moka', 'Noka', 'Ooka', 'Poka', 'Roka', 'Soka',
              'Toka', 'Uka', 'Voka', 'Woka', 'Yoka', 'Zoka', 'Anta', 'Besa', 'Ceta', 'Deta'],
    neutral: ['Ochre', 'Amber', 'Chalk', 'Ember', 'Pitch', 'Shadow', 'Smoke', 'Spark', 'Dark', 'Hollow',
              'Echo', 'Gallery', 'Deep', 'Glow', 'Soot'],
    last:    ['Ashwall', 'Bonedepth', 'Cavemark', 'Darkstone', 'Deepfire', 'Echowall',
              'Flintborn', 'Galleryborn', 'Handmark', 'Ironochre', 'Jaw-of-Stone', 'Knapper',
              'Longwall', 'Mountainborn', 'Nightstone', 'Ochremark', 'Pigmenthand',
              'Rockborn', 'Stonecutter', 'Underearth', 'Ashcavern', 'Blindpassage', 'Chalkhand',
              'Deepvein', 'Emberwall', 'Firelit', 'Grottoborn', 'Hearthstone', 'Innerdark',
              'Karst-Born', 'Lampblack', 'Mineralveil', 'Nookdweller', 'Overhang-Kin', 'Passagemark',
              'Quartzhand', 'Ridgehollow', 'Soot-Painter', 'Torchbearer', 'Undervault', 'Vaultborn',
              'Wallpainter', 'Ashencavern', 'Blackrock', 'Coalmark', 'Direchamber', 'Emberhollow', 'Fissureborn', 'Gravelfloor', 'Hollowkin'],
  },

  // ── COASTAL FORAGERS ──────────────────────────────────────────────────────
  'Coastal Foragers': {
    masc:    ['Kai', 'Mor', 'Ren', 'Sal', 'Tel', 'Var', 'Wen', 'Xan', 'Yel', 'Zan',
              'Abas', 'Balu', 'Coro', 'Delu', 'Embu', 'Folu', 'Galu', 'Helu', 'Ibalu', 'Joru',
              'Kelo', 'Lomu', 'Naro', 'Osu', 'Pelo', 'Roku', 'Selo', 'Talu', 'Umo', 'Velu',
              'Wako', 'Xolu', 'Yaro', 'Zelu', 'Ako', 'Bemu', 'Colu', 'Deko', 'Elu', 'Femo',
              'Golu', 'Heko', 'Ilu', 'Jomo', 'Kalu', 'Leko', 'Molu', 'Neko', 'Olu', 'Pako'],
    fem:     ['Ara', 'Bisa', 'Cora', 'Dela', 'Ela', 'Fina', 'Gara', 'Hina', 'Ira', 'Jina',
              'Kola', 'Lira', 'Mina', 'Nora', 'Osa', 'Pina', 'Rina', 'Sina', 'Tina', 'Uva',
              'Vela', 'Wisa', 'Xora', 'Yena', 'Zina', 'Alia', 'Besa', 'Cira', 'Dosa', 'Etna',
              'Fira', 'Gosa', 'Hira', 'Iosa', 'Jira', 'Kosa', 'Lina', 'Mosa', 'Nira', 'Osta',
              'Pira', 'Rosa', 'Sira', 'Tosa', 'Ura', 'Vira', 'Wosa', 'Xira', 'Yosa', 'Zira'],
    neutral: ['Salt', 'Tide', 'Shore', 'Gull', 'Kelp', 'Crag', 'Swell', 'Reef', 'Brine', 'Foam',
              'Shell', 'Drift', 'Wrack', 'Mist', 'Spray'],
    last:    ['Saltbone', 'Tidemark', 'Shoreborn', 'Gull-Eye', 'Kelp-Catcher', 'Deep-Reef',
              'Brine-Walker', 'Foam-Kin', 'Shell-Mound', 'Wave-Reader', 'Rock-Pool',
              'Oar-Grip', 'Ebb-Born', 'Coral-Touch', 'Otter-Blood', 'Clam-Digger',
              'Heron-Watch', 'Surf-Runner', 'Spume-Born', 'Anchor-Stone', 'Barnacle-Kin',
              'Cove-Dweller', 'Driftwood-Born', 'Estuary-Walker', 'Fishweir', 'Gullcaller',
              'Highwave', 'Inlet-Born', 'Jetty-Stone', 'Kelp-Weaver', 'Lowtide-Kin', 'Mussel-Bed',
              'Netmender', 'Ocean-Sung', 'Pearl-Diver', 'Rockpool-Born', 'Seaglass', 'Tidepool-Kin',
              'Undertow', 'Vastwater', 'Whalebone', 'Ashenshore', 'Bay-Kin', 'Cliffwatch', 'Driftnet', 'Emberide', 'Foamborn', 'Gullhaven', 'Harborkin', 'Isle-Walker'],
  },

  // ── FOREST WANDERERS ──────────────────────────────────────────────────────
  'Forest Wanderers': {
    masc:    ['Bren', 'Cael', 'Dael', 'Fen', 'Gael', 'Hael', 'Irel', 'Jael', 'Kael', 'Lael',
              'Mael', 'Nael', 'Oel', 'Pael', 'Rael', 'Sael', 'Tael', 'Uael', 'Vael', 'Wael',
              'Xael', 'Yael', 'Zael', 'Aren', 'Berel', 'Corel', 'Durel', 'Erel', 'Forel', 'Gurel',
              'Harel', 'Irol', 'Jurel', 'Korel', 'Lurel', 'Morel', 'Nurel', 'Orel', 'Purel', 'Qurel',
              'Rurel', 'Surel', 'Turel', 'Urel', 'Vurel', 'Worel', 'Xurel', 'Yurel', 'Zurel', 'Aorel'],
    fem:     ['Brana', 'Cala', 'Dana', 'Fana', 'Gala', 'Hala', 'Iala', 'Jana', 'Kana', 'Lana',
              'Mana', 'Nala', 'Oana', 'Pana', 'Rana', 'Sana', 'Tana', 'Uana', 'Vana', 'Wana',
              'Xana', 'Yana', 'Zana', 'Arena', 'Berna', 'Corna', 'Durna', 'Erna', 'Forna', 'Gurna',
              'Harna', 'Irona', 'Jurna', 'Korna', 'Lurna', 'Morna', 'Nurna', 'Orna', 'Purna', 'Qurna',
              'Rurna', 'Surna', 'Turna', 'Urna', 'Vurna', 'Worna', 'Xurna', 'Yurna', 'Zurna', 'Aorna'],
    neutral: ['Briar', 'Fern', 'Moss', 'Root', 'Thorn', 'Bark', 'Leaf', 'Branch', 'Bough', 'Grove',
              'Canopy', 'Shade', 'Hollow', 'Burrow', 'Thicket'],
    last:    ['Ashwood', 'Briarborn', 'Canopymark', 'Darkwood', 'Elm-Heart', 'Fernback',
              'Grovedweller', 'Hollowborn', 'Ivygrip', 'Juniperborn', 'Knot-Root',
              'Leafmark', 'Mosscrown', 'Nightwood', 'Oak-Blood', 'Pinecrest', 'Quiverleaf',
              'Root-Runner', 'Shadewood', 'Thorn-Path', 'Antlerhide', 'Bramblekin', 'Coppiceborn',
              'Deerwalker', 'Evergreenhand', 'Foxtrail', 'Glade-Born', 'Heartwood', 'Ironbark',
              'Junglemark', 'Kinbark', 'Lichenskin', 'Mistbranch', 'Needlefall', 'Owlwatch',
              'Ravenroost', 'Silentstep', 'Timberborn', 'Underbrush', 'Vinewalker', 'Wolfden',
              'Ashenbough', 'Barkstrider', 'Coverthide', 'Duskthicket', 'Emberbranch', 'Fallenleaf', 'Grovekin', 'Hazelbrook', 'Ivythorn'],
  },

  // ── HIGHLAND CLAN ─────────────────────────────────────────────────────────
  'Highland Clan': {
    masc:    ['Ack', 'Brak', 'Cruk', 'Druk', 'Fruk', 'Gruk', 'Hruk', 'Iruk', 'Jruk', 'Kruk',
              'Arl', 'Brl', 'Carl', 'Darl', 'Earl', 'Farl', 'Garl', 'Harl', 'Iarl', 'Jarl',
              'Lruk', 'Mruk', 'Nruk', 'Oruk', 'Pruk', 'Qruk', 'Rruk', 'Sruk', 'Truk', 'Uruk',
              'Karl', 'Larl', 'Marl', 'Narl', 'Oarl', 'Parl', 'Quarl', 'Rarl', 'Sarl', 'Tarl',
              'Vruk', 'Wruk', 'Xruk', 'Yruk', 'Zruk', 'Uarl', 'Varl', 'Warl', 'Xarl', 'Yarl'],
    fem:     ['Arka', 'Breka', 'Creka', 'Dreka', 'Freka', 'Greka', 'Hreka', 'Ireka', 'Jreka', 'Kreka',
              'Alta', 'Belta', 'Celta', 'Delta', 'Elta', 'Felta', 'Gelta', 'Helta', 'Ielta', 'Jelta',
              'Lreka', 'Mreka', 'Nreka', 'Oreka', 'Preka', 'Qreka', 'Rreka', 'Sreka', 'Treka', 'Ureka',
              'Kelta', 'Lelta', 'Melta', 'Nelta', 'Oelta', 'Pelta', 'Quelta', 'Relta', 'Selta', 'Telta',
              'Vreka', 'Wreka', 'Xreka', 'Yreka', 'Zreka', 'Uelta', 'Velta', 'Welta', 'Xelta', 'Yelta'],
    neutral: ['Peak', 'Ridge', 'Pass', 'Bluff', 'Scarp', 'Crag', 'Fell', 'Tor', 'Glen', 'Cairn',
              'Wind', 'Moor', 'Heath', 'Scree', 'Summit'],
    last:    ['Ascent', 'Blizzard-Born', 'Coldpass', 'Direwolf-Scar', 'Eagle-Eye',
              'Frost-Walker', 'Goat-Blood', 'High-Ground', 'Ice-Heart', 'Jagged-Peak',
              'Kestrel-Mark', 'Ledge-Born', 'Mist-Walker', 'North-Wind', 'Overhang',
              'Peak-Dweller', 'Quartzhand', 'Ridgeback', 'Stone-Climber', 'Tundra-Edge',
              'Ash-Summit', 'Boulder-Born', 'Cliffhold', 'Craghand', 'Echo-Ridge', 'Falcon-Perch',
              'Granite-Kin', 'Heather-Walk', 'Iceridge', 'Juniper-Peak', 'Knuckle-Rock', 'Lichenstone',
              'Moraine-Born', 'Notch-Walker', 'Outcrop-Kin', 'Pinnacle-Born', 'Rimewalker',
              'Scarpwalker', 'Talus-Born', 'Uplandborn', 'Ashenscarp', 'Bluffwatch', 'Coldsummit', 'Deepnotch', 'Emberpeak', 'Frostridge', 'Gorgeborn', 'Hawkperch', 'Icecliff', 'Jaggedhorn'],
  },

  // ── GRASSLAND NOMADS ──────────────────────────────────────────────────────
  'Grassland Nomads': {
    masc:    ['Aro', 'Bero', 'Cero', 'Dero', 'Ero', 'Fero', 'Gero', 'Hero', 'Iero', 'Jero',
              'Ako', 'Beko', 'Ceko', 'Deko', 'Eko', 'Feko', 'Geko', 'Heko', 'Ieko', 'Jeko',
              'Kero', 'Lero', 'Mero', 'Nero', 'Oero', 'Pero', 'Quero', 'Rero', 'Sero', 'Tero',
              'Keko', 'Leko', 'Meko', 'Neko', 'Oeko', 'Peko', 'Queko', 'Reko', 'Seko', 'Teko',
              'Uro', 'Vero', 'Wero', 'Xero', 'Yero', 'Zero', 'Ueko', 'Veko', 'Weko', 'Yeko'],
    fem:     ['Aera', 'Bera', 'Cera', 'Dera', 'Era', 'Fera', 'Gera', 'Hera', 'Iera', 'Jera',
              'Asha', 'Besha', 'Cesha', 'Desha', 'Esha', 'Fesha', 'Gesha', 'Hesha', 'Iesha', 'Jesha',
              'Kera', 'Lera', 'Mera', 'Nera', 'Oera', 'Pera', 'Quera', 'Rera', 'Sera', 'Tera',
              'Kesha', 'Lesha', 'Mesha', 'Nesha', 'Oesha', 'Pesha', 'Quesha', 'Resha', 'Sesha', 'Tesha',
              'Uera', 'Vera', 'Wera', 'Xera', 'Yera', 'Zera', 'Uesha', 'Vesha', 'Wesha', 'Yesha'],
    neutral: ['Steppe', 'Plain', 'Grass', 'Wind', 'Dust', 'Horizon', 'Herd', 'Burn', 'Ember', 'Trail',
              'Stampede', 'Drought', 'Rain', 'Lightning', 'Field'],
    last:    ['Ashfield', 'Bison-Blood', 'Charred-Ground', 'Dustborn', 'Ember-Path',
              'Far-Horizon', 'Grass-Runner', 'Herd-Mark', 'Iron-Stamper', 'Journey-Long',
              'Kill-Plain', 'Longtrail', 'Meadow-Born', 'Nomad-Heart', 'Open-Sky',
              'Plain-Walker', 'Quake-Earth', 'Runningfire', 'Steppe-Born', 'Thunderstep',
              'Antelope-Chaser', 'Bramblewind', 'Cloudshadow', 'Driftgrass', 'Emberdust',
              'Fireontheplain', 'Goldengrass', 'Highplain-Kin', 'Ironwind', 'Kite-Watcher',
              'Longshadow', 'Migrant-Born', 'Nightherd', 'Overland', 'Pathfinder-Kin',
              'Questrail', 'Rangewalker', 'Sunburnt', 'Trailmarker', 'Vastplain',
              'Ashenwind', 'Boundlessgrass', 'Cattledrive', 'Duskplain', 'Emberhorizon', 'Farwalker', 'Grasslandborn', 'Hardpan-Kin', 'Ironhoof', 'Junegrass'],
  },

  // ── DESERT SURVIVORS ──────────────────────────────────────────────────────
  'Desert Survivors': {
    masc:    ['Aden', 'Badin', 'Cadin', 'Dadin', 'Edin', 'Fadin', 'Gadin', 'Hadin', 'Iadin', 'Jadin',
              'Aker', 'Baker', 'Caker', 'Daker', 'Eaker', 'Faker', 'Gaker', 'Haker', 'Iaker', 'Jaker',
              'Kadin', 'Ladin', 'Madin', 'Nadin', 'Oadin', 'Padin', 'Qadin', 'Radin', 'Sadin', 'Tadin',
              'Kaker', 'Laker', 'Maker', 'Naker', 'Oaker', 'Paker', 'Qaker', 'Raker', 'Saker', 'Taker',
              'Uadin', 'Vadin', 'Wadin', 'Xadin', 'Yadin', 'Zadin', 'Uaker', 'Vaker', 'Waker', 'Yaker'],
    fem:     ['Adna', 'Badna', 'Cadna', 'Dadna', 'Edna', 'Fadna', 'Gadna', 'Hadna', 'Iadna', 'Jadna',
              'Afra', 'Bafra', 'Cafra', 'Dafra', 'Efra', 'Fafra', 'Gafra', 'Hafra', 'Iafra', 'Jafra',
              'Kadna', 'Ladna', 'Madna', 'Nadna', 'Oadna', 'Padna', 'Qadna', 'Radna', 'Sadna', 'Tadna',
              'Kafra', 'Lafra', 'Mafra', 'Nafra', 'Oafra', 'Pafra', 'Qafra', 'Rafra', 'Safra', 'Tafra',
              'Uadna', 'Vadna', 'Wadna', 'Xadna', 'Yadna', 'Zadna', 'Uafra', 'Vafra', 'Wafra', 'Yafra'],
    neutral: ['Grit', 'Sand', 'Dune', 'Shard', 'Bone', 'Dry', 'Crack', 'Dust', 'Parch', 'Mirage',
              'Oasis', 'Flint', 'Hollow', 'Dark', 'Stone'],
    last:    ['Arid-Born', 'Bone-Dry', 'Cracked-Earth', 'Dustwalker', 'Edge-of-Shade',
              'Flintmark', 'Gritborn', 'Heatwalker', 'Iron-Sun', 'Jawbone',
              'Kill-Dry', 'Leather-Skin', 'Midnight-Walk', 'Nighthunter', 'Ochre-Sand',
              'Parched-Land', 'Quick-Water', 'Rock-Seeker', 'Sand-Runner', 'Thirstborn',
              'Ash-Basin', 'Blazing-Kin', 'Canyon-Walker', 'Duneborn', 'Emberdrought',
              'Farsight-Walker', 'Glasswind', 'Heatshimmer', 'Ironmirage', 'Jackal-Kin',
              'Kiln-Skinned', 'Longshadow-Walk', 'Mesa-Born', 'Nightcool', 'Oasis-Keeper',
              'Parchskin', 'Quiethunt', 'Redrock-Kin', 'Scorpion-Watch', 'Vulture-Sworn',
              'Ashendune', 'Barrenwalker', 'Cactusveil', 'Direheat', 'Emberdune', 'Flatrock-Kin', 'Grimsand', 'Hardpan-Walker', 'Ironmesa', 'Junipersage'],
  },
};
