// genres/modern/secrets.js
// One hidden thing per character — something the AI can pull on for dramatic tension.
// Secrets should never be stated openly in the character Entry;
// they inform how the AI steers the story.
//
// Each secret carries:
//   id, description, toneTag, severity (low | medium | high | explosive),
//   statAffinity, criminalFlag (bool)

export const SECRETS = [

  // ── CRIMINAL PAST ─────────────────────────────────────────────────────────
  {
    id: 'got_away_with_it',
    description: 'Was responsible for a serious crime years ago — and was never caught',
    toneTag: 'gritty',
    severity: 'explosive',
    statAffinity: { intelligence: 1.2, wisdom: 0.9 },
    criminalFlag: true,
  },
  {
    id: 'witnessed_crime_silent',
    description: 'Witnessed a violent crime and said nothing — someone else took the fall',
    toneTag: 'gritty',
    severity: 'high',
    statAffinity: { constitution: 0.9, wisdom: 0.9 },
    criminalFlag: true,
  },
  {
    id: 'stole_from_employer',
    description: 'Embezzled money from a former employer — never discovered',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { intelligence: 1.2, wisdom: 0.8 },
    criminalFlag: true,
  },
  {
    id: 'informant',
    description: 'Has been, or currently is, a confidential informant for law enforcement',
    toneTag: 'gritty',
    severity: 'explosive',
    statAffinity: { charisma: 1.1, constitution: 0.9 },
    criminalFlag: true,
  },
  {
    id: 'faked_death',
    description: 'Someone important from their past believes they are dead — intentionally',
    toneTag: 'gritty',
    severity: 'explosive',
    statAffinity: { intelligence: 1.3, charisma: 1.1 },
    criminalFlag: false,
  },
  {
    id: 'hit_and_run',
    description: 'Was involved in a hit-and-run accident and fled the scene',
    toneTag: 'gritty',
    severity: 'explosive',
    statAffinity: { wisdom: 0.7, constitution: 0.9 },
    criminalFlag: true,
  },
  {
    id: 'blackmail_material',
    description: 'Holds damaging information about a powerful person — and hasn\'t decided what to do with it',
    toneTag: 'gritty',
    severity: 'high',
    statAffinity: { intelligence: 1.3, charisma: 1.1 },
    criminalFlag: true,
  },

  // ── IDENTITY & DECEPTION ──────────────────────────────────────────────────
  {
    id: 'fake_credentials',
    description: 'Their professional credentials are forged or falsified',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { intelligence: 1.2, charisma: 1.2 },
    criminalFlag: true,
  },
  {
    id: 'false_identity',
    description: 'Has been living under a false name or constructed identity for years',
    toneTag: 'gritty',
    severity: 'explosive',
    statAffinity: { intelligence: 1.3, charisma: 1.2 },
    criminalFlag: true,
  },
  {
    id: 'secret_past_life',
    description: 'Had a completely different life before — different name, different city, different person',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { wisdom: 1.2, charisma: 1.1 },
    criminalFlag: false,
  },
  {
    id: 'lied_about_background',
    description: 'Has systematically lied about their upbringing and family to everyone around them',
    toneTag: 'dramatic',
    severity: 'medium',
    statAffinity: { charisma: 1.2, wisdom: 0.9 },
    criminalFlag: false,
  },
  {
    id: 'secret_family',
    description: 'Has a child — or a whole family — that their current life doesn\'t know about',
    toneTag: 'dramatic',
    severity: 'explosive',
    statAffinity: { charisma: 1.1, wisdom: 0.8 },
    criminalFlag: false,
  },

  // ── BETRAYAL ──────────────────────────────────────────────────────────────
  {
    id: 'betrayed_a_friend',
    description: 'Betrayed a close friend in a serious way — and let them believe something else happened',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { charisma: 1.1, wisdom: 0.8 },
    criminalFlag: false,
  },
  {
    id: 'turned_someone_in',
    description: 'Reported someone — friend, family, or colleague — to authorities, anonymously',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { wisdom: 1.2, charisma: 0.9 },
    criminalFlag: false,
  },
  {
    id: 'affair_ongoing',
    description: 'Currently having an affair — with someone their partner knows',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { charisma: 1.2, wisdom: 0.7 },
    criminalFlag: false,
  },
  {
    id: 'sabotaged_colleague',
    description: 'Deliberately sabotaged a colleague\'s career to get ahead',
    toneTag: 'dramatic',
    severity: 'medium',
    statAffinity: { intelligence: 1.2, wisdom: 0.8 },
    criminalFlag: false,
  },
  {
    id: 'stole_credit',
    description: 'Built their reputation on work that was partially or fully someone else\'s',
    toneTag: 'dramatic',
    severity: 'medium',
    statAffinity: { intelligence: 1.1, wisdom: 0.8, charisma: 1.1 },
    criminalFlag: false,
  },

  // ── HEALTH & MENTAL HEALTH ────────────────────────────────────────────────
  {
    id: 'hidden_addiction',
    description: 'Still using — or using again — and nobody knows',
    toneTag: 'gritty',
    severity: 'high',
    statAffinity: { constitution: 0.8, wisdom: 0.8 },
    criminalFlag: false,
  },
  {
    id: 'serious_diagnosis_hidden',
    description: 'Has received a serious or terminal medical diagnosis and told no one',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { constitution: 0.8, wisdom: 1.2 },
    criminalFlag: false,
  },
  {
    id: 'mental_health_secret',
    description: 'Has been managing a serious mental health condition in secret for years',
    toneTag: 'dramatic',
    severity: 'medium',
    statAffinity: { intelligence: 1.2, constitution: 0.9 },
    criminalFlag: false,
  },
  {
    id: 'attempted_suicide',
    description: 'Survived a suicide attempt that no one in their current life knows about',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { wisdom: 1.2, constitution: 0.8 },
    criminalFlag: false,
  },

  // ── MONEY & POWER ─────────────────────────────────────────────────────────
  {
    id: 'hidden_wealth',
    description: 'Has significantly more money hidden away than anyone around them knows',
    toneTag: 'neutral',
    severity: 'medium',
    statAffinity: { intelligence: 1.2, charisma: 1.1 },
    criminalFlag: false,
  },
  {
    id: 'hidden_debt',
    description: 'Carrying a debt load that would shock everyone who thinks they\'re stable',
    toneTag: 'dramatic',
    severity: 'medium',
    statAffinity: { wisdom: 0.8, charisma: 1.1 },
    criminalFlag: false,
  },
  {
    id: 'bribed_someone',
    description: 'Bribed an official, officer, or gatekeeper to get where they are',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { charisma: 1.2, intelligence: 1.1 },
    criminalFlag: true,
  },
  {
    id: 'inheritance_stolen',
    description: 'Manipulated or deceived a family member out of money or inheritance',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { charisma: 1.2, wisdom: 0.8 },
    criminalFlag: false,
  },

  // ── QUIETER SECRETS ───────────────────────────────────────────────────────
  {
    id: 'not_really_over_it',
    description: 'Still deeply in love with someone from their past — and pretending otherwise',
    toneTag: 'cozy',
    severity: 'low',
    statAffinity: { wisdom: 0.9, charisma: 1.1 },
    criminalFlag: false,
  },
  {
    id: 'regrets_a_child',
    description: 'Secretly regrets having children — and lives with profound guilt about it',
    toneTag: 'dramatic',
    severity: 'medium',
    statAffinity: { wisdom: 1.1, constitution: 0.9 },
    criminalFlag: false,
  },
  {
    id: 'wants_to_leave',
    description: 'Desperately wants to abandon their current life entirely — has a plan forming',
    toneTag: 'neutral',
    severity: 'medium',
    statAffinity: { wisdom: 1.2, charisma: 0.9 },
    criminalFlag: false,
  },
  {
    id: 'wrote_something',
    description: 'Wrote something — a letter, journal, manifesto — that would destroy relationships if found',
    toneTag: 'cozy',
    severity: 'medium',
    statAffinity: { intelligence: 1.2, wisdom: 1.1 },
    criminalFlag: false,
  },
  {
    id: 'famous_anonymously',
    description: 'Is anonymously famous — a blogger, creator, or figure — that no one in their life knows about',
    toneTag: 'cozy',
    severity: 'low',
    statAffinity: { intelligence: 1.2, charisma: 1.1 },
    criminalFlag: false,
  },
  {
    id: 'doesnt_believe',
    description: 'Has privately lost faith in a religion or ideology that still defines their community',
    toneTag: 'neutral',
    severity: 'low',
    statAffinity: { wisdom: 1.2, intelligence: 1.1 },
    criminalFlag: false,
  },
  {
    id: 'ghost_from_past',
    description: 'Someone they hurt badly long ago has recently surfaced in their city — they don\'t know it yet',
    toneTag: 'dramatic',
    severity: 'high',
    statAffinity: { wisdom: 0.9, charisma: 1.1 },
    criminalFlag: false,
  },
];
