// ── HAIR ─────────────────────────────────────────────────────────────────
export const HAIR = [
  { id: "auburn_braided", label: "auburn hair, braided" },
  { id: "bald", label: "bald" },
  { id: "black_close_cropped", label: "black hair, close-cropped" },
  { id: "black_long_straight", label: "black hair, long and straight" },
  {
    id: "black_medium_greased",
    label: "black hair, medium-length, greased and slicked back",
  },
  { id: "black_swept_one_side", label: "black hair, swept to one side" },
  { id: "black_braided", label: "black hair, braided" },
  { id: "black_voluminous", label: "black hair, voluminous" },
  { id: "black_shaved_undercut", label: "black hair, with a shaved undercut" },
  { id: "black_bobcut", label: "black hair, bobcut" },
  { id: "black_short_spiky", label: "black hair, short and spiky" },
  { id: "blonde_long_loose", label: "blonde hair, long and loose" },
  { id: "blonde_shoulder_length", label: "blonde hair, shoulder-length" },
  { id: "blonde_short_spiky", label: "blonde hair, short and spiky" },
  { id: "blonde_pixie_cut", label: "blonde hair, pixie cut" },
  { id: "brown_dreadlocks", label: "brown hair, dreadlocks" },
  { id: "brown_pulled_back", label: "brown hair, pulled back" },
  { id: "brown_shoulder_length", label: "brown hair, shoulder-length" },
  { id: "brown_short_spiky", label: "brown hair, short and spiky" },
  { id: "brown_wild_unkempt", label: "brown hair, wild and unkempt" },
  {
    id: "chestnut_gorgeous_flowing_locks",
    label: "chestnut hair, gorgeous flowing locks",
  },
  { id: "gray_ponytail", label: "gray hair, ponytail" },
  { id: "gray_buzzed_short", label: "gray hair, buzzed short" },
  { id: "green_mohawk", label: "green hair, mohawk" },
  {
    id: "platinum_impeccably_styled",
    label: "platinum hair, impeccably styled",
  },
  { id: "purple_bobcut", label: "purple hair, bobcut" },
  { id: "red_barely_maintained", label: "red hair, barely maintained" },
  { id: "shaved_stubble", label: "shaved stubble" },
  { id: "silver_shaved_one_side", label: "silver hair, shaved on one side" },
  { id: "short_dark", label: "short dark hair" },
  { id: "short_light", label: "short light hair" },
  { id: "close_cropped", label: "close-cropped or shaved" },
  { id: "medium_wavy", label: "medium-length hair, wavy" },
  { id: "long_straight", label: "long hair, straight" },
  { id: "long_curly", label: "long hair, curly or coily" },
  { id: "natural_coily", label: "natural coils or locs" },
  { id: "gray_streaked", label: "going gray, not hiding it" },
  { id: "dyed", label: "hair dyed an unnatural color" },
  { id: "messy", label: "perpetually messy hair" },
  { id: "pulled_back", label: "hair always pulled back" },
  { id: "thinning", label: "thinning or receding hair" },
];
