/**
 * Common sentiments that can be used across different genres and contexts
 */
export const SENTIMENTS = [
    // ── Original ──────────────────────────────────────────────────────────────
    {
        id: 'proud',
        label: 'Proud',
        iconPrompt: "proud emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#proud.png",
    },
    {
        id: 'resentful',
        label: 'Resentful',
        iconPrompt: "resentful emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#resentful.png",
    },
    {
        id: 'indifferent',
        label: 'Indifferent',
        iconPrompt: "indifferent emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#indifferent.png",
    },
    {
        id: 'passionate',
        label: 'Passionate',
        iconPrompt: "passionate emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#passionate.png",
    },
    {
        id: 'burned_out',
        label: 'Burned Out',
        iconPrompt: "burned_out emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#burned_out.png",
    },
    {
        id: 'desperate',
        label: 'Desperate',
        iconPrompt: "desperate emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#desperate.png",
    },
    {
        id: 'quietly_satisfied',
        label: 'Quietly Satisfied',
        iconPrompt: "smug emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#quietly_satisfied.png",
    },
    {
        id: 'ashamed',
        label: 'Ashamed',
        iconPrompt: "ashamed emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#ashamed.png",
    },
    {
        id: 'lost',
        label: 'Lost',
        iconPrompt: "lost emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#lost.png",
    },

    // ── Nihongi & Joseon Dynasty ──────────────────────────────────────────────
    {
        id: 'accomplished',
        label: 'Accomplished',
        iconPrompt: "accomplished satisfied emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#accomplished.png",
    },
    {
        id: 'adaptable',
        label: 'Adaptable',
        iconPrompt: "adaptable open-faced emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#adaptable.png",
    },
    {
        id: 'alert',
        label: 'Alert',
        iconPrompt: "startled alert emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#alert.png",
    },
    {
        id: 'ambitious',
        label: 'Ambitious',
        iconPrompt: "determined ambitious emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#ambitious.png",
    },
    {
        id: 'analytical',
        label: 'Analytical',
        iconPrompt: "thinking analytical emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#analytical.png",
    },
    {
        id: 'beleaguered',
        label: 'Beleaguered',
        iconPrompt: "overwhelmed beleaguered emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#beleaguered.png",
    },
    {
        id: 'bored',
        label: 'Bored',
        iconPrompt: "yawning bored emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#bored.png",
    },
    {
        id: 'calculating',
        label: 'Calculating',
        iconPrompt: "scheming calculating emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#calculating.png",
    },
    {
        id: 'canny',
        label: 'Canny',
        iconPrompt: "shrewd winking canny emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#canny.png",
    },
    {
        id: 'careful',
        label: 'Careful',
        iconPrompt: "cautious careful emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#careful.png",
    },
    {
        id: 'community_bound',
        label: 'Community-Bound',
        iconPrompt: "warm beaming community emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#community_bound.png",
    },
    {
        id: 'compassionate',
        label: 'Compassionate',
        iconPrompt: "sympathetic compassionate emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#compassionate.png",
    },
    {
        id: 'conflicted',
        label: 'Conflicted',
        iconPrompt: "anguished conflicted emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#conflicted.png",
    },
    {
        id: 'constrained',
        label: 'Constrained',
        iconPrompt: "repressed constrained emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#constrained.png",
    },
    {
        id: 'contemplative',
        label: 'Contemplative',
        iconPrompt: "contemplative thoughtful emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#contemplative.png",
    },
    {
        id: 'contemptuous',
        label: 'Contemptuous',
        iconPrompt: "disgusted contemptuous emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#contemptuous.png",
    },
    {
        id: 'cryptic',
        label: 'Cryptic',
        iconPrompt: "smirking cryptic emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#cryptic.png",
    },
    {
        id: 'dangerous',
        label: 'Dangerous',
        iconPrompt: "menacing dangerous emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#dangerous.png",
    },
    {
        id: 'devout',
        label: 'Devout',
        iconPrompt: "serene prayerful devout emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#devout.png",
    },
    {
        id: 'diplomatic',
        label: 'Diplomatic',
        iconPrompt: "charming diplomatic emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#diplomatic.png",
    },
    {
        id: 'direct',
        label: 'Direct',
        iconPrompt: "serious stern direct emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#direct.png",
    },
    {
        id: 'discreet',
        label: 'Discreet',
        iconPrompt: "shushing discreet emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#discreet.png",
    },
    {
        id: 'duplicitous',
        label: 'Duplicitous',
        iconPrompt: "devilish grinning duplicitous emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#duplicitous.png",
    },
    {
        id: 'dutiful',
        label: 'Dutiful',
        iconPrompt: "saluting dutiful emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#dutiful.png",
    },
    {
        id: 'enduring',
        label: 'Enduring',
        iconPrompt: "weathered resolute enduring emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#enduring.png",
    },
    {
        id: 'entrusted',
        label: 'Entrusted',
        iconPrompt: "solemn entrusted emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#entrusted.png",
    },
    {
        id: 'exacting',
        label: 'Exacting',
        iconPrompt: "stern demanding exacting emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#exacting.png",
    },
    {
        id: 'fearful',
        label: 'Fearful',
        iconPrompt: "fearful emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#fearful.png",
    },
    {
        id: 'graceful',
        label: 'Graceful',
        iconPrompt: "elegant graceful emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#graceful.png",
    },
    {
        id: 'guarded',
        label: 'Guarded',
        iconPrompt: "unamused guarded emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#guarded.png",
    },
    {
        id: 'haunted',
        label: 'Haunted',
        iconPrompt: "horrified haunted emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#haunted.png",
    },
    {
        id: 'homesick',
        label: 'Homesick',
        iconPrompt: "pensive sad homesick emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#homesick.png",
    },
    {
        id: 'indispensable',
        label: 'Indispensable',
        iconPrompt: "confident indispensable emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#indispensable.png",
    },
    {
        id: 'knowing',
        label: 'Knowing',
        iconPrompt: "smug knowing emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#knowing.png",
    },
    {
        id: 'learned',
        label: 'Learned',
        iconPrompt: "nerd learned emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#learned.png",
    },
    {
        id: 'liminal',
        label: 'Liminal',
        iconPrompt: "confused between-worlds liminal emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#liminal.png",
    },
    {
        id: 'loyal',
        label: 'Loyal',
        iconPrompt: "devoted loyal emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#loyal.png",
    },
    {
        id: 'marginalized',
        label: 'Marginalized',
        iconPrompt: "sad resigned marginalized emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#marginalized.png",
    },
    {
        id: 'mediating',
        label: 'Mediating',
        iconPrompt: "peaceful mediating emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#mediating.png",
    },
    {
        id: 'methodical',
        label: 'Methodical',
        iconPrompt: "focused methodical emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#methodical.png",
    },
    {
        id: 'observant',
        label: 'Observant',
        iconPrompt: "monocle observant emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#observant.png",
    },
    {
        id: 'obsessive',
        label: 'Obsessive',
        iconPrompt: "wide-eyed obsessive emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#obsessive.png",
    },
    {
        id: 'otherworldly',
        label: 'Otherworldly',
        iconPrompt: "zany otherworldly emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#otherworldly.png",
    },
    {
        id: 'patient',
        label: 'Patient',
        iconPrompt: "serene patient emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#patient.png",
    },
    {
        id: 'perceptive',
        label: 'Perceptive',
        iconPrompt: "knowing perceptive emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#perceptive.png",
    },
    {
        id: 'politically_aware',
        label: 'Politically Aware',
        iconPrompt: "suspicious side-eye emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#politically_aware.png",
    },
    {
        id: 'practical',
        label: 'Practical',
        iconPrompt: "sensible practical emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#practical.png",
    },
    {
        id: 'pragmatic',
        label: 'Pragmatic',
        iconPrompt: "neutral pragmatic emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#pragmatic.png",
    },
    {
        id: 'prescient',
        label: 'Prescient',
        iconPrompt: "all-seeing prescient emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#prescient.png",
    },
    {
        id: 'principled',
        label: 'Principled',
        iconPrompt: "righteous principled emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#principled.png",
    },
    {
        id: 'protective',
        label: 'Protective',
        iconPrompt: "worried protective emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#protective.png",
    },
    {
        id: 'quietly_ambitious',
        label: 'Quietly Ambitious',
        iconPrompt: "sly quietly ambitious emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#quietly_ambitious.png",
    },
    {
        id: 'receptive',
        label: 'Receptive',
        iconPrompt: "attentive open receptive emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#receptive.png",
    },
    {
        id: 'resigned',
        label: 'Resigned',
        iconPrompt: "tired resigned emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#resigned.png",
    },
    {
        id: 'ritually_precise',
        label: 'Ritually Precise',
        iconPrompt: "focused precise ritually emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#ritually_precise.png",
    },
    {
        id: 'rooted',
        label: 'Rooted',
        iconPrompt: "contented earthy rooted emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#rooted.png",
    },
    {
        id: 'seasonal',
        label: 'Seasonal',
        iconPrompt: "peaceful contented seasonal emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#seasonal.png",
    },
    {
        id: 'self_sufficient',
        label: 'Self-Sufficient',
        iconPrompt: "confident independent emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#self_sufficient.png",
    },
    {
        id: 'skeptical',
        label: 'Skeptical',
        iconPrompt: "raised eyebrow skeptical emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#skeptical.png",
    },
    {
        id: 'status_conscious',
        label: 'Status-Conscious',
        iconPrompt: "proud upturned-nose status emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#status_conscious.png",
    },
    {
        id: 'stoic',
        label: 'Stoic',
        iconPrompt: "expressionless stoic emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#stoic.png",
    },
    {
        id: 'subversive',
        label: 'Subversive',
        iconPrompt: "mischievous subversive emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#subversive.png",
    },
    {
        id: 'suspicious',
        label: 'Suspicious',
        iconPrompt: "suspicious squinting emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#suspicious.png",
    },
    {
        id: 'tenacious',
        label: 'Tenacious',
        iconPrompt: "determined gritted-teeth tenacious emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#tenacious.png",
    },
    {
        id: 'traditional',
        label: 'Traditional',
        iconPrompt: "reverent traditional emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#traditional.png",
    },
    {
        id: 'understated',
        label: 'Understated',
        iconPrompt: "quiet neutral understated emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#understated.png",
    },
    {
        id: 'unsentimental',
        label: 'Unsentimental',
        iconPrompt: "blank unsentimental emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#unsentimental.png",
    },
    {
        id: 'visionary',
        label: 'Visionary',
        iconPrompt: "wide-eyed visionary emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#visionary.png",
    },
    {
        id: 'worldly',
        label: 'Worldly',
        iconPrompt: "cool sunglasses worldly emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#worldly.png",
    },
    {
        id: 'yearning',
        label: 'Yearning',
        iconPrompt: "pleading yearning emoji icon with a yellow face on a white background, shadow",
        iconPath: "generator/common/icons/SENTIMENTS#yearning.png",
    },
];
