// genres/historical-korea-joseon-dynasty/professions.js
// Professions of Joseon Dynasty Korea.
// Industries must match TAG_POOLS.professionTags keys in settings.js exactly.

export const PROFESSIONS = [
  // ── Civil Administration ──────────────────────────────────────────────
  {
    title: 'Scholar-Official',
    industry: 'Civil Administration',
    economicTier: 5,
    statAffinity: { intelligence: 1.4, wisdom: 1.2, charisma: 1.1 },
    sentiments: ['Deeply believes in rule through virtue', 'Suspicious of military power', 'Obsessed with precedent and protocol'],
    iconPrompt: 'joseon dynasty korean scholar official seated writing brush ink calligraphy silk hanbok court painting style',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#scholar_official.png',
  },
  {
    title: 'Local Magistrate',
    industry: 'Civil Administration',
    economicTier: 4,
    statAffinity: { wisdom: 1.3, charisma: 1.2, strength: 1.0 },
    sentiments: ['Proud of maintaining order', 'Constantly navigating petitions from below and pressure from above', 'Knows every local clan grudge'],
    iconPrompt: 'joseon dynasty korean local magistrate seated court judgment hall formal robes stern expression traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#local_magistrate.png',
  },
  {
    title: "Magistrate's Aide",
    industry: 'Civil Administration',
    economicTier: 3,
    statAffinity: { intelligence: 1.2, dexterity: 1.1, wisdom: 1.1 },
    sentiments: ['Keeps the actual wheels turning', 'Has leverage he will never admit to', 'Knows exactly which registers have been falsified'],
    iconPrompt: 'joseon dynasty korean magistrate aide clerk ledger records practical hanbok government office traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#magistrate_aide.png',
  },
  {
    title: 'Village Elder',
    industry: 'Civil Administration',
    economicTier: 3,
    statAffinity: { wisdom: 1.4, charisma: 1.2, constitution: 1.1 },
    sentiments: ['Memory is authority; holds grudges like deeds', 'Absorbs grievances so they do not become crimes', 'Quietly subversive of any outsider authority'],
    iconPrompt: 'joseon dynasty korean village elder seated respected elder weathered face plain hanbok village courtyard traditional folk painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#village_elder.png',
  },
  // ── Military ──────────────────────────────────────────────────────────
  {
    title: 'Royal Guard',
    industry: 'Military',
    economicTier: 4,
    statAffinity: { strength: 1.3, constitution: 1.2, dexterity: 1.1 },
    sentiments: ['Loyalty above politics', 'Has seen what palace factions do to good men', 'Trusts only what he can verify with his eyes'],
    iconPrompt: 'joseon dynasty korean royal palace guard armor helmet weapon standing guard ceremonial proud traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#royal_guard.png',
  },
  {
    title: 'Cavalry Officer',
    industry: 'Military',
    economicTier: 4,
    statAffinity: { strength: 1.3, dexterity: 1.2, constitution: 1.1 },
    sentiments: ['Contemptuous of scholars who have never bled', 'Fiercely loyal to unit over king', 'Haunted by one specific battle'],
    iconPrompt: 'joseon dynasty korean cavalry officer horse armor sword mounted warrior proud battlefield traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#cavalry_officer.png',
  },
  {
    title: 'Fortress Soldier',
    industry: 'Military',
    economicTier: 2,
    statAffinity: { strength: 1.2, constitution: 1.3, dexterity: 1.0 },
    sentiments: ['Resigned to being forgotten', 'Fiercely protective of the men beside him', 'Counts the days to rotation leave'],
    iconPrompt: 'joseon dynasty korean fortress soldier guard wall spear armor cold northern frontier tired reliable traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#fortress_soldier.png',
  },
  // ── Arts & Learning ───────────────────────────────────────────────────
  {
    title: 'Sungkyunkwan Scholar',
    industry: 'Arts & Learning',
    economicTier: 4,
    statAffinity: { intelligence: 1.4, wisdom: 1.2, charisma: 1.0 },
    sentiments: ['Burning ambition dressed in studied calm', 'Grades every conversation like an examination', 'Has memorized eight times the texts actually required'],
    iconPrompt: 'joseon dynasty korean sungkyunkwan scholar student academy night studying books candle lamp gwageo preparation traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#sungkyunkwan_scholar.png',
  },
  {
    title: 'Royal Painter',
    industry: 'Arts & Learning',
    economicTier: 3,
    statAffinity: { dexterity: 1.3, intelligence: 1.2, wisdom: 1.1 },
    sentiments: ['Sees everything through compositional instinct', 'Exists in a grey zone between artisan and official', 'Has been asked to paint things he wishes he had not'],
    iconPrompt: 'joseon dynasty korean royal court painter brush silk scroll portrait careful precise pigments traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#royal_painter.png',
  },
  {
    title: 'Court Historian',
    industry: 'Arts & Learning',
    economicTier: 4,
    statAffinity: { intelligence: 1.3, wisdom: 1.3, charisma: 0.9 },
    sentiments: ['Terrified of what he has already written down', 'Knows the difference between what happened and what the record says', 'Refuses to falsify; has survived this far by ambiguity'],
    iconPrompt: 'joseon dynasty korean court historian annals writing veritable records brush scroll official archive careful solemn traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#court_historian.png',
  },
  // ── Trade ─────────────────────────────────────────────────────────────
  {
    title: 'Market Merchant',
    industry: 'Trade',
    economicTier: 3,
    statAffinity: { charisma: 1.3, intelligence: 1.2, dexterity: 1.0 },
    sentiments: ['Knows the actual value of everything in the province', 'Despises the yangban disdain for money they spend freely', 'Has a network of informants dressed as customers'],
    iconPrompt: 'joseon dynasty korean market merchant stall goods trade jongno commercial street shrewd confident practical hanbok traditional folk painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#market_merchant.png',
  },
  {
    title: 'Traveling Peddler',
    industry: 'Trade',
    economicTier: 2,
    statAffinity: { dexterity: 1.2, charisma: 1.1, constitution: 1.2 },
    sentiments: ['Knows every road and every magistrate\'s price', 'Carries other people\'s letters for a small fee', 'Has heard the rumor that becomes the rebellion'],
    iconPrompt: 'joseon dynasty korean traveling peddler jangsu pack goods rural road village gate cheerful resilient traditional folk painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#traveling_peddler.png',
  },
  {
    title: 'Maritime Trader',
    industry: 'Trade',
    economicTier: 4,
    statAffinity: { charisma: 1.2, constitution: 1.2, intelligence: 1.2 },
    sentiments: ['Operates in the gap between official policy and commercial reality', 'Has a working knowledge of Japanese and enough Chinese to deal', 'Two sets of books; neither is the real one'],
    iconPrompt: 'joseon dynasty korean maritime trader ship busan port japanese goods cargo sea coast prosperous risky traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#maritime_trader.png',
  },
  // ── Spiritual ─────────────────────────────────────────────────────────
  {
    title: 'Buddhist Monk',
    industry: 'Spiritual',
    economicTier: 2,
    statAffinity: { wisdom: 1.4, constitution: 1.1, intelligence: 1.2 },
    sentiments: ['Outside the social order, which is both prison and sanctuary', 'Holds centuries of knowledge the court would prefer to forget', 'Feeds the exiled and the desperate without asking why they are here'],
    iconPrompt: 'joseon dynasty korean buddhist monk gray robe shaved head mountain temple incense prayer beads serene steadfast traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#buddhist_monk.png',
  },
  {
    title: 'Mudang (Shaman)',
    industry: 'Spiritual',
    economicTier: 2,
    statAffinity: { charisma: 1.3, wisdom: 1.2, constitution: 1.1 },
    sentiments: ['Despised by the Confucian order; indispensable to the families of that order', 'Hears what people do not say to priests or officials', 'The ritual is real, whatever the scholars think'],
    iconPrompt: 'joseon dynasty korean mudang shaman female ritual ceremony colorful costume drum spirit possession traditional folk painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#mudang_shaman.png',
  },
  {
    title: 'Court Physician',
    industry: 'Spiritual',
    economicTier: 3,
    statAffinity: { intelligence: 1.3, wisdom: 1.3, dexterity: 1.1 },
    sentiments: ['Trusted with secrets that could destroy houses', 'Navigates the jungin ceiling by being too necessary to dismiss', 'Knows which palace ailments are not illness'],
    iconPrompt: 'joseon dynasty korean court physician acupuncture herbs medical diagnosis careful skilled practical traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#court_physician.png',
  },
  // ── Labor ─────────────────────────────────────────────────────────────
  {
    title: 'Rice Farmer',
    industry: 'Labor',
    economicTier: 2,
    statAffinity: { constitution: 1.4, strength: 1.2, wisdom: 1.1 },
    sentiments: ['Watches the weather the way scholars watch the king', 'Has no illusions about what the landlord is', 'The land is not his but the knowledge of it is'],
    iconPrompt: 'joseon dynasty korean rice farmer paddy field transplanting seedlings plain hanbok straw hat muddy hands hardworking traditional folk painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#rice_farmer.png',
  },
  // ── Service ───────────────────────────────────────────────────────────
  {
    title: 'Palace Court Lady',
    industry: 'Service',
    economicTier: 3,
    statAffinity: { charisma: 1.2, wisdom: 1.2, intelligence: 1.1 },
    sentiments: ['Trained to be invisible and indispensable simultaneously', 'Carries information that would shake the throne', 'Has learned to want very small things very precisely'],
    iconPrompt: 'joseon dynasty korean court lady nagin palace service elegant green hanbok court duties discreet attentive traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#palace_court_lady.png',
  },
  {
    title: 'Nobi (House Slave)',
    industry: 'Service',
    economicTier: 1,
    statAffinity: { dexterity: 1.2, constitution: 1.2, wisdom: 1.1 },
    sentiments: ['Knows the house better than its owner', 'Survival has required calibrating every person in the compound', 'Freedom is the thing not spoken of'],
    iconPrompt: 'joseon dynasty korean nobi servant slave household duties plain clothing serving master house compound cautious dignified traditional folk painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#nobi_house_slave.png',
  },
  // ── Gisaeng Arts ──────────────────────────────────────────────────────
  {
    title: 'Gisaeng Madam',
    industry: 'Gisaeng Arts',
    economicTier: 4,
    statAffinity: { charisma: 1.4, intelligence: 1.3, wisdom: 1.2 },
    sentiments: ['Runs the most sophisticated information network in the province', 'Has buried two magistrates and outlasted four governors', 'Sentiment is a luxury; discretion is a business model'],
    iconPrompt: 'joseon dynasty korean gisaeng madam older woman elegant authority jeweled hairpin silk robe commanding shrewd banquet hall traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#gisaeng_madam.png',
  },
  {
    title: 'Gisaeng (Entertainer-Courtesan)',
    industry: 'Gisaeng Arts',
    economicTier: 3,
    nsfw: true,
    statAffinity: { charisma: 1.4, dexterity: 1.2, intelligence: 1.2 },
    sentiments: ['More educated than most of her clients', 'Uses performance as armor and armor as performance', 'Has heard the confession of three men who should have known better'],
    iconPrompt: 'joseon dynasty korean gisaeng female entertainer haegeum musician court performance elegant silk hanbok ornate binyeo hairpin graceful traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/PROFESSIONS#gisaeng_entertainer.png',
  },
];
