// genres/historical-korea-joseon-dynasty/tensions.js
// Active pressures and ongoing conflicts for Joseon Dynasty characters.

export const TENSIONS = [
  {
    id: 'faction_enemy',
    label: 'A Rival Faction Has Targeted Them',
    description: 'Enemies in the court bungdang system are actively working to discredit or destroy them through slander, false accusation, or manipulation of the examination system',
    toneTag: 'political',
    iconPrompt: 'joseon dynasty korean court faction intrigue rival officials whispers plotting scheming palace corridor traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#faction_enemy.webp',
  },
  {
    id: 'debt_of_favor',
    label: 'Owe an Unpayable Debt of Obligation',
    description: 'A powerful person saved or elevated them — and now expects repayment in a form that conflicts with their principles',
    toneTag: 'dramatic',
    iconPrompt: 'joseon dynasty korean obligation debt powerful patron pressure bowing tense meeting request refusal traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#debt_of_favor.webp',
  },
  {
    id: 'clan_disgrace',
    label: 'Family Name Under a Shadow',
    description: 'A relative\'s disgrace — treason, corruption, or conversion — casts legal and social suspicion over the whole clan',
    toneTag: 'gritty',
    iconPrompt: 'joseon dynasty korean family disgrace shame clan house gate closed ostracism avoidance shadow traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#clan_disgrace.webp',
  },
  {
    id: 'forbidden_love',
    label: 'A Forbidden Attachment',
    description: 'In love with someone the social order forbids: across class lines, into a rival clan, or within a relationship that Confucian law names as impossible',
    toneTag: 'romantic',
    iconPrompt: 'joseon dynasty korean forbidden love secret meeting hanbok couple moonlight garden wall hidden longing traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#forbidden_love.webp',
  },
  {
    id: 'imperial_commission',
    label: 'Under Pressure from a Royal Commission',
    description: 'Has received an official command from the throne or a senior official — the task is dangerous, the margin for failure is zero',
    toneTag: 'high_stakes',
    iconPrompt: 'joseon dynasty korean royal command commission official document seal pressure obligation court messenger traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#imperial_commission.webp',
  },
  {
    id: 'gwageo_pressure',
    label: 'Family Obsession with the Examinations',
    description: 'The entire household\'s status, finances, and hopes rest on them passing the gwageo — and they are not sure they want to',
    toneTag: 'dramatic',
    iconPrompt: 'joseon dynasty korean gwageo exam family pressure studying night candle anxious scholar family watching expecting traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#gwageo_pressure.webp',
  },
  {
    id: 'bandit_passes',
    label: 'In Contact with a Bandit Network',
    description: 'Has been drawn into the orbit of a provincial bandit or rebel leader — provides information, shelter, or passage they cannot easily stop providing',
    toneTag: 'criminal',
    criminalFlag: true,
    iconPrompt: 'joseon dynasty korean bandit network secret contact mountain hideout nervous messenger night meeting dangerous traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#bandit_passes.webp',
  },
  {
    id: 'inheritance_dispute',
    label: 'Clan Inheritance Dispute',
    description: 'The clan compound, land, or lineage position is contested — a cousin, a concubine\'s son, or a creditor is making a legal case',
    toneTag: 'bitter',
    iconPrompt: 'joseon dynasty korean inheritance dispute clan elders meeting argument property records legal document tense traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#inheritance_dispute.webp',
  },
  {
    id: 'dangerous_knowledge',
    label: 'Knows Something Lethal',
    description: 'Is in possession of information — a bribe, a cover-up, a falsified record — that would destroy a powerful person if spoken',
    toneTag: 'high_stakes',
    iconPrompt: 'joseon dynasty korean dangerous secret knowledge hidden document cautious fear powerful enemy night alone fearful traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#dangerous_knowledge.webp',
  },
  {
    id: 'rebel_contact',
    label: 'Connected to a Rebel Movement',
    description: 'Has family, friends, or sympathies tied to a peasant uprising or political resistance — one informant away from arrest',
    toneTag: 'criminal',
    criminalFlag: true,
    iconPrompt: 'joseon dynasty korean rebel movement peasant uprising secret meeting night forest banner protest connection dangerous traditional folk painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#rebel_contact.webp',
  },
  {
    id: 'haunted_by_imjin',
    label: 'Haunted by the Imjin War',
    description: 'Carries specific memories of the Japanese invasion that they have never been able to set down — affects sleep, judgment, and reaction',
    toneTag: 'dark',
    iconPrompt: 'joseon dynasty korean imjin war haunted veteran nightmare flashback memory trauma survivor quiet withdrawn traditional painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#haunted_by_imjin.webp',
  },
  {
    id: 'marriage_trap',
    label: 'Trapped in a Political Marriage',
    description: 'The marriage was an alliance, not a choice — and one of the parties is now actively working against the other\'s family',
    toneTag: 'bitter',
    iconPrompt: 'joseon dynasty korean political marriage trap cold couple formal duty resentment obligation inner quarters traditional court painting',
    iconPath: 'generator/genres/historical-korea-joseon-dynasty/icons/TENSIONS#marriage_trap.webp',
  },
];
