<#
    FateVend static server — Windows / PowerShell edition.

    The exact equivalent of serve.sh, for people who don't have bash. It writes
    generator/config.js from the root .env, serves web/ over HTTP, and starts
    the AI Dungeon import server if Node.js happens to be installed.

    Deliberately depends on nothing but Windows itself: no Python, no Node, no
    WSL, no Git Bash. The HTTP server is System.Net.HttpListener, which ships
    with .NET, so a fresh Windows machine can run the app by double-clicking
    Start-FateVend.cmd. Node is only consulted for the optional importer.

    Usage:  powershell -ExecutionPolicy Bypass -File serve.ps1
    or:     double-click Start-FateVend.cmd (which does the above for you)

    Stop it with Ctrl+C.
#>

[CmdletBinding()]
param(
    # First port to try. Moves forward if it's taken, exactly like serve.sh.
    [int]$Port = 8080,
    # Skip opening a browser window on startup.
    [switch]$NoBrowser
)

$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath $PSScriptRoot   # serve from web/, never the repo root

# ── Retire a stale instance ───────────────────────────────────────────────────
# Same trick as serve.sh: instances identify themselves over HTTP rather than by
# PID, because a PID recorded by one shell is meaningless to another. Sweeping
# by marker means serve.ps1 and serve.sh can each shut the other one down.
# Cheap "is anything listening here at all" test, used to skip the expensive
# HTTP probe on the ~30 ports that are almost always empty. Invoke-WebRequest
# costs the better part of a second even against a closed port, which turned
# this sweep into a 30-second startup delay before the app would load.
function Test-PortOpen {
    param([int]$ProbePort)
    $client = New-Object Net.Sockets.TcpClient
    try {
        $async = $client.BeginConnect('127.0.0.1', $ProbePort, $null, $null)
        if (-not $async.AsyncWaitHandle.WaitOne(120)) { return $false }
        $client.EndConnect($async)
        return $true
    } catch {
        return $false
    } finally {
        $client.Close()
    }
}

function Test-FateVendServer {
    param([int]$ProbePort)
    if (-not (Test-PortOpen -ProbePort $ProbePort)) { return $false }
    try {
        $r = Invoke-WebRequest -Uri "http://127.0.0.1:$ProbePort/__fatevend_ping__" `
            -TimeoutSec 1 -UseBasicParsing
        return ($r.Content -eq 'fatevend-static')
    } catch {
        # Something else owns the port — not ours to shut down.
        return $false
    }
}

$stopped = @()
foreach ($p in $Port..($Port + 30)) {
    if (Test-FateVendServer -ProbePort $p) {
        try {
            Invoke-WebRequest -Uri "http://127.0.0.1:$p/__fatevend_shutdown__" `
                -TimeoutSec 2 -UseBasicParsing | Out-Null
        } catch {
            # A shutdown route that kills the process mid-response looks like a
            # failed request from here. That's the intended outcome, not an error.
        }
        $stopped += $p
    }
}
if ($stopped.Count -gt 0) {
    Write-Host "Stopped stale FateVend server(s) on port(s): $($stopped -join ', ')"
    Start-Sleep -Milliseconds 400
}

# ── Write generator/config.js from ../.env ────────────────────────────────────
# So the browser can read API keys without the .env file itself ever being
# served. Entirely optional: index.html has an onerror fallback and the app
# works fine with keys typed into Settings instead.
$envPath = Join-Path (Split-Path $PSScriptRoot -Parent) '.env'
$keys = @{}
if (Test-Path -LiteralPath $envPath) {
    foreach ($line in Get-Content -LiteralPath $envPath) {
        if ($line -match '^\s*([A-Z_]+)\s*=\s*(.+?)\s*$') {
            $value = $Matches[2]
            if ($value.Length -ge 2 -and $value[0] -eq $value[-1] -and ($value[0] -eq '"' -or $value[0] -eq "'")) {
                $value = $value.Substring(1, $value.Length - 2)
            }
            $keys[$Matches[1]] = $value
        }
    }
}

function Get-EnvValue {
    param([string]$Name)
    if ($keys.ContainsKey($Name)) { return $keys[$Name] }
    return ''
}

# Stamp the running commit so Settings can show which version this is. Git is
# optional — a ZIP download has no repository, which is a supported way to run.
$gitVersion = 'dev'
if (Get-Command git -ErrorAction SilentlyContinue) {
    try {
        $rev = & git -C .. rev-parse --short HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $rev) {
            $gitVersion = $rev.Trim()
            $dirty = & git -C .. status --porcelain 2>$null
            if ($LASTEXITCODE -eq 0 -and $dirty) { $gitVersion += '-dirty' }
        }
    } catch {
        $gitVersion = 'dev'
    }
}

$configLines = @(
    '// Auto-generated by serve.ps1 - do not commit'
    "window.__ANTHROPIC_KEY  = $(ConvertTo-Json (Get-EnvValue 'ANTHROPIC_API_KEY'));"
    "window.__GEMINI_KEY     = $(ConvertTo-Json (Get-EnvValue 'GEMINI_API_KEY'));"
    "window.__SD_URL         = $(ConvertTo-Json (Get-EnvValue 'SD_URL'));"
    "window.__STABILITY_KEY  = $(ConvertTo-Json (Get-EnvValue 'STABILITY_API_KEY'));"
    "window.__OLLAMA_URL     = $(ConvertTo-Json (Get-EnvValue 'OLLAMA_URL'));"
    "window.__OLLAMA_MODEL   = $(ConvertTo-Json (Get-EnvValue 'OLLAMA_MODEL'));"
    "window.__TTS_KOKORO_URL = $(ConvertTo-Json (Get-EnvValue 'TTS_KOKORO_URL'));"
    "window.__TTS_OPENAI_KEY = $(ConvertTo-Json (Get-EnvValue 'TTS_OPENAI_KEY'));"
    "window.__NSFW_SUFFIX    = $(ConvertTo-Json (Get-EnvValue 'NSFW_IMAGE_PROMPT_SUFFIX'));"
    "window.__GIT_VERSION__  = $(ConvertTo-Json $gitVersion);"
)
# WriteAllText with an explicit no-BOM encoding, not Out-File -Encoding utf8:
# PowerShell 5.1's utf8 means "UTF-8 with BOM", and serve.sh writes this same
# file without one. Browsers tolerate a BOM on a script, but having the two
# servers emit byte-different files invites a confusing diff later.
[IO.File]::WriteAllText(
    (Join-Path $PSScriptRoot 'generator/config.js'),
    ($configLines -join "`r`n") + "`r`n",
    (New-Object Text.UTF8Encoding($false))
)

$anthropicLen = (Get-EnvValue 'ANTHROPIC_API_KEY').Length
$geminiLen = (Get-EnvValue 'GEMINI_API_KEY').Length
Write-Host "config.js written (anthropic key length: $anthropicLen, gemini key length: $geminiLen, git version: $gitVersion)"
if ($anthropicLen -eq 0 -and $geminiLen -eq 0) {
    Write-Host "  No API keys found in .env - that's fine. Enter them in Settings, or"
    Write-Host "  just spin the reels: rolling a character needs no key at all."
}

# ── Optional: AI Dungeon import server ───────────────────────────────────────
# Needs Node. Without it the app simply hides the "Import to AI Dungeon" button;
# every other way of getting a scenario out (Copy, Download Package) still works.
$importer = $null
if (Get-Command node -ErrorAction SilentlyContinue) {
    try {
        $importer = Start-Process -FilePath 'node' -ArgumentList 'tools/aidungeon-server.mjs' `
            -NoNewWindow -PassThru
        Write-Host 'AI Dungeon import server started on http://localhost:7432'
    } catch {
        Write-Host "Could not start the AI Dungeon import server: $($_.Exception.Message)"
    }
} else {
    Write-Host 'Node.js not found - skipping the AI Dungeon import server.'
    Write-Host '  The app still works; the one-click "Import to AI Dungeon" button stays hidden.'
    Write-Host '  See INSTALL.md if you want it.'
}

# ── Static file server ───────────────────────────────────────────────────────
$mimeTypes = @{
    '.html' = 'text/html; charset=utf-8'
    '.js'   = 'text/javascript; charset=utf-8'
    '.mjs'  = 'text/javascript; charset=utf-8'
    '.css'  = 'text/css; charset=utf-8'
    '.json' = 'application/json; charset=utf-8'
    '.svg'  = 'image/svg+xml'
    '.webp' = 'image/webp'
    '.png'  = 'image/png'
    '.jpg'  = 'image/jpeg'
    '.jpeg' = 'image/jpeg'
    '.gif'  = 'image/gif'
    '.ico'  = 'image/x-icon'
    '.mp3'  = 'audio/mpeg'
    '.wav'  = 'audio/wav'
    '.ogg'  = 'audio/ogg'
    '.woff' = 'font/woff'
    '.woff2' = 'font/woff2'
    '.ttf'  = 'font/ttf'
    '.zip'  = 'application/zip'
    '.txt'  = 'text/plain; charset=utf-8'
    '.md'   = 'text/markdown; charset=utf-8'
}

$listener = New-Object System.Net.HttpListener
$bound = $false
for ($p = $Port; $p -lt $Port + 30; $p++) {
    try {
        $listener.Prefixes.Clear()
        # localhost-only: binding all interfaces with HttpListener needs an
        # elevated URL ACL reservation, and prompting for admin on first run is
        # exactly the kind of friction this script exists to avoid.
        $listener.Prefixes.Add("http://localhost:$p/")
        $listener.Start()
        $Port = $p
        $bound = $true
        break
    } catch {
        continue
    }
}
if (-not $bound) {
    Write-Host "Could not bind any port in $Port..$($Port + 30)."
    exit 1
}

$root = (Get-Item -LiteralPath $PSScriptRoot).FullName
Write-Host ''
Write-Host "  App is at http://localhost:$Port/"
Write-Host '  Press Ctrl+C to stop.'
Write-Host ''

if (-not $NoBrowser) {
    Start-Process "http://localhost:$Port/" | Out-Null
}

# Requests are served on the accept thread, one at a time. That sounds wrong for
# a cold load of ~350 files, and a runspace pool was tried here — it was no
# faster (2936ms vs 2873ms), because the per-request cost of [PowerShell]::Create()
# plus AddScript() lands back on the accept thread and cancels out whatever the
# workers save.
#
# The cost was never concurrency. It was per-request cmdlet overhead: swapping
# Test-Path + Get-Item for a single IO.FileInfo took a cold load from ~2.9s to
# ~650ms, faster than the Python server. Keep filesystem work in this loop to
# .NET calls rather than cmdlets. Repeat loads are ~250ms thanks to the 304
# handling below.
function Invoke-Request {
    param($context, $root, $mimeTypes)

    $request = $context.Request
    $response = $context.Response
    try {
        # RawUrl, not Url.AbsolutePath: icon filenames contain '#', which the
        # app sends percent-encoded. AbsolutePath hands back a decoded string in
        # which that '#' is indistinguishable from a fragment delimiter.
        $path = [Uri]::UnescapeDataString(($request.RawUrl -split '\?')[0])
        if ($path.EndsWith('/')) { $path += 'index.html' }

        $relative = $path.TrimStart('/').Replace('/', [IO.Path]::DirectorySeparatorChar)
        $full = [IO.Path]::GetFullPath((Join-Path $root $relative))

        # Never serve anything outside web/ — the repo root holds .env.
        if (-not $full.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)) {
            $response.StatusCode = 403
            $response.Close()
            return
        }

        $file = New-Object IO.FileInfo($full)
        if (-not $file.Exists) {
            $response.StatusCode = 404
            $body = [Text.Encoding]::UTF8.GetBytes('404 - not found')
            $response.ContentLength64 = $body.Length
            $response.OutputStream.Write($body, 0, $body.Length)
            $response.Close()
            return
        }

        # no-cache, not no-store: the browser keeps a copy but must revalidate,
        # so an edited icon is never stale while an unchanged one costs an empty
        # 304 instead of resending its body. Same reasoning as serve.sh.
        $response.Headers.Add('Cache-Control', 'no-cache')

        $modified = $file.LastWriteTimeUtc
        # HTTP dates have 1-second resolution; NTFS timestamps do not. Without
        # truncating, a file always looks fractionally newer than the copy the
        # browser just cached and every 304 would come back as a 200.
        $modified = $modified.AddTicks(-($modified.Ticks % [TimeSpan]::TicksPerSecond))
        $response.Headers.Add('Last-Modified', $modified.ToString('r'))

        $ims = $request.Headers['If-Modified-Since']
        if ($ims) {
            $since = [DateTime]::MinValue
            if ([DateTime]::TryParse($ims, [ref]$since) -and $modified -le $since.ToUniversalTime()) {
                $response.StatusCode = 304
                $response.Close()
                return
            }
        }

        $ext = $file.Extension.ToLowerInvariant()
        $type = 'application/octet-stream'
        if ($mimeTypes.ContainsKey($ext)) { $type = $mimeTypes[$ext] }
        $response.ContentType = $type

        $bytes = [IO.File]::ReadAllBytes($full)
        $response.ContentLength64 = $bytes.Length
        $response.OutputStream.Write($bytes, 0, $bytes.Length)
        $response.Close()
    } catch {
        # A cancelled request (the browser switching genres mid-preload) closes
        # the socket while we're still writing. Normal traffic, not a fault.
        try { $response.Close() } catch { }
    }
}

try {
    while ($listener.IsListening) {
        $context = $listener.GetContext()

        $controlPath = [Uri]::UnescapeDataString(($context.Request.RawUrl -split '\?')[0])
        if ($controlPath -eq '/__fatevend_ping__') {
            $body = [Text.Encoding]::UTF8.GetBytes('fatevend-static')
            $context.Response.ContentType = 'text/plain'
            $context.Response.ContentLength64 = $body.Length
            $context.Response.OutputStream.Write($body, 0, $body.Length)
            $context.Response.Close()
            continue
        }
        if ($controlPath -eq '/__fatevend_shutdown__') {
            $context.Response.StatusCode = 200
            $context.Response.Close()
            break
        }

        Invoke-Request -context $context -root $root -mimeTypes $mimeTypes
    }
} finally {
    if ($listener.IsListening) { $listener.Stop() }
    $listener.Close()
    if ($importer -and -not $importer.HasExited) {
        Stop-Process -Id $importer.Id -Force -ErrorAction SilentlyContinue
    }
    Write-Host 'Server stopped.'
}
