#!/usr/bin/env bash
# Serve from web/ so .env and other project files are never exposed.
# App is at http://localhost:8080/ (or the next free port, if 8080 is taken —
# watch the "Serving HTTP on ..." line below for the actual port used).
cd "$(dirname "$0")"

STATIC_PID_FILE=".serve-static.pid"
AIDUNGEON_PID_FILE=".serve-aidungeon.pid"

# Stop anything left running from a previous run of this script before
# starting new instances — a closed terminal or a killed shell doesn't always
# take its background children with it, so a stale process can otherwise keep
# running (and serving stale code) indefinitely.
kill_stale() {
  local pidfile="$1" label="$2"
  if [ -f "$pidfile" ]; then
    local pid
    pid=$(cat "$pidfile" 2>/dev/null)
    if [ -n "$pid" ]; then
      echo "Stopping previous $label (PID $pid)…"
      # Plain `kill` only reliably signals processes this same shell/MSYS
      # runtime spawned itself (e.g. `node ... &` backgrounded in this
      # script) — a PID that a *different* prior run wrote to disk (like a
      # Python process's own self-reported native Windows PID) often isn't
      # in bash's PID namespace at all, so `kill` silently no-ops on it.
      # `taskkill` operates on real Windows PIDs directly and reliably
      # catches that case; try both, ignore errors either way.
      kill "$pid" 2>/dev/null
      command -v taskkill &>/dev/null && taskkill //F //PID "$pid" >/dev/null 2>&1
      sleep 0.3
      kill -9 "$pid" 2>/dev/null
    fi
    rm -f "$pidfile"
  fi
}
kill_stale "$AIDUNGEON_PID_FILE" "AI Dungeon import server"
kill_stale "$STATIC_PID_FILE" "static file server"

# Write config.js from the root .env so the browser can read the API key
# without the .env file itself ever being served. Also stamps the current git
# commit so the Settings modal can show which version is actually running.
python3 - <<'PY'
import os, re, json, pathlib, subprocess

env_path = pathlib.Path('../.env')   # CWD is web/, set by the cd above
keys = {}
if env_path.exists():
    for line in env_path.read_text().splitlines():
        m = re.match(r'^([A-Z_]+)=(.+)', line.strip())
        if m:
            keys[m.group(1)] = m.group(2)

try:
    git_version = subprocess.run(
        ['git', 'rev-parse', '--short', 'HEAD'],
        cwd='..', capture_output=True, text=True, check=True,
    ).stdout.strip()
    dirty = subprocess.run(
        ['git', 'status', '--porcelain'],
        cwd='..', capture_output=True, text=True, check=True,
    ).stdout.strip()
    if dirty:
        git_version += '-dirty'
except (subprocess.CalledProcessError, FileNotFoundError):
    git_version = 'dev'

out = pathlib.Path('generator/config.js')
out.write_text(
    '// Auto-generated by serve.sh — do not commit\n'
    f'window.__ANTHROPIC_KEY  = {json.dumps(keys.get("ANTHROPIC_API_KEY", ""))};\n'
    f'window.__GEMINI_KEY     = {json.dumps(keys.get("GEMINI_API_KEY", ""))};\n'
    f'window.__SD_URL         = {json.dumps(keys.get("SD_URL", ""))};\n'
    f'window.__STABILITY_KEY  = {json.dumps(keys.get("STABILITY_API_KEY", ""))};\n'
    f'window.__GIT_VERSION__  = {json.dumps(git_version)};\n'
)
print(f'config.js written (anthropic key length: {len(keys.get("ANTHROPIC_API_KEY",""))}, gemini key length: {len(keys.get("GEMINI_API_KEY",""))}, git version: {git_version})')
PY

# Start the AI Dungeon import server in the background (requires Node.js + Playwright).
# The web app shows an "Import to AI Dungeon" button only when this is reachable.
if command -v node &>/dev/null; then
  node tools/aidungeon-server.mjs &
  AIDUNGEON_SERVER_PID=$!
  echo "$AIDUNGEON_SERVER_PID" > "$AIDUNGEON_PID_FILE"
  # INT/TERM explicitly, not just EXIT — systemd stops services with SIGTERM,
  # and without a handler for it bash kills the child but skips the EXIT trap.
  trap 'kill $AIDUNGEON_SERVER_PID 2>/dev/null; rm -f "$AIDUNGEON_PID_FILE" "$STATIC_PID_FILE"; exit 0' EXIT INT TERM
else
  echo "node not found — AI Dungeon import server not started."
fi

# Plain http.server sends no Cache-Control headers, so browsers fall back to
# heuristic caching and can keep showing stale assets (e.g. edited genre icons)
# after a file changes on disk. Force no-store so every request is fresh.
# -u: unbuffered stdout, so the port/URL message (and journalctl -f) show up
# immediately instead of sitting in a buffer that's lost if the process is killed.
python3 -u - <<'PY'
import http.server, socket, os, pathlib, platform, subprocess

# Record our own PID so the next run of serve.sh can stop us if we're
# still around (e.g. this terminal got closed without a clean Ctrl+C).
pathlib.Path('.serve-static.pid').write_text(str(os.getpid()))

def describe_port_owner(port):
    """Best-effort lookup of what's already listening on `port`, so the
    "port is taken" message says who — not just that it happened."""
    try:
        if platform.system() == 'Windows':
            out = subprocess.run(['netstat', '-ano'], capture_output=True, text=True, timeout=5).stdout
            pid = None
            for line in out.splitlines():
                parts = line.split()
                if len(parts) >= 5 and parts[0] == 'TCP' and parts[1].endswith(f':{port}') and parts[-2] == 'LISTENING':
                    pid = parts[-1]
                    break
            if not pid:
                return None
            tl = subprocess.run(
                ['tasklist', '/FI', f'PID eq {pid}', '/FO', 'CSV', '/NH'],
                capture_output=True, text=True, timeout=5,
            ).stdout.strip()
            name = tl.split(',')[0].strip('"') if tl else None
            return f'PID {pid}' + (f' ({name})' if name else '')
        else:
            out = subprocess.run(
                ['lsof', '-nP', f'-i:{port}', '-sTCP:LISTEN'],
                capture_output=True, text=True, timeout=5,
            ).stdout
            lines = [l for l in out.splitlines() if l and not l.startswith('COMMAND')]
            if not lines:
                return None
            parts = lines[0].split()
            return f'PID {parts[1]} ({parts[0]})'
    except Exception:
        return None

class NoCacheHandler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header('Cache-Control', 'no-store')
        super().end_headers()

class QuietThreadingHTTPServer(http.server.ThreadingHTTPServer):
    # A cancelled image request (e.g. the browser switching genres mid-preload)
    # closes the socket while we're still writing to it — a normal occurrence,
    # not a bug. Suppress just that traceback; still log anything else.
    def handle_error(self, request, client_address):
        import sys
        exc = sys.exc_info()[1]
        if isinstance(exc, (BrokenPipeError, ConnectionResetError, ConnectionAbortedError)):
            return
        super().handle_error(request, client_address)

def find_free_port(preferred, bind, tries=20):
    port = preferred
    for _ in range(tries):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind((bind, port))
                return port
            except OSError:
                port += 1
    raise RuntimeError(f'No free port found in range {preferred}-{port}')

BIND = '0.0.0.0'
PORT = find_free_port(8080, BIND)
if PORT != 8080:
    owner = describe_port_owner(8080)
    if owner:
        print(f'Port 8080 is already in use by {owner} — using {PORT} instead.')
    else:
        print(f'Port 8080 is already in use — using {PORT} instead.')
print(f'App is at http://localhost:{PORT}/')

http.server.test(HandlerClass=NoCacheHandler, ServerClass=QuietThreadingHTTPServer, port=PORT, bind=BIND)
PY
