#!/usr/bin/env bash
# Serve from web/ so .env and other project files are never exposed.
# App is at http://localhost:8080/
cd "$(dirname "$0")"

# Write config.js from the root .env so the browser can read the API key
# without the .env file itself ever being served.
python3 - <<'PY'
import os, re, json, pathlib

env_path = pathlib.Path('../.env')   # CWD is web/, set by the cd above
keys = {}
if env_path.exists():
    for line in env_path.read_text().splitlines():
        m = re.match(r'^([A-Z_]+)=(.+)', line.strip())
        if m:
            keys[m.group(1)] = m.group(2)

out = pathlib.Path('generator/config.js')
out.write_text(
    '// Auto-generated by serve.sh — do not commit\n'
    f'window.__ANTHROPIC_KEY  = {json.dumps(keys.get("ANTHROPIC_API_KEY", ""))};\n'
    f'window.__GEMINI_KEY     = {json.dumps(keys.get("GEMINI_API_KEY", ""))};\n'
    f'window.__SD_URL         = {json.dumps(keys.get("SD_URL", ""))};\n'
    f'window.__STABILITY_KEY  = {json.dumps(keys.get("STABILITY_API_KEY", ""))};\n'
)
print(f'config.js written (anthropic key length: {len(keys.get("ANTHROPIC_API_KEY",""))}, gemini key length: {len(keys.get("GEMINI_API_KEY",""))})')
PY

# Start the AI Dungeon import server in the background (requires Node.js + Playwright).
# The web app shows an "Import to AI Dungeon" button only when this is reachable.
if command -v node &>/dev/null; then
  node tools/aidungeon-server.mjs &
  AIDUNGEON_SERVER_PID=$!
  # INT/TERM explicitly, not just EXIT — systemd stops services with SIGTERM,
  # and without a handler for it bash kills the child but skips the EXIT trap.
  trap 'kill $AIDUNGEON_SERVER_PID 2>/dev/null; exit 0' EXIT INT TERM
else
  echo "node not found — AI Dungeon import server not started."
fi

# Plain http.server sends no Cache-Control headers, so browsers fall back to
# heuristic caching and can keep showing stale assets (e.g. edited genre icons)
# after a file changes on disk. Force no-store so every request is fresh.
python3 - <<'PY'
import http.server, socketserver

class NoCacheHandler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header('Cache-Control', 'no-store')
        super().end_headers()

class QuietThreadingHTTPServer(http.server.ThreadingHTTPServer):
    # A cancelled image request (e.g. the browser switching genres mid-preload)
    # closes the socket while we're still writing to it — a normal occurrence,
    # not a bug. Suppress just that traceback; still log anything else.
    def handle_error(self, request, client_address):
        import sys
        exc = sys.exc_info()[1]
        if isinstance(exc, (BrokenPipeError, ConnectionResetError, ConnectionAbortedError)):
            return
        super().handle_error(request, client_address)

http.server.test(HandlerClass=NoCacheHandler, ServerClass=QuietThreadingHTTPServer, port=8080, bind='0.0.0.0')
PY
